### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1007]
Plugins... refresh..

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/utils.py", line 260, in check
    self.callback(result)
  File "/home/andre/emesene/emesene/gui/gtkui/ExtensionList.py", line 278, in show_update_callback
    self.show_update()
  File "/home/andre/emesene/emesene/gui/gtkui/PluginWindow.py", line 56, in show_update
    description=pluginmanager.plugin_description(name))
  File "/home/andre/emesene/emesene/pluginmanager.py", line 259, in plugin_description
    return self._plugins[name].get_description()
  File "/home/andre/emesene/emesene/pluginmanager.py", line 159, in get_description
    description = self.meta.get('description', '')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Sbte** [comment]
Fixed now I hope. Thanks for reporting this!
