### ISSUE TITLE
 'NoneType' object has no attribute 'Empty'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1011]
Reproduce:

1.Open Emesene in Console
2. Login
3. Click Quit

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 136, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

**Comment by c10ud** [comment]
cannot be fixed, in some issue i should have explained the reason

**Comment by zipatei** [comment]
oh yes, about cancel in console... so reverse..no problem.

**Comment by Sbte** [comment]
Well it's possible to fix it, by catching an AttributeError, but the you probably catch every AttributeError that papyon possibly sends to us.

**Comment by zipatei** [comment]
@c10ud @Sbte 

Since we have already catch to capture ctrl + c, it is not possible to fix this problem that always happens when you click quit in MainMenu?

**Comment by zipatei** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 137, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

**Comment by c10ud** [comment]
interpreter shutdown errors are (impossibru?) difficult to catch,
reference: google and some other bug report here

2012/4/19 zipatei
reply@reply.github.com:
