### ISSUE TITLE
TypeError: __common_errback() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1027]
```
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 253, in _error_handler
    self._response_handler(transport, error.response)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 240, in _response_handler
    user_data)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 134, in _HandleSOAPFault
    run(errback, error)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
TypeError: __common_errback() takes at least 3 arguments (2 given)
```

Reproduce:

Just Login (Maybe broken profile)

**Comment by Sbte** [comment]
Maybe at https://github.com/emesene/emesene/blob/dde60d7fda124ec85ee18d572a420ffe91c252e1/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/content_roaming.py#L117

there should be

`(self.__common_errback, None))`

That or I just don't have a clue...

**Comment by zipatei** [comment]
yes... this fix this bug.
