### ISSUE TITLE
TypeError when typing a message to an offline contact

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1029]
```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/base/Worker.py", line 183, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/sven/emesene/emesene/e3/papylib/Worker.py", line 1341, in _handle_action_send_message
    self.oim_box.send_message(first_dude, message.body)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/util/decorator.py", line 111, in new_function
    func(*args, **kwargs)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 314, in send_message
    self.__send_unmanaged_message(recipient, message)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 293, in __send_unmanaged_message
    self._client._protocol.send_unmanaged_message(recipient, message)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/notification.py", line 286, in send_unmanaged_message
    payload=message, callback=callback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/base.py", line 90, in _send_command
    increment, callback, errback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/transport.py", line 213, in send_command_ex
    self.send_command(cmd, increment, callback, errback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/transport.py", line 289, in send_command
    logger.debug('>>> ' + unicode(command))
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 226, in __unicode__
    return unicode(CommandPrinter(self))
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 36, in __unicode__
    return printer()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 68, in _print_UUM
    result += "\n" + repr(command.payload)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/message.py", line 71, in __repr__
    message += '\t' + escape_string(self.body).\
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/util/debug.py", line 27, in escape_string
    for c in string:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/base/Worker.py", line 183, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/sven/emesene/emesene/e3/papylib/Worker.py", line 1341, in _handle_action_send_message
    self.oim_box.send_message(first_dude, message.body)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/util/decorator.py", line 111, in new_function
    func(*args, **kwargs)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 314, in send_message
    self.__send_unmanaged_message(recipient, message)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 293, in __send_unmanaged_message
    self._client._protocol.send_unmanaged_message(recipient, message)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/notification.py", line 286, in send_unmanaged_message
    payload=message, callback=callback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/base.py", line 90, in _send_command
    increment, callback, errback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/transport.py", line 213, in send_command_ex
    self.send_command(cmd, increment, callback, errback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/transport.py", line 289, in send_command
    logger.debug('>>> ' + unicode(command))
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 226, in __unicode__
    return unicode(CommandPrinter(self))
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 36, in __unicode__
    return printer()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/command.py", line 68, in _print_UUM
    result += "\n" + repr(command.payload)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp/message.py", line 71, in __repr__
    message += '\t' + escape_string(self.body).\
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/util/debug.py", line 27, in escape_string
    for c in string:
TypeError: 'NoneType' object is not iterable
```

**Comment by c10ud** [comment]
i think you're trying to send typing notifications through UUMs

**Comment by c10ud** [comment]
post-reading: maybe not, but a little extra info would be nice

**Comment by Sbte** [comment]
I'm trying to reproduce this with -vvv
