### ISSUE TITLE
Icon of transfer and block contact should be disabled on facebook accounts.

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1036]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Dialog.py", line 139, in chooser_cb
    response_cb(response, filename)
  File "/home/andre/emesene/emesene/gui/base/Handler.py", line 553, in open_file_cb
    self.conversation.on_filetransfer_invite(filename, filepath)
  File "/home/andre/emesene/emesene/gui/base/Conversation.py", line 217, in on_filetransfer_invite
    self.session.filetransfer_invite(self.cid, self.members[0],
AttributeError: 'Session' object has no attribute 'filetransfer_invite'

**Comment by zipatei** [comment]
@c10ud  This is not fixed.

**Comment by c10ud** [comment]
please reopen, seems like we need to check for the current service...

2012/3/6 zipatei
reply@reply.github.com:
