### ISSUE TITLE
[ERROR] start emesene-2 and traceback

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1050]
I just upgraded to version git emesene2 but just the start I get this traceback error:

``` python
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene.e3.common.DBus"
Errors occurred while importing jabber backend: No module named xmpp
Traceback (most recent call last):
  File "/usr/bin/emesene-2", line 34, in <module>
    emesene.main()
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 831, in main
    main_method(Controller)
  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/__init__.py", line 86, in gtk_main
    controller = Controller()
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 148, in __init__
    self._parse_commandline()
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 221, in _parse_commandline
    self.single_instance = SingleInstance.SingleInstance()
  File "/usr/lib/python2.7/site-packages/emesene/SingleInstance.py", line 50, in __init__
    except dbus.DBusException, error:
UnboundLocalError: local variable 'dbus' referenced before assignment
```

**Comment by marianoguerra** [comment]
this should help (didn't tested it)

```
    diff --git a/emesene/SingleInstance.py b/emesene/SingleInstance.py     
    index 097cb91..7da6f67 100644                                          
    --- a/emesene/SingleInstance.py                                        
    +++ b/emesene/SingleInstance.py                                        
    @@ -35,21 +35,27 @@ class SingleInstance:                              
             if os.name == 'posix':                                        
                 try:                                                      
                     import dbus, dbus.service                             
    -                dbus_version = getattr(dbus, 'version', (0, 0, 0))    
    -                if dbus_version >= (0, 41, 0):                        
    -                    import dbus.glib                                  
    -                if dbus_version >= (0, 80, 0):                        
    -                    from dbus.mainloop.glib import DBusGMainLoop      
    -                    DBusGMainLoop(set_as_default=True)                
    -                    self.new_dbus = True                              
    -                else:                                                 
    -                    import dbus.mainloop.glib                         
    -                    self.new_dbus = False                             
    -                self.have_dbus = True                                 
    -                self.dbus = dbus                                      
    -            except dbus.DBusException, error:                         
                     self.have_dbus = False                                
    -                print 'Unable to use D-Bus: %s' % str(error)          
    +            except ImportError:                                       
    +                self.have_dbus = False                                
    +                                                                      
    +            if self.have_dbus:                                        
    +                try:                                                  
    +                    dbus_version = getattr(dbus, 'version', (0, 0, 0))
    +                    if dbus_version >= (0, 41, 0):                    
    +                        import dbus.glib                              
    +                    if dbus_version >= (0, 80, 0):                    
    +                        from dbus.mainloop.glib import DBusGMainLoop  
    +                        DBusGMainLoop(set_as_default=True)            
    +                        self.new_dbus = True                          
    +                    else:                                             
    +                        import dbus.mainloop.glib                     
    +                        self.new_dbus = False                         
    +                    self.have_dbus = True                             
    +                    self.dbus = dbus                                  
    +                except dbus.DBusException, error:                     
    +                    self.have_dbus = False                            
    +                    print 'Unable to use D-Bus: %s' % str(error)      

             self.lock_file_name = os.path.normpath(tempfile.gettempdir() +
                                 '/emesene-' + getpass.getuser() + '.lock')
```
