### ISSUE TITLE
i send message offline (me online - other offline)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1053]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 230, in _response_handler
    handler(callback, errback, response, user_data)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/rsi.py", line 63, in _HandleGetMessageResponse
    run(callback, run_id, seq_num, m.get_payload().decode('base64'))
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/scenario/fetch_messages.py", line 46, in __get_message_callback
    run(self._callback, id, run_id, seq_num, message)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 355, in __fetch_message_cb
    message = self._messages.search_by_id(id)[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 230, in _response_handler
    handler(callback, errback, response, user_data)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/rsi.py", line 63, in _HandleGetMessageResponse
    run(callback, run_id, seq_num, m.get_payload().decode('base64'))
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/scenario/fetch_messages.py", line 46, in __get_message_callback
    run(self._callback, id, run_id, seq_num, message)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/OfflineIM/offline_messages_box.py", line 355, in __fetch_message_cb
    message = self._messages.search_by_id(id)[0]
IndexError: list index out of range
[02:06:23 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
[02:06:23 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[02:06:23 ERROR papylib.Events] Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder
[02:06:23 WARNING papyon.gnet.HTTP] Received response but wasn't waiting for one
[02:06:23 WARNING papyon.gnet.HTTP] <<< HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Date: Sat, 03 Mar 2012 02:06:25 GMT
Server: Microsoft-IIS/6.0
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
X-Powered-By: ASP.NET
X-AspNet-Version: 4.0.30319
X-WindowsLive-Hydra: H: BLU161-ds3 V: 16.2.5023.120 D: 2012-01-20T23:28:09
X-TransactionID: ceb0f667-3e20-403b-b195-decc1ec4c4b6
X-Response-Time: 421.8642
Content-Length: 540
Cache-Control: private
Content-Type: text/xml; charset=utf-8

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:NotAllowed</faultcode><faultstring xml:lang="en-US">The message was not found in the OIM folder</faultstring><detail><OimReceiveExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/Microsoft.Live.Protocols.OimReceive" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Description>Message with ID: 'e2121aea-e6db-4b03-b089-b3e00e68d68f' does not exist</Description></OimReceiveExceptionDetail></detail>/s:Fault/s:Body/s:Envelope
[02:07:00 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
[02:07:00 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[02:07:00 ERROR papylib.Events] Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder

**Comment by c10ud** [comment]
apparently it tried to fetch a message that it was already deleted (?)

**Comment by zipatei** [comment]
I have no idea ... :s

**Comment by zipatei** [comment]
[21:26:01 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from rsi.hotmail.com:443
[21:26:01 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[21:26:01 ERROR papylib.Events] Client got an error handling offline messages: 6 Offline Message Error (s:NotAllowed): The message was not found in the OIM folder

The same error. (Me offline. other online)

**Comment by zipatei** [comment]
when I'm talking and another person is offline and online, I get everything.

Then turn off the Emesene.

Again I turn on emesene, and get everything the other person said again.

**Comment by c10ud** [comment]
given all the reports you're posting seems like there's an issue with your network because i see lots of server errors which shouldn't be there (they happen once a while, but in your case they're present in every service call (!))

**Comment by zipatei** [comment]
But my network (cable 12Mb) is working fine ...

Alias when I was in emesene was working properly.

Now I am online in messenger and hotmail is working fine.

**Comment by zipatei** [comment]
This only happens when I'm offline.

When I am online, these errors do not exist.

**Comment by c10ud** [comment]
the errors seem related to https, also it could be the server is
stopping you from making too many requests but in that case i don't
understand the "notAllowed" error... not that i know all server errors
but...

2012/3/7 zipatei
reply@reply.github.com:
