### ISSUE TITLE
strange errors at login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1066]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 531, in event
    self._dispatch(method_name, *args[:-1])
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/andre/emesene/emesene/e3/papylib/PapyEvents.py", line 253, in on_oim_messages_fetched
    self._client._on_conversation_oim_received(message)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 479, in _on_conversation_oim_received
    self._handle_action_new_conversation(account, cid)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1275, in _handle_action_new_conversation
    conv = papyon.Conversation(self, [contact,])
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/conversation.py", line 58, in Conversation
    if contact.network_id == NetworkID.MSN])
AttributeError: 'NoneType' object has no attribute 'network_id'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 861, in run
    quit = self._process(data)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 882, in _process
    cid=cid)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 602, in add_event
    (id_src_info, id_src_acc) = self.insert_info(src.account, src.id,
AttributeError: 'Contact' object has no attribute 'id'

[21:28:45 WARNING papyon.service] Transport Error : Connection to omega.contacts.msn.com:443 (SSL TCP) failed: 
[21:28:45 ERROR papylib.Events] Client got an error handling addressbook: 4 Connection to omega.contacts.msn.com:443 (SSL TCP) failed: 
[21:28:46 WARNING papyon.service] Transport Error : Connection to local-bay.contacts.msn.com:443 (SSL TCP) failed: 
[21:28:46 ERROR papylib.Events] Client got an error handling addressbook: 4 Connection to local-bay.contacts.msn.com:443 (SSL TCP) failed:

**Comment by zipatei** [comment]
[21:45:07 ERROR papylib.Events] contact freddiezixxa@hotmail.com not found on address book

**Comment by c10ud** [comment]
i think the real error here is that you couldn't connect and get your address book, but there's sort of unhandled fault here

**Comment by zipatei** [comment]
I cann't connect emesene. I don't know what is happening.

**Comment by zipatei** [comment]
these errors appear below two errors if we are we talking about the live profile.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 861, in run
    quit = self._process(data)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 882, in _process
    cid=cid)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 602, in add_event
    (id_src_info, id_src_acc) = self.insert_info(src.account, src.id,
AttributeError: 'Contact' object has no attribute 'id'

[22:55:47 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'nick'
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 93, in _on_conv_message
    contact.nick), account, icid=icid)
AttributeError: 'NoneType' object has no attribute 'nick'

**Comment by zipatei** [comment]
Another strange thing,

Reproduced:
1) Open Messenger in profile.live.com
2) Open COnversation and talk
3) Open Emesene

We get what the contact says and we also send

**Comment by c10ud** [comment]
i think that's normal (?) because it's done automagically by MSNP18

2012/3/8 zipatei
reply@reply.github.com:

**Comment by zipatei** [comment]
But this does not happen in empathy.

**Comment by c10ud** [comment]
probably because they disable mpop (somehow)

2012/3/19 zipatei
reply@reply.github.com:

**Comment by c10ud** [comment]
i see now ssl errors which we should have fixed.... could this has been fixed by 2.12.3?

**Comment by zipatei** [comment]
@c10ud I think yes... I never had these errors.

The @pepeleproso will close this topic with the commit for WebMessenger.

**Comment by pepeleproso** [comment]
my commit should solve only this

Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
self.run()
File "/home/andre/emesene/emesene/e3/base/Logger.py", line 861, in run
quit = self._process(data)
File "/home/andre/emesene/emesene/e3/base/Logger.py", line 882, in _process
cid=cid)
File "/home/andre/emesene/emesene/e3/base/Logger.py", line 602, in add_event
(id_src_info, id_src_acc) = self.insert_info(src.account, src.id,
AttributeError: 'Contact' object has no attribute 'id'

**Comment by c10ud** [comment]
@zipatei can you try again now in order to see if all issues are gone?

**Comment by zipatei** [comment]
First error:

Running global cleanup code from study base classes.
[15:15:36 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'nick'
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 93, in _on_conv_message
    contact.nick), account, icid=icid)
AttributeError: 'NoneType' object has no attribute 'nick'

**Comment by zipatei** [comment]
Forget this: (Second, as Empathy, we should not receive what I write/send via webmessenger.)

But, One suggestion for these situations, would do something that happens in the genus WebMessenger: 

POPUP in conversation: "You are now signed in to 2 places. Messages will appear at all of these places.  Sign out of other places"

**Comment by c10ud** [comment]
papyon cannot detect multiple points of presence afaik, so id go for: if contact is None: contact = me

i don't think empathy "solution" is nice, i'd show the user the messages he's sending from eventual other places instead of silently discarding them.

**Comment by pepeleproso** [comment]
@zipatei try again please.

**Comment by zipatei** [comment]
Ya.. its fixed, but another error.. =))

[21:00:18 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'picture'
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 97, in _on_conv_message
    contact.nick), account, icid=icid)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 140, in _create_indicator
    pixbuf = utils.safe_gtk_pixbuf_load(contact.picture or '', (48, 48))
AttributeError: 'NoneType' object has no attribute 'picture'

**Comment by pepeleproso** [comment]
@zipatei  another path, hopefully the last one.

**Comment by zipatei** [comment]
ya,,, fixed.. =))

**Comment by zipatei** [comment]
Close this issue... errors fixed...
