### ISSUE TITLE
music plugin

### ISSUE THREAD

**Issue by DragaO** [emesene/emesene#107]
when i execute the music plugin and click on "preferences", the window doesn't do anything. just stay here over all windows and doesn't close on any button i click

**Comment by EibrielInv** [comment]
Confirmed.

If I Execute Music plugin, and open the Plugin Preferences, a "None preferences windows" shows, with a texbox, checkbox, some labels a button, al ok, but I cannot interact with. The interface is like an image, no "over" on buttons, don't change on click, I can't select the text on the textbox, nothing.
Clicking the Cross don't close that window, I must close first the Preferences windows, and then, close the "None preferences windows"

If I change the "listening to" extension a "Rhythmbox" the plugin works perfectly :)

If I open now the preference of the plugin an empty window titled "Rhythmbox preferences" appear.

If I stop the plugin, and activate again, the Rhythmbox music title shows, But the extension "listening to" is in None!!

If I change "listening to" to "Rythmbox", and try open plugin preferences nothing happens.

If I change "listening to" to "None", and try open plugin preferences nothing happens.

Regards!!

**Comment by marianoguerra** [comment]
make preference extension single instance, remove modal attribute closed by 17bf230aa066e850b68b5ad2fb256a6a81964f9d

**Comment by c10ud** [comment]
http://bit.ly/8YSUZr

**Comment by EibrielInv** [comment]
Still not solved....

```
[17:13:18 INFO pluginmanager] starting plugin "music"
[17:13:18 INFO extension] extension id None not registered on option provider
    Traceback (most recent call last):
  File "plugins/music/songretriever.py", line 94, in check_song
    self.set_cover_as_avatar(song)
  File "plugins/music/songretriever.py", line 105, in set_cover_as_avatar
    self.avatar_manager.set_as_avatar(image_path)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/gui/base/AvatarManager.py", line 126, in set_as_avatar
    fpath = self.add_new_avatar(filename)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/gui/base/AvatarManager.py", line 89, in add_new_avatar
    pix_96.resize(96)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/gui/base/PictureHandler.py", line 40, in resize
    raise NotImplementedError("Method not implemented")
NotImplementedError: Method not implemented
[17:13:26 DEBUG papyon.transport] >>> PNG
[17:13:27 DEBUG papyon.transport] <<< QNG 39
[17:13:37 INFO pluginmanager] configuring plugin "music"
[17:13:37 INFO extension] extension id None not registered on option provider
```

Still have same behaviour as before, with the freezed configuration window...
