### ISSUE TITLE
import from emesene1 stalls

### ISSUE THREAD

**Issue by glensc** [emesene/emesene#1074]
21:00:05  glen> when that "synchronization finishes" should i realy press "cancel" button? as the box does not dissapear
21:00:10  glen> very confusing
21:02:26  glen> oh fun. the cancel button doesn't do anything either
21:02:53  glen> but closing the dialog with corner x made it dissapear
21:03:04  glen> using emesene-2.12.1
21:04:43  glen> http://dl.dropbox.com/u/8879577/ss/emesene2-sync.png

sorry no output messages this time, i'll try to reproduce

**Comment by glensc** [comment]
i retried the sequence, removed .config/emesene2 and invoked again. nothing interesting in output, seems just messages that came from msn server communication, nothing that seems related to the import

$ emesene 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"
[22:05:27 WARNING papyon.p2p] Trying to publish an empty MSNObject
[22:05:27 WARNING e3.common.Config] couldn't load config: /home/users/glen/.config/emesene2/messenger.hotmail.com/glen@alkohol.ee/config (no file)
[22:05:28 WARNING papyon.p2p] Trying to publish an empty MSNObject
/usr/share/emesene/gui/gtkui/**init**.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
[22:05:40 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:05:44 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:05:45 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:05:47 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:05:54 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:05:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:01 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:05 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:06 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 c6 a7 30 6e 00 00 00 00 00 00 00 00
b4 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
54 98 1c 3f 78 e5 f6 02 b4 02 00 00 00 00 00 00
[22:06:06 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
e9 aa 72 6a c5 a7 30 6e 00 00 00 00 00 00 00 00
88 5f 00 00 00 00 00 00 00 00 00 00 20 00 00 00
0b e7 ea 20 00 00 00 00 00 00 00 00 00 00 00 00
[22:06:07 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 ca a7 30 6e 00 00 00 00 00 00 00 00
b3 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
b6 50 8a 46 79 e5 f6 02 b3 02 00 00 00 00 00 00
[22:06:08 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
af e4 9f 26 c9 a7 30 6e 00 00 00 00 00 00 00 00
88 5f 00 00 00 00 00 00 00 00 00 00 20 00 00 00
e5 a5 15 1c 00 00 00 00 00 00 00 00 00 00 00 00
[22:06:14 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:15 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: chunk end exceeds blob size
e9 aa 72 6a c5 a7 30 6e e8 5d 00 00 00 00 00 00
88 5f 00 00 00 00 00 00 b2 04 00 00 20 00 00 00
0b e7 ea 20 00 00 00 00 00 00 00 00 00 00 00 00
[22:06:15 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: chunk end exceeds blob size
af e4 9f 26 c9 a7 30 6e e8 5d 00 00 00 00 00 00
88 5f 00 00 00 00 00 00 b2 04 00 00 20 00 00 00
e5 a5 15 1c 00 00 00 00 00 00 00 00 00 00 00 00
[22:06:15 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:22 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:24 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:35 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:35 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:43 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:45 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:45 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:46 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:51 ERROR e3.common.Signal] Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: GDBus.Error:org.freedesktop.Notifications.MaxNotificationsExceeded: Exceeded maximum number of notifications
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/emesene/e3/common/Signal.py", line 65, in emit
  File "/usr/share/python2.7/site-packages/emesene/e3/common/Signal.py", line 112, in __call__
  File "/usr/share/python2.7/site-packages/emesene/e3/common/notification.py", line 186, in _on_contact_attr_changed
  File "/usr/share/python2.7/site-packages/emesene/e3/common/notification.py", line 177, in _do_notify_online
  File "/usr/share/python2.7/site-packages/emesene/e3/common/notification.py", line 217, in _notify
  File "/usr/share/python2.7/site-packages/emesene/gui/common/PyNotification.py", line 47, in PyNotification
Error: GDBus.Error:org.freedesktop.Notifications.MaxNotificationsExceeded: Exceeded maximum number of notifications
[22:06:51 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:53 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:53 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:55 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 97 d5 06 00 00 00 00 00 00 00 00 00
db 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
c3 f7 3d 25 62 db eb 4f db 02 00 00 00 00 00 00
[22:06:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:56 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 b7 2e 01 00 00 00 00 00 00 00 00 00
dc 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
06 c7 4c 71 63 db eb 4f dc 02 00 00 00 00 00 00
[22:06:56 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:06:56 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 95 d5 06 00 00 00 00 00 00 00 00 00
72 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
a4 0d 2a 36 64 db eb 4f 72 01 00 00 00 00 00 00
[22:06:56 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 b5 2e 01 00 00 00 00 00 00 00 00 00
73 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
1e ca 05 0b 65 db eb 4f 73 01 00 00 00 00 00 00
[22:06:59 ERROR papyon.protocol.notification] Notification got error : 800 29
[22:07:09 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:09 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:09 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:21 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:23 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:23 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:24 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:25 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:25 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:25 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[22:07:26 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

**Comment by c10ud** [comment]
i found the import failing once, but since i had a dirty db because i was using emesene1 since ages i just rm'd the old db :)
