### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1089]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/MainMenu.py", line 177, in <lambda>
    lambda _args: self.handler.on_preferences_selected())
  File "/home/andre/emesene/emesene/gui/base/Handler.py", line 155, in on_preferences_selected
    instance = extension.get_and_instantiate('preferences', self.session)
  File "/home/andre/emesene/emesene/extension.py", line 453, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/home/andre/emesene/emesene/extension.py", line 290, in get_and_instantiate
    inst = cls(_args, **kwargs)
  File "/home/andre/emesene/emesene/gui/gtkui/Preferences.py", line 109, in **init**
    self.conversation = ConversationWindow(session)
  File "/home/andre/emesene/emesene/gui/gtkui/Preferences.py", line 659, in **init**
    'session.config.b_close_button_on_tabs')
  File "/home/andre/emesene/emesene/gui/gtkui/Preferences.py", line 369, in append_check
    widget = self.create_check(text, property_name)
  File "/home/andre/emesene/emesene/gui/gtkui/Preferences.py", line 361, in create_check
    widget.set_active(default)
TypeError: an integer is required

Open preferences

**Comment by arielj** [comment]
check now, this should be fixed

**Comment by c10ud** [comment]
tried and no error

**Comment by zipatei** [comment]
fixed
