### ISSUE TITLE
TypeError: QWidget.showMaximized(): first argument of unbound method must have type 'QWidget'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1090]
Traceback (most recent call last):
  File "/usr/bin/emesene", line 34, in <module>
    emesene.main()
  File "/usr/share/emesene/emesene/emesene.py", line 830, in main
    main_method(Controller)
  File "/usr/share/emesene/emesene/gui/qt4ui/**init**.py", line 42, in qt4_main
    controller.start()
  File "/usr/share/emesene/emesene/emesene.py", line 236, in start
    self._set_location(self.window)
  File "/usr/share/emesene/emesene/emesene.py", line 527, in _set_location
    window.maximize()
  File "/usr/share/emesene/emesene/gui/qt4ui/TopLevelWindow.py", line 143, in maximize
    QtGui.QMainWindow.showMaximized()
TypeError: QWidget.showMaximized(): first argument of unbound method must have type 'QWidget'

Press this command: emesene -e main:qt4_main

**Comment by c10ud** [comment]
qt4 backend is unsupported, don't use it unless you know what you're doing/ready to fix it
