### ISSUE TITLE
AttributeError: 'module' object has no attribute 'profile'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1092]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/emesene", line 30, in <module>
    from emesene import emesene
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 104, in <module>
    from e3 import papylib
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/**init**.py", line 21, in <module>
    from Session import Session
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Session.py", line 22, in <module>
    from Worker import Worker
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 65, in <module>
    from PapyEvents import *
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/PapyEvents.py", line 23, in <module>
    import papyon.event
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
    from client import *
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
    import papyon.profile as profile
AttributeError: 'module' object has no attribute 'profile'

**Comment by zipatei** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=804278

**Comment by c10ud** [comment]
emesene-2.11.11 again, please don't import the entire rhel bugtracker
