### ISSUE TITLE
emesene wont launch

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1097]
Getting this error:

```
Traceback (most recent call last):
  File "emesene.py", line 79, in <module>
    languages=[lang])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 465, in translation
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 437, in find
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 132, in _expand_lang
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 351, in normalize
AttributeError: 'NoneType' object has no attribute 'lower'
```

Latest git rev, OS X 10.7.3

**Comment by arielj** [comment]
are you sure you are using latest git? line 79 of emesene.py is not the one on your traceback https://github.com/emesene/emesene/blob/master/emesene/emesene.py

anyway, i've sent a little fix, try latest git

**Comment by joshf** [comment]
Yeah fixed now, i think the script i use to bundle emesene failed, so i thought i was at a later rev than i was
