### ISSUE TITLE
Papyon error

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1100]
[22:00:44 ERROR papyon.msnp2p.session_manager] 'UUID' object has no attribute 'upper'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session_manager.py", line 152, in _on_slp_message_received
    session = handler._handle_message(peer, guid, message)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/p2p.py", line 311, in _handle_message
    session.accept(obj._data)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/msnobject.py", line 56, in accept
    self._accept()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 197, in _accept
    self._respond(200)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 194, in _respond
    self._close_end_points(status_code)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 250, in _close_end_points
    self._close_end_point(end_point, status)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 255, in _close_end_point
    s_channel_state=0)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/SLP.py", line 408, in __init__
    self.add_header("AcceptedBy", "{%s}" % reason[1].upper())
AttributeError: 'UUID' object has no attribute 'upper'
[22:00:44 ERROR papyon.msnp2p.session_manager] Could not handle SLP invite message

**Comment by c10ud** [comment]
nice, i wonder why this happens after years of emesene+papyon.. anyway
there must be a nice method for converting an uuid to a string

2012/3/27 Sven reply@reply.github.com:
