### ISSUE TITLE
Language module bugs

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1128]
When opening preferences:

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/MainMenu.py", line 178, in <lambda>
    lambda *args: self.handler.on_preferences_selected())
  File "/home/sven/emesene/emesene/gui/base/Handler.py", line 155, in on_preferences_selected
    instance = extension.get_and_instantiate('preferences', self.session)
  File "/home/sven/emesene/emesene/extension.py", line 453, in get_and_instantiate
    return category.get_and_instantiate(*args, **kwargs)
  File "/home/sven/emesene/emesene/extension.py", line 290, in get_and_instantiate
    inst = cls(*args, **kwargs)
  File "/home/sven/emesene/emesene/gui/gtkui/Preferences.py", line 113, in __init__
    self.desktop = DesktopTab(session)
  File "/home/sven/emesene/emesene/gui/gtkui/Preferences.py", line 1142, in __init__
    self.languages_cb.set_active(default)
TypeError: an integer is required
```

**Comment by jamesaxl** [comment]
Emesene doesn't start:

```
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "emesene/emesene", line 34, in <module>
    emesene.main()
  File "/home/wise/Downloads/emesene_git/emesene/emesene/emesene.py", line 852, in main
    main_method(Controller)
  File "/home/wise/Downloads/emesene_git/emesene/emesene/gui/gtkui/__init__.py", line 86, in gtk_main
    controller = Controller()
  File "/home/wise/Downloads/emesene_git/emesene/emesene/emesene.py", line 148, in __init__
    self.config.language_config)
  File "/home/wise/Downloads/emesene_git/emesene/emesene/Language.py", line 93, in install_desired_translation
    self._lang = self._lang.split("_")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Sbte** [comment]
@arielj:

A few things:

Please use the current language by default in the preferences. Not the current config value. And please don't solve this by using get_or_set on the config value, because then users can't benefit from automatic adaption after changing the system language.

Please use index if you want to find something, don't loop over the whole thing.

Also try to use a decent combo box that only depends on the keys (so not a default text combo box). That way you don't need the DICT_R.

If you do all this at least my bug will be solved ;)

**Comment by arielj** [comment]
"Please use the current language by default in the preferences. Not the current config value. And please don't solve this by using get_or_set on the config value, because then users can't benefit from automatic adaption after changing the system language."

why not the config value? Preferences should show what's on the config file, it would be confusing other way.

'Please use index if you want to find something, don't loop over the whole thing.'

i don't understand this, I'm not looping to find something, I'm looping to populate the combobox and find the index :P.

'Also try to use a decent combo box that only depends on the keys (so not a default text combo box). That way you don't need the DICT_R.'

I'm using what's used everywhere else :P, we are always using text combo boxes. What do you suggest?

**Comment by Sbte** [comment]
<i>why not the config value? Preferences should show what's on the config file, it would be confusing other way.</i>

Because if the config value is not set, it should use the system default. Only if the value changes, the config value should be set. That way people who prefer the default system locale would still have the default system locale in emesene after they change the default system locale, i.e. if they change en->es on their system they would have es in emesene too. 

<i>i don't understand this, I'm not looping to find something, I'm looping to populate the combobox and find the index :P.</i>

Lists have an index method. You should loop to populate the combobox, but not to find an index.

<i>I'm using what's used everywhere else :P, we are always using text combo boxes. What do you suggest?</i>

A combobox using a liststore that specifies both key an value (of the language dict).

**Comment by arielj** [comment]
"Because if the config value is not set, it should use the system default. Only if the value changes, the config value should be set. That way people who prefer the default system locale would still have the default system locale in emesene after they change the default system locale, i.e. if they change en->es on their system they would have es in emesene too."

Ok, I'll change that.

"Lists have an index method. You should loop to populate the combobox, but not to find an index."
But I have a dict, not a list.

"A combobox using a liststore that specifies both key an value (of the language dict)."

Ok, I'll try that later, I'll change that big dict to a liststore, so I can have an index and use that model for the combo.

**Comment by Sbte** [comment]
About you having a dict: you iterate over the list of keys.

Anyhow, I can do the last two things if I have time. As long as it works right? :P

**Comment by arielj** [comment]
Go with that if you want to, I gotta go now so I don't have too much time.

**Comment by monksy** [comment]
I'm seeing this issue with 2.12.3 when trying to open the preference's dialog box. [This is on a clean install on Ubuntu linux 12.04.]

Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/MainMenu.py", line 178, in <lambda>
    lambda _args: self.handler.on_preferences_selected())
  File "/usr/share/emesene/emesene/gui/base/Handler.py", line 155, in on_preferences_selected
    instance = extension.get_and_instantiate('preferences', self.session)
  File "/usr/share/emesene/emesene/extension.py", line 453, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 290, in get_and_instantiate
    inst = cls(_args, **kwargs)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 142, in **init**
    self.**init_list()
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 223, in __init_list
    self.facebook = Facebook(self.session)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 1206, in __init**
    'session.config.b_fb_enable_integration')
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 373, in append_check
    widget = self.create_check(text, property_name)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 365, in create_check
    widget.set_active(default)
TypeError: an integer is required
