### ISSUE TITLE
[TRACEBACK] not start emesene2 (git-version)

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1130]
``` python
Traceback (most recent call last):
  File "/usr/bin/emesene-2", line 30, in <module>
    from emesene import emesene
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 62, in <module>
    language_management.install_default_translation()
  File "/usr/lib/python2.7/site-packages/emesene/Language.py", line 110, in install_default_translation
    self.install_desired_translation(language)
  File "/usr/lib/python2.7/site-packages/emesene/Language.py", line 100, in install_desired_translation
    fallback=True)
  File "/usr/lib/python2.7/gettext.py", line 465, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/usr/lib/python2.7/gettext.py", line 437, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python2.7/gettext.py", line 132, in _expand_lang
    locale = normalize(locale)
  File "/usr/lib/python2.7/locale.py", line 358, in normalize
    fullname = localename.encode('ascii').translate(_ascii_lower_map)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by arielj** [comment]
Do you really have latest git? it should be fixed here https://github.com/emesene/emesene/commit/87587f4824f9da4a6871b552b50b6ef977861907
