### ISSUE TITLE
Latest git won't run anymore

### ISSUE THREAD

**Issue by hit** [emesene/emesene#1133]
g@g:~/Apps/emesene/emesene$ ./emesene -vvv
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/home/g/Apps/emesene/emesene/emesene.py", line 852, in main
    main_method(Controller)
  File "/home/g/Apps/emesene/emesene/gui/gtkui/**init**.py", line 86, in gtk_main
    controller = Controller()
  File "/home/g/Apps/emesene/emesene/emesene.py", line 148, in **init**
    self.config.language_config)
  File "/home/g/Apps/emesene/emesene/Language.py", line 130, in install_desired_translation
    self._lang = self._lang.split("_")[0]
AttributeError: 'list' object has no attribute 'split'

**Comment by arielj** [comment]
please test if it's fixed now

**Comment by hit** [comment]
Seems fixed now.
