### ISSUE TITLE
Facebook error

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1134]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 102, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 182, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 392, in _handle_action_set_message
    self.session.facebook_client.message = message
  File "/home/andre/emesene/emesene/e3/jabber/facebook.py", line 93, in _set_personal_message
    self._client.publish(message, "me")
  File "/home/andre/emesene/emesene/e3/jabber/pyfb/pyfb/pyfb.py", line 125, in publish
    self._client.push(id, "feed", message=message)
  File "/home/andre/emesene/emesene/e3/jabber/pyfb/pyfb/client.py", line 188, in push
    self._make_auth_request(path, **data)
  File "/home/andre/emesene/emesene/e3/jabber/pyfb/pyfb/client.py", line 69, in _make_auth_request
    return urllib.urlopen(url, post_data).read()
  File "/usr/lib/python2.7/urllib.py", line 88, in urlopen
    return opener.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 209, in open
    return getattr(self, name)(url, data)
  File "/usr/lib/python2.7/urllib.py", line 436, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1161, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init**
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 104] Ligação terminada no destino

**Comment by zipatei** [comment]
I think this occured when i changed the PM

**Comment by lfottaviano** [comment]
I was going to see this bug, but sincerely I can't reproduce it.  @zipatei  plz when you report an issue please put us in context, I have to guess If you where using gtkui, qt4ui, what you have done, etc.
thanks for all :)
