### ISSUE TITLE
[TRACEBACK] emesene not start-up GTK error

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1137]
Run emesene-2 on Gentoo LiveCD 12.1 with KDE v4.8.1

emesene git last version

``` python
No protocol specified
No protocol specified
xprop:  unable to open display ':0'
No protocol specified
No protocol specified
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could $
  warnings.warn(str(e), _gtk.Warning)
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Errors occurred while importing jabber backend: No module named xmpp
Traceback (most recent call last):
  File "/usr/bin/emesene-2", line 34, in <module>
    emesene.main()
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 850, in main
    main_method(Controller)
  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/__init__.py", line 8$
    setup()
  File "/usr/lib/python2.7/site-packages/emesene/gui/gtkui/__init__.py", line 1$
    gtk.settings_get_default().set_property("gtk-error-bell", False)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by Sbte** [comment]
I think this tells you that you have a broken gtk installation. If there are no gtk settings present on your system, I doubt that it can even draw a window.

If other gtk applications run without problems, then you can consider reopening this bug.

**Comment by Sbte** [comment]
Relevant commit that added this line (for curious people): 287f86d6685bd63cbeb1adc5aca5d536b30cc5dd

**Comment by KinG-InFeT** [comment]
the live system works perfectly, only emesene does not work properly and GTK are installed properly.
