### ISSUE TITLE
I cannot log in

### ISSUE THREAD

**Issue by alejandrocobo** [emesene/emesene#1152]
I tryed emesene 2.12.1 and 2.12.3 (Qt edition under Linux 3.3) and I cannot log in. When I try to log in, the progress bar is always going and coming, then the tray icon becomes green while the progress bar continues going and comming  but nothing more happens.

 I obtain this messages from the console:

*\* (process:2775): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

*\* (process:2775): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

*\* (process:2775): WARNING *_: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
Gtk-Message: Failed to load module "canberra-gtk-module"
*_ Message: pygobject_register_sinkfunc is deprecated (GstObject)
Cannot import gtkui: cannot import name gtkui
Errors occurred while importing jabber backend: No module named xmpp
[17:27:53 WARNING e3.common.Config] couldn't load config: /home/a/.config/emesene2/messenger.hotmail.com/myaccount@hotmail.com/config (no file)
[17:27:53 ERROR e3.common.Signal] Method called on dead object: on_login_succeed.on_login_succeed
Traceback (most recent call last):
  File "/usr/share/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), _arg)
  File "/usr/share/emesene/emesene.py", line 602, in on_login_succeed
    self.draw_main_screen()
  File "/usr/share/emesene/emesene.py", line 514, in draw_main_screen
    self.tray_icon.quit_on_close)
TypeError: go_main() takes at least 5 arguments (4 given)
[17:27:53 ERROR e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'ConnectingPage' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/usr/share/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, **kwargs) == False:
  File "/usr/share/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene.py", line 698, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'ConnectingPage' object has no attribute 'contact_list'

Thanks.

**Comment by Sbte** [comment]
Could you try the latest development version? It's probably fixed there.

**Comment by c10ud** [comment]
also, use Qt frontend only if you are interested in fixing it :)

**Comment by alejandrocobo** [comment]
Yes, it seems to work ok now.

Thanks.
