### ISSUE TITLE
TypeError: Method called on dead object

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1164]
I dont know how to reproduce this

[14:56:46 ERROR e3.common.Signal] Method called on dead object: _on_contact_attr_changed._on_contact_attr_changed
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 110, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

**Comment by Sbte** [comment]
Could this have happened when you changed tray icons? Can you remember or reproduce by any chance?
