### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'has_similar_conversation'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1179]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 86, in _on_conv_message
    conv = conv_manager.has_similar_conversation(cid, [account])
AttributeError: 'NoneType' object has no attribute 'has_similar_conversation'

**Comment by zipatei** [comment]
Ubuntu 12.04 - Emesene last commit github - Gtkui

**Comment by c10ud** [comment]
#1180
