### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'has_similar_conversation'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1180]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 136, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 182, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1340, in _handle_action_send_message
    papyconversation = self.papyconv[cid]
KeyError: 1334785713.478266

Ubuntu 12.04 - Emesene last commit github - Gtkui

**Comment by zipatei** [comment]
[23:02:58 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 1334785713.478266
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 95, in _on_conv_message
    contact.nick), account, icid=icid)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 161, in _create_indicator
    ind = self.r_indicator_dict[old_icid]
KeyError: 1334785713.478266

**Comment by c10ud** [comment]
can you reproduce what you did with -vvv ?

**Comment by c10ud** [comment]
also, the messaging menu part needs to be simplified because is too prone to errors..
i'm mostly interested in the papylibs one

to devs: https://github.com/emesene/emesene/blob/master/emesene/e3/papylib/Worker.py#L1340

this shouldn't happen because "we" opened the conversation, so...

@zipatei: please if you remember what were you doing exactly this could help reproducing

**Comment by zipatei** [comment]
c10ud. nothing...but may have 2 things:

1) I think the error has relationed with #1179
2) I've just signed in and received a message from a contact. I clicked close and got another message just the same contact. And these two errors plus the #1179 appeared.

**Comment by c10ud** [comment]
yea i think #1179 is the same as this bug

**Comment by c10ud** [comment]
but you didn't _receive_, you actually _sent_ a message:

File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1340, in _handle_action_send_message

**Comment by c10ud** [comment]
the messaging menu errors are because you sent a message without a conversation, i am interested in how to reproduce it

**Comment by zipatei** [comment]
[18:40:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
 [18:40:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
 [18:41:49 WARNING papyon.p2p] Trying to publish an empty MSNObject
 [18:42:17 ERROR papyon.msnp2p.session_manager] Session_id == 0
 *\* Message: console message: undefined @0: TypeError: 'undefined' is not an object

[18:49:54 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
 [18:51:45 ERROR e3.common.Signal] Signal handler (on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'has_similar_conversation'
 Traceback (most recent call last):
 File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
 if callback(_args, *_kwargs) == False:
 File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call_
 self.f(self.c(), arg)
 File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 97, in _on_conv_message
 conv = conv_manager.has_similar_conversation(cid, [account])
 AttributeError: 'NoneType' object has no attribute 'has_similar_conversation'
- Message: console message: undefined @0: TypeError: 'undefined' is not an object

Reproduce:
1) Open conversation.
2) send message..
3) close conversation
4) receive message...

Single window

**Comment by c10ud** [comment]
this is a big issue, not related to single window afaik, leads to hard crashes, reproducible with dummy

**Comment by Sbte** [comment]
Ah, good this is reproducible in Dummy too after bfd6a1f6d80a2ecefff3fe44f0287cebb1f48cf5. Just send and close.

**Comment by Sbte** [comment]
It's reproducible in dummy because of a bug in the dummy session. It never sends conv_first_action, so conversations don't get opened when you receive a message.

**Comment by zipatei** [comment]
Reproducible in MSN here

**Comment by c10ud** [comment]
please test current git head 36d58fb9d1dc9637b1c998f85502c3a57cadd94e

**Comment by c10ud** [comment]
nvm, fix ain't working

**Comment by c10ud** [comment]
well since this was because of a bad fix for #1282 and i reverted everything, i think this no longer affects current git head (other bugs do)
