### ISSUE TITLE
[AvatarChooser] Select PDF file

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1181]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/ImageChooser.py", line 150, in _on_accept
    self.response_cb(gui.stock.ACCEPT, filename)
  File "/home/andre/emesene/emesene/gui/gtkui/AvatarChooser.py", line 220, in _on_image_selected
    animation = gtk.gdk.PixbufAnimation(path)
glib.GError: Incapaz de reconhecer o formato de imagem do ficheiro '/home/andre/declaracao.pdf'

**Comment by zipatei** [comment]
we have to create a list of supported extensions in order to get an error saying the file is not supported or remove "all files" option in ImageChooser

**Comment by lfottaviano** [comment]
I have found this, so I will do it.

**Comment by zipatei** [comment]
i know... hehehe
