### ISSUE TITLE
Errno socket error] [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1184]
[02:02:16 ERROR e3.common.Collections] [Errno socket error] [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Collections.py", line 181, in fetch_metadata
    rq = self.github.get_raw(self.theme, current_ext.files[path])
  File "/home/andre/emesene/emesene/e3/common/Github.py", line 42, in get_raw
    response = urlopen(API_GITHUB_GETRAW % (self._org, repo, sha))
  File "/usr/lib/python2.7/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 436, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1161, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

MSN Protocol...last commit... Ubuntu 12.04... I just login, and preferences, and refresh extensions.

**Comment by zipatei** [comment]
(02:01:31) pluginmanager:Imported plugins:
(02:01:31) pluginmanager:Imported plugins:
(02:01:33) pluginmanager:Imported plugins:
(02:01:33) pluginmanager:Imported plugins:
(02:01:52) pluginmanager:Imported plugins:
(02:01:52) pluginmanager:Imported plugins:
(02:01:57) pluginmanager:Imported plugins:
(02:01:57) pluginmanager:Imported plugins:
(02:02:00) pluginmanager:Imported plugins:
(02:02:00) pluginmanager:Imported plugins:
(02:02:01) papyon.transport:>>> PNG
(02:02:01) papyon.transport:<<< QNG 46
(02:02:02) pluginmanager:Imported plugins:
(02:02:02) pluginmanager:Imported plugins:
(02:02:08) pluginmanager:Imported plugins:
(02:02:08) pluginmanager:Imported plugins:
(02:02:12) pluginmanager:Imported plugins:
(02:02:12) pluginmanager:Imported plugins:
(02:02:12) pluginmanager:Imported plugins:
(02:02:12) pluginmanager:Imported plugins:
(02:02:16) e3.common.Collections:[Errno socket error] [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
(02:02:17) pluginmanager:Imported plugins:
(02:02:17) pluginmanager:Imported plugins:
(02:02:17) pluginmanager:Imported plugins:
(02:02:17) pluginmanager:Imported plugins:

**Comment by zipatei** [comment]
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371
