### ISSUE TITLE
[Windows 7] Error at init emesene

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1186]
Traceback (most recent call last):
  File "emesene.py", line 103, in <module>
  File "e3__init__.pyo", line 3, in <module>
    
  File "e3\common__init__.pyo", line 22, in <module>

  File "e3\common\notification.pyo", line 21, in <module>
    
  File "gui__init__.pyo", line 20, in <module>

  File "gui\base__init__.pyo", line 35, in <module>

  File "gui\base\Theme.pyo", line 35, in **init**

  File "e3\common\ConfigDir.pyo", line 33, in **init**

  File "e3\common\ConfigDir.pyo", line 71, in _get_default_base_dir

  File "os.pyo", line 423, in **getitem**

KeyError: 'APPDATA'

**Comment by lfottaviano** [comment]
so if in that windows you open a cmd and do,  cd %APPDATA% what you get?
