### ISSUE TITLE
'NoneType' object has no attribute 'Plugin'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1192]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/utils.py", line 260, in check
    self.callback(result)
  File "/home/andre/emesene/emesene/gui/gtkui/ExtensionList.py", line 291, in show_update_callback
    self.show_update()
  File "/home/andre/emesene/emesene/gui/gtkui/ExtensionList.py", line 667, in show_update
    description=pluginmanager.plugin_description(name))
  File "/home/andre/emesene/emesene/pluginmanager.py", line 259, in plugin_description
    return self._plugins[name].get_description()
  File "/home/andre/emesene/emesene/pluginmanager.py", line 161, in get_description
    description = self.module.Plugin.description
AttributeError: 'NoneType' object has no attribute 'Plugin'

I tranfer music plugin and error.

**Comment by Sbte** [comment]
The download wasn't complete or something?

**Comment by Sbte** [comment]
Also, did get an error importing that plugin? What happened?

**Comment by zipatei** [comment]
Maybe, click in refresh in preferences before transfer plugin finnished.

**Comment by Sbte** [comment]
Ok, so yeah, we should integrate the progress bar into the preferences window, and download into a temp dir, and move the downloaded stuff from there to the plugins/themes dirs

**Comment by c10ud** [comment]
this looks so #989
