### ISSUE TITLE
GTK3 bug in login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1212]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 698, in on_contact_list_ready
    self.on_pending_contacts()
  File "/home/andre/emesene/emesene/emesene.py", line 692, in on_pending_contacts
    dialog.contact_added_you(accounts, on_contact_added_you)
  File "/home/andre/emesene/emesene/gui/gtkui/Dialog.py", line 439, in contact_added_you
    dialog = AddBuddy(response_cb)
  File "/home/andre/emesene/emesene/gui/gtkui/Dialog.py", line 1650, in **init**
    self.pages = self._buildpages()
  File "/home/andre/emesene/emesene/gui/gtkui/Dialog.py", line 1693, in _buildpages
    arrowleft = TinyArrow(gtk.ARROW_LEFT)
  File "/home/andre/emesene/emesene/gui/gtkui/Dialog.py", line 1798, in __init__
    self.connect("expose_event", self.expose)
TypeError: <TinyArrow object at 0xa9e639c (gui+gtkui+Dialog+TinyArrow at 0x96446f0)>: unknown signal name: expose_event

**Comment by c10ud** [comment]
check git head
