### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1215]
andre@Portatil:~/emesene/emesene$ ./emesene
No module named direct
Traceback (most recent call last):
  File "./emesene", line 30, in <module>
    from emesene import emesene
  File "/home/andre/emesene/emesene/emesene.py", line 113, in <module>
    from e3 import papylib
  File "/home/andre/emesene/emesene/e3/papylib/**init**.py", line 21, in <module>
    from Session import Session
  File "/home/andre/emesene/emesene/e3/papylib/Session.py", line 22, in <module>
    from Worker import Worker
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 65, in <module>
    from PapyEvents import *
  File "/home/andre/emesene/emesene/e3/papylib/PapyEvents.py", line 23, in <module>
    import papyon.event
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
    from client import *
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
    import papyon.profile as profile
AttributeError: 'module' object has no attribute 'profile'

**Comment by c10ud** [comment]
please pull again, it works locally

**Comment by c10ud** [comment]
if it doesn't work please tell me which was the latest working rev

**Comment by c10ud** [comment]
No module named direct -- interesting

**Comment by zipatei** [comment]
9d14de61ac057482697a78c61c8e686b958cebeb this commit works

**Comment by c10ud** [comment]
it's missing direct.py, and that sucks because i cannot find it in my local directory -- it's working locally because i still had the .pyc

did anyone clone my direct connect branch and save it?
