### ISSUE TITLE
[TRACEBACK] (git-version)

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1219]
``` python
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (864 bytes)]
[19:21:22 DEBUG papyon.transport] <<< ACK 3
[19:21:25 WARNING papyon.msnp2p.transport.direct] Error mapping port 6891 (timeout)
[19:21:25 DEBUG papyon.msnp2p.session] Bridge listening 151.70.121.143 6891
Errors occurred while importing jabber backend: No module named xmpp
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>])
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">])
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">])
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">])
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="Kry-passion@hotmail.it" guid="682ca9d3-92e1-4b6c-b074-28a6918b1c4a">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">, <SwitchboardP2PTransport peer="planamente94@hotmail.it" guid="2c007718-d12b-456a-bc3a-20e791f90e33">, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="m@nuel.it" guid="None">])
Best transport is now: <SwitchboardP2PTransport peer="m@nuel.it" guid="None">
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="Kry-passion@hotmail.it" guid="682ca9d3-92e1-4b6c-b074-28a6918b1c4a">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">, <SwitchboardP2PTransport peer="planamente94@hotmail.it" guid="2c007718-d12b-456a-bc3a-20e791f90e33">, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="m@nuel.it" guid="None">])
Best transport is now: <SwitchboardP2PTransport peer="m@nuel.it" guid="None">
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="Kry-passion@hotmail.it" guid="682ca9d3-92e1-4b6c-b074-28a6918b1c4a">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">, <SwitchboardP2PTransport peer="planamente94@hotmail.it" guid="2c007718-d12b-456a-bc3a-20e791f90e33">, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="m@nuel.it" guid="None">])
Best transport is now: <SwitchboardP2PTransport peer="m@nuel.it" guid="None">
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="Kry-passion@hotmail.it" guid="682ca9d3-92e1-4b6c-b074-28a6918b1c4a">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">, <SwitchboardP2PTransport peer="planamente94@hotmail.it" guid="2c007718-d12b-456a-bc3a-20e791f90e33">, <DirectP2PTransport object at 0xacb6874 (papyon+msnp2p+transport+direct+DirectP2PTransport at 0xb7d9aa0)>, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <DirectP2PTransport object at 0xacb661c (papyon+msnp2p+transport+direct+DirectP2PTransport at 0xb2c269d0)>, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="m@nuel.it" guid="None">])
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 318, in _bridge_listening
    external_ip, external_port)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 225, in _accept_transreq
    self._respond_transreq(transreq, 200, body)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 218, in _respond_transreq
    self._send_slp_message(response)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 383, in _send_slp_message
    self._application_id, message)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 83, in send_slp_message
    self.send_data(peer, peer_guid, application_id, 0, str(message))
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 87, in send_data
    transport = self._get_transport(peer, peer_guid, blob)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 171, in _get_transport
    best = self.find_transport(peer, peer_guid, blob)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 163, in find_transport
    if transport.can_send(peer, peer_guid, blob):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 108, in can_send
    raise NotImplementedError
NotImplementedError
[19:21:25 WARNING papyon.msnp2p.transport.direct] Error mapping port 6892 (timeout)
[19:21:25 DEBUG papyon.msnp2p.session] Bridge listening 151.70.121.143 6892
Available transports: set([<NotificationP2PTransport object at 0xa9956e4 (papyon+msnp2p+transport+base+BaseP2PTransport at 0xa9d8000)>, <SwitchboardP2PTransport peer="Kry-passion@hotmail.it" guid="682ca9d3-92e1-4b6c-b074-28a6918b1c4a">, <SwitchboardP2PTransport peer="alessandro.boxeur@hotmail.it" guid="f08270f4-8164-8847-1ccf-1090fb0effda">, <SwitchboardP2PTransport peer="planamente94@hotmail.it" guid="2c007718-d12b-456a-bc3a-20e791f90e33">, <DirectP2PTransport object at 0xacb6874 (papyon+msnp2p+transport+direct+DirectP2PTransport at 0xb7d9aa0)>, <SwitchboardP2PTransport peer="la_bolanta77@hotmail.com" guid="5442b918-0e19-4831-855d-94f9fd93f9ad">, <DirectP2PTransport object at 0xacb661c (papyon+msnp2p+transport+direct+DirectP2PTransport at 0xb2c269d0)>, <SwitchboardP2PTransport peer="m_z@hotmail.it" guid="None">, <SwitchboardP2PTransport peer="m@nuel.it" guid="None">])
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 318, in _bridge_listening
    external_ip, external_port)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 225, in _accept_transreq
    self._respond_transreq(transreq, 200, body)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 218, in _respond_transreq
    self._send_slp_message(response)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 383, in _send_slp_message
    self._application_id, message)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 83, in send_slp_message
    self.send_data(peer, peer_guid, application_id, 0, str(message))
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 87, in send_data
    transport = self._get_transport(peer, peer_guid, blob)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 171, in _get_transport
    best = self.find_transport(peer, peer_guid, blob)
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 163, in find_transport
    if transport.can_send(peer, peer_guid, blob):
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 108, in can_send
    raise NotImplementedError
NotImplementedError
[19:21:28 DEBUG papyon.transport] >>> XFR 22 SB
[19:21:28 DEBUG papyon.transport] <<< XFR 22 SB 64.4.61.195:1863 CKI 891769317.24811762.47166254 U messenger.msn.com 1
[19:21:28 INFO papyon.protocol.switchboard] New switchboard session 891769317.24811762.47166254
[19:21:28 DEBUG papyon.transport] <-> Connecting to 64.4.61.195:1863
```

**Comment by KinG-InFeT** [comment]
all papylib error
