### ISSUE TITLE
Error on received message

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#126]
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 110, in **call**
    apply(self.f, (self.c(),) + arg)
  File "/home/sven/emesene/emesene/emesene.py", line 519, in on_new_conversation
    gui.play(gui.theme.sound_send)
TypeError: play() takes exactly 2 arguments (1 given)

The error seems clear enough to me ;)

EDIT: This most likely has nothing to do with emoticons. It was just that while testing, it was the first message I received or something.

**Comment by c10ud** [comment]
Fix small bug in play(). Closed by ee1833c0c73bd444aeb3803f81b33c0f53851541
