### ISSUE TITLE
Closing the conversation window in non-single window emesene breaks everything

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1269]
```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/Window.py", line 219, in _on_delete_event
    return self.cb_on_close(self.content_main)
  File "/home/sven/emesene/emesene/emesene.py", line 719, in _on_conversation_window_close
    conv_manager.get_dimensions()
AttributeError: 'NoneType' object has no attribute 'get_dimensions'
[00:29:58 ERROR e3.common.Signal] Signal handler (_on_contact_selected._on_contact_selected) error: 'NoneType' object has no attribute 'present'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/gui/gtkui/MainWindow.py", line 282, in _on_contact_selected
    self.on_new_conversation_requested(contact.account)
  File "/home/sven/emesene/emesene/gui/base/MainWindowBase.py", line 48, in on_new_conversation_requested
    self.on_new_conversation(cid, [account], False)
  File "/home/sven/emesene/emesene/emesene.py", line 709, in on_new_conversation
    conv_manager.present(conversation, sing_wind and conv_tabs)
  File "/home/sven/emesene/emesene/gui/gtkui/ConversationManager.py", line 257, in present
    self.get_parent().present(b_single_window)
AttributeError: 'NoneType' object has no attribute 'present'
```

**Comment by moneycat** [comment]
This problem seems only occur when use mouse to click the close button. Emesene will not brake anything while close traditional conversation window via ESC key.

**Comment by moneycat** [comment]
I think I found the bug. This is my solution:
https://github.com/moneycat/emesene/commit/f5f06006d01359c3e1d75b43d5c69140d407ac0e

If this is correct, I'll pull it. :)

**Comment by c10ud** [comment]
only thing that needs to be checked is with single-window: will the X button call the conv handler?

**Comment by moneycat** [comment]
@c10ud I'm not actually realise the flow of emesene :P

I just test this for single window mode and the behavior on close button is the same.

**Comment by c10ud** [comment]
well these last hacks i did complicated more an already complicated codepath... however one step at a time everything's coming back to normal (?)

thanks for the fix, if it works, then great!
