### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1283]
[14:34:36 WARNING papyon.p2p] Trying to publish an empty MSNObject
[14:34:36 ERROR papyon.msnp2p.session_manager] Session_id == 0
[14:41:22 ERROR papyon.msnp2p.session_manager] Session_id == 0
[14:44:05 ERROR papyon.msnp2p.session_manager] Session_id == 0
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session_manager.py", line 63, in <lambda>
    self._on_slp_message_received(peer, guid, msg))
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session_manager.py", line 180, in _on_slp_message_received
    session._on_slp_message_received(message)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 373, in _on_slp_message_received
    self._transreq_accepted(message.body)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 273, in _transreq_accepted
    new_bridge.open(transresp.nonce, transresp.external_ips[0],
IndexError: list index out of range
[14:44:30 ERROR papyon.msnp2p.session_manager] Session_id == 0
[14:44:59 ERROR papyon.msnp2p.session_manager] Session_id == 0
[14:45:34 ERROR papyon.msnp2p.session_manager] Session_id == 0
[15:15:04 WARNING papyon.p2p] Trying to publish an empty MSNObject

**Comment by c10ud** [comment]
since we need more debug info i added them to latest commit git.io/dR_TwA

please update and report again when issues comes

**Comment by zipatei** [comment]
More errors in single window:

[18:40:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[18:40:55 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[18:41:49 WARNING papyon.p2p] Trying to publish an empty MSNObject
[18:42:17 ERROR papyon.msnp2p.session_manager] Session_id == 0
*\* Message: console message: undefined @0: TypeError: 'undefined' is not an object

[18:49:54 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[18:51:45 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'has_similar_conversation'
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), _arg)
  File "/home/andre/emesene/emesene/gui/common/MessagingMenu.py", line 97, in _on_conv_message
    conv = conv_manager.has_similar_conversation(cid, [account])
AttributeError: 'NoneType' object has no attribute 'has_similar_conversation'
*_ Message: console message: undefined @0: TypeError: 'undefined' is not an object

**Comment by Sbte** [comment]
The above error is unrelated to this issue. Please open new issues for different bugs....

**Comment by zipatei** [comment]
[15:38:35 WARNING papyon.p2p] Trying to publish an empty MSNObject
[15:38:36 ERROR papyon.msnp2p.session_manager] Session_id == 0
[15:38:36 ERROR papyon.msnp2p.session_manager] Session_id == 0
[15:39:02 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[15:39:03 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[15:39:03 ERROR papyon.msnp2p.session_manager] Session_id == 0
[15:39:16 ERROR papylib.Events] Error sending message: 4 1

(emesene:3145): GStreamer-WARNING **: Failed to load plugin '/usr/lib/i386-linux-gnu/gstreamer-0.10/libgstbluetooth.so': /usr/lib/i386-linux-gnu/gstreamer-0.10/libgstbluetooth.so: não é possível agarrar objecto partilhado: Descritor de ficheiro inválido
[15:45:58 ERROR papyon.msnp2p.session] list index out of range
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 274, in _transreq_accepted
    new_bridge.open(transresp.nonce, transresp.external_ips[0],
IndexError: list index out of range
Listening: true
NeedConnectingEndpointInfo: true
Conn-Type: Port-Restrict-NAT
TCP-Conn-Type: Port-Restrict-NAT
IPv6-global:  ip censored
UPnPNat: true
Capabilities-Flags: 1
srddA-lanretxE4vPI: ip censored
troP-lanretxE4vPI: 48785
srddA-lanretnI4vPI: ip censored
troP-lanretnI4vPI: 48785
IPv6-Addrs: ip censored
IPv6-Port: 58785
Nat-Trav-Msg-Type: WLX-Nat-Trav-Msg-Direct-Connect-Resp
Bridge: TCPv1
Nonce: {D201A978-EA06-4769-BC0B-9F4E6DC5B83D}

[15:46:23 ERROR papyon.msnp2p.session_manager] Session_id == 0
[15:57:00 WARNING papyon.p2p] Trying to publish an empty MSNObject
[15:57:02 WARNING papyon.p2p] Trying to publish an empty MSNObject

**Comment by c10ud** [comment]
ok, that should be

you sending a message to some windows live messenger

am i right? wlm 2009 or newer?

still is weird we have External ips in the transreq...

**Comment by c10ud** [comment]
looks like e16840e04296f5915f94b5d95637cbd1a5c4309c version isn't passed correctly when this message is received
