### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_selected'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1298]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/ContactList.py", line 316, in open_conversation
    contact = self.get_contact_selected()
  File "/home/andre/emesene/emesene/gui/gtkui/ContactList.py", line 416, in get_contact_selected
    selected = self._get_selected()
  File "/home/andre/emesene/emesene/gui/gtkui/ContactList.py", line 305, in _get_selected
    iter_ = self.get_selection().get_selected()[1]
AttributeError: 'NoneType' object has no attribute 'get_selected'

**Comment by c10ud** [comment]
please be more verbose, how, which ui, etc.

**Comment by zipatei** [comment]
sorry... GTK2... Click CTRL + T in contact list
