### ISSUE TITLE
Crash when click Preferences

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1300]
Dears,

Here is a defect in Sabayon System (Gentoo based linux distribution).
Here is error log bellow:

Version: emesene-2.12.4_dev
OS: Sabayon 8

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
[22:36:31 ERROR sleekxmpp.xmlstream.xmlstream] Could not connect to [2404:6800:8005::7d]:5222. Socket Error #101: Network is unreachable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/MainMenu.py", line 207, in <lambda>
    lambda _args: self.handler.on_preferences_selected())
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/Handler.py", line 130, in on_preferences_selected
    self.session)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/extension.py", line 453, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/extension.py", line 290, in get_and_instantiate
    inst = cls(_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Preferences.py", line 147, in **init**
    self.**init_list()
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Preferences.py", line 250, in __init_list
    self.facebook = Facebook(self.session)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Preferences.py", line 1331, in __init**
    'session.config.b_fb_enable_integration')
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Preferences.py", line 408, in append_check
    widget = self.create_check(text, property_name)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Preferences.py", line 400, in create_check
    widget.set_active(default)
TypeError: an integer is required
^\Quit

**Comment by Sbte** [comment]
@pepeleproso this happens (I think) because when logged in to google talk, the Facebook preferences tab will still be drawn. See the line

`if 'facebook' in self.session.SERVICES:`

**Comment by shwangdev** [comment]
widget = gtk.CheckButton(text)
  widget.set_active(default)

I sew that the value of "default" is None which causes error with function set_active.
