### ISSUE TITLE
Chat messages was transferred to notification message, but not show in chat window.

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1302]
Here is log

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/ConversationManager.py", line 105, in _on_message
    conversation = self.new_conversation(cid, [account])
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/ConversationManager.py", line 270, in new_conversation
    conversation.update_data()
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/Conversation.py", line 530, in update_data
    self._update_single_information(self.members[0])
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/Conversation.py", line 586, in _update_single_information
    nick = MarkupParser.escape(contact.display_name)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/MarkupParser.py", line 47, in escape
    return xml.sax.saxutils.escape(string_, dic)
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 39, in escape
    data = data.replace("&", "&amp;")
TypeError: 'NoneType' object is not callable
/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/**init**.py:97: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()
/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/ContactList.py:366: GtkWarning: gtk_tree_model_filter_real_unref_node: assertion`elt->ref_count > 0' failed
  self.model.refilter()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/ConversationManager.py", line 163, in _on_switch_page
    self.set_message_waiting(page, False)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/ConversationManager.py", line 145, in set_message_waiting
    conversation.message_waiting = is_waiting
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/Conversation.py", line 373, in _set_message_waiting
    self.update_message_waiting(value)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Conversation.py", line 257, in update_message_waiting
    self.update_tab()
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Conversation.py", line 281, in update_tab
    self.tab_label.set_text(self.text)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/TabWidget.py", line 131, in set_text
    self._label.set_markup(gobject.markup_escape_text(text))
TypeError: glib.markup_escape_text() argument 1 must be string or read-only buffer, not JID
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/ConversationManager.py", line 163, in _on_switch_page
    self.set_message_waiting(page, False)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/ConversationManager.py", line 145, in set_message_waiting
    conversation.message_waiting = is_waiting
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/base/Conversation.py", line 373, in _set_message_waiting
    self.update_message_waiting(value)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Conversation.py", line 257, in update_message_waiting
    self.update_tab()
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/Conversation.py", line 281, in update_tab
    self.tab_label.set_text(self.text)
  File "/usr/lib/python2.7/site-packages/emesene-2.12.4_dev-py2.7.egg/emesene/gui/gtkui/TabWidget.py", line 131, in set_text
    self._label.set_markup(gobject.markup_escape_text(text))
TypeError: glib.markup_escape_text() argument 1 must be string or read-only buffer, not JID
^\Quit

**Comment by Sbte** [comment]
Apparently, xmpp session makes contacts with the account being None.

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/blob/master/emesene/e3/xmpp/Worker.py#L102

This piece of code is broken. For example `account` doesn't even exist: @c10ud

**Comment by c10ud** [comment]
will look into it asap

**Comment by shwangdev** [comment]
fix it

**Comment by c10ud** [comment]
i surely will

2012/5/28 Xiang Wang
reply@reply.github.com:

**Comment by c10ud** [comment]
ok, i fixed something but i'm unsure that's related to this, JID is always unicode here. i tried with gtalk and facebook

**Comment by shwangdev** [comment]
not fixit, this case can still be reproduced.

**Comment by c10ud** [comment]
are you using gtalk? can you run it with -vvv? (more debug)

2012/5/28 Xiang Wang
reply@reply.github.com:

**Comment by shwangdev** [comment]
*I doult that , why login gtalk , emesene cost a lots of time.

And with debug option , there is a debug log always showed up:

[22:27:35 DEBUG sleekxmpp.thirdparty.statemachine] State was not ready

What doese sleekxmapp do in backend when login.
Why it costs so much time...

*
On Mon, May 28, 2012 at 10:09 PM, Riccardo <
reply@reply.github.com

> wrote:
> 
> are you using gtalk? can you run it with -vvv? (more debug)
> 
> 2012/5/28 Xiang Wang
> reply@reply.github.com:
> 
> > not fixit, this case can still be reproduced.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/emesene/emesene/issues/1302#issuecomment-5965262
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/1302#issuecomment-5965973

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_
