### ISSUE TITLE
qt4ui broken

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1324]
$ ./emesene/emesene -e main:qt4_main
Traceback (most recent call last):
  File "./emesene/emesene", line 34, in <module>
    emesene.main()
  File "emesene/emesene.py", line 768, in main
    main_method(Controller)
  File "emesene/gui/qt4ui/**init**.py", line 42, in qt4_main
    controller.start()
  File "emesene/emesene.py", line 258, in start
    self._set_location(self.window)
  File "emesene/emesene.py", line 529, in _set_location
    window.set_location(width, height, posx, posy, single_window and is_conv)
TypeError: set_location() takes exactly 5 arguments (6 given)

**Comment by jamesaxl** [comment]
yeah after combining contact list with chatwindow , qt4 need some update, i have cared about qt4 but i felt boring after this last change :(, i need time god willing

**Comment by c10ud** [comment]
pepeleproso fixed this, ofcourse qt4 ui is still incomplete, etc.

**Comment by pepeleproso** [comment]
I'll be doing some work on qt. I want to use qt on windows since gtk on windows is unmaintained upstream.
