### ISSUE TITLE
[Discuss] crash on utf8 decode?

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1327]
Does anyone encounter the same problem recently? My emesene broken many times a day.

Error message:

```
[12:04:48 ERROR papyon.msnp2p.session] Bridge switching failed, using default one (switchboard)
[12:04:48 ERROR papyon.msnp2p.session] Bridge switching failed, using default one (switchboard)
[12:06:08 ERROR e3.common.Signal] Signal handler (on_contact_attr_changed_succeed.on_contact_attr_changed_succeed) error: 'utf8' codec can't decode bytes in position 64-65: invalid continuation byte
Traceback (most recent call last):
  File "/emesene/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/emesene/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "/emesene/gui/gtkui/Conversation.py", line 426, in on_contact_attr_changed_succeed
    self.update_data()
  File "/emesene/gui/base/Conversation.py", line 532, in update_data
    self.update_group_information()
  File "/emesene/gui/gtkui/Conversation.py", line 349, in update_group_information
    ", ".join(members_nick))
  File "/emesene/gui/gtkui/Header.py", line 74, in _set_information
    self._information.set_markup(Header.INFO_TPL % lines)
  File "/emesene/gui/gtkui/Renderers.py", line 568, in set_markup
    markup = msnplus_to_list(text)
  File "/emesene/gui/gtkui/Renderers.py", line 161, in msnplus_to_list
    text = plus_text_parse(text, plus)
  File "/emesene/gui/gtkui/Renderers.py", line 154, in plus_text_parse
    item = Plus.msnplus_parse(item)
  File "/emesene/gui/base/Plus.py", line 404, in msnplus_parse
    dictlike = msnplus(text, False)
  File "/emesene/gui/base/Plus.py", line 390, in msnplus
    text = unicode(text, 'utf8') if not isinstance(text, unicode) else text
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 64-65: invalid continuation byte
[12:11:06 ERROR e3.common.Signal] Signal handler (on_contact_attr_changed_succeed.on_contact_attr_changed_succeed) error: 'utf8' codec can't decode bytes in position 64-65: invalid continuation byte
Traceback (most recent call last):
  File "/emesene/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/emesene/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "/emesene/gui/gtkui/Conversation.py", line 426, in on_contact_attr_changed_succeed
    self.update_data()
  File "/emesene/gui/base/Conversation.py", line 532, in update_data
    self.update_group_information()
  File "/emesene/gui/gtkui/Conversation.py", line 349, in update_group_information
    ", ".join(members_nick))
  File "/emesene/gui/gtkui/Header.py", line 74, in _set_information
    self._information.set_markup(Header.INFO_TPL % lines)
  File "/emesene/gui/gtkui/Renderers.py", line 568, in set_markup
    markup = msnplus_to_list(text)
  File "/emesene/gui/gtkui/Renderers.py", line 161, in msnplus_to_list
    text = plus_text_parse(text, plus)
  File "/emesene/gui/gtkui/Renderers.py", line 154, in plus_text_parse
    item = Plus.msnplus_parse(item)
  File "/emesene/gui/base/Plus.py", line 404, in msnplus_parse
    dictlike = msnplus(text, False)
  File "/emesene/gui/base/Plus.py", line 390, in msnplus
    text = unicode(text, 'utf8') if not isinstance(text, unicode) else text
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 64-65: invalid continuation byte
Segmentation fault (core dumped)
```

**Comment by moneycat** [comment]
Accroding to: http://docs.python.org/howto/unicode.html. It seems like the text combined with unicode and ascii words but it is hard to reproduce by myself.

```
>>> unicode('\x80abc', errors='strict')
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0:
                    ordinal not in range(128)
>>> unicode('\x80abc', errors='replace')
u'\ufffdabc'
>>> unicode('\x80abc', errors='ignore')
u'abc'
```

Is it better to modify
`text = unicode(text, 'utf8') if not isinstance(text, unicode) else text`
to
`text = unicode(text, 'utf8', 'ignore') if not isinstance(text, unicode) else text`?

**Comment by Sbte** [comment]
It's probably some bug like this one:

https://github.com/emesene/emesene/commit/119aaef17d883a471eb8afca2b57127b03ba3cac

**Comment by moneycat** [comment]
I close this issue because it is hard to re-produce. I'll still trace if it still occurs.
