### ISSUE TITLE
Error of msnplus

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1330]
If nick or message is`[I]`, nothing shown in the field. If user typing a close tag like `[/C]`, it will rise error.

Traceback (most recent call last):
  File "/emesene/gui/gtkui/TextField.py", line 91, in on_entry_activate
    self.text = self.entry.get_text()
  File "/emesene/gui/gtkui/TextField.py", line 128, in _set_text
    gobject.markup_escape_text(self._text or self.empty_text))
  File "/emesene/gui/gtkui/Renderers.py", line 568, in set_markup
    markup = msnplus_to_list(text)
  File "/emesene/gui/gtkui/Renderers.py", line 161, in msnplus_to_list
    text = plus_text_parse(text, plus)
  File "/emesene/gui/gtkui/Renderers.py", line 154, in plus_text_parse
    item = Plus.msnplus_parse(item)
  File "/emesene/gui/base/Plus.py", line 406, in msnplus_parse
    dictlike = msnplus(text, False)
  File "/emesene/gui/base/Plus.py", line 393, in msnplus
    dictlike = _msnplus_to_dict(text, message_stack, do_parse_emotes)
  File "/emesene/gui/base/Plus.py", line 210, in _msnplus_to_dict
    _close_tags(message_stack, text_before, tag, arg, do_parse_emotes)
  File "/emesene/gui/base/Plus.py", line 129, in _close_tags
    if isinstance(message_stack[stack_index], dict):
IndexError: list index out of range

**Comment by Sbte** [comment]
I left this as it is (I added the test), because it's probably hard to fix and there's also probably no one who will ever use `[/c]` in their name just to mess with you :P

**Comment by moneycat** [comment]
@Sbte I look into the code and it too hard to fix of my understand. Maybe one day we can find a way to fix it. Thanks for reply. :P

**Comment by moneycat** [comment]
@Sbte I've implement a strict tag verification for msnplus d9b9b805ad4cf822bc59d3d272eb2afe58374060. If you have some free time, take a look into it, please. Thanks.

**Comment by Sbte** [comment]
Seems to work, and I have no idea what you just did, so push it :P
