### ISSUE TITLE
Cannot login to MSN

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1344]
I cannot login to MSN with emesene  2.12.6-dev. It just loads forever and nothing happens.

`Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/papylib/papyon/papyon/gnet/io/ssl_socket.py", line 68, in _io_channel_handler
    self._transport.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 283, in do_handshake
AttributeError: 'NoneType' object has no attribute 'do_handshake'`

./emesene -vvv

`[09:58:53 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x10e64cd70 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x7fd5d39dc140)>
[09:58:53 DEBUG papyon.transport] <-> Connecting to messenger.hotmail.com:1863
[09:58:53 DEBUG papyon.transport] >>> VER 0 MSNP18 MSNP16 MSNP15
[09:58:53 DEBUG papyon.transport] <<< VER 0 MSNP18
[09:58:53 DEBUG papyon.transport] >>> CVR 1 0x0409 winnt 5.1 i386 MSNMSGR 8.1.0178 msmsgs MYEMAIL@msn.com
[09:58:53 DEBUG papyon.transport] <<< CVR 1 14.0.8117 14.0.8117 14.0.8117 http://msgruser.dlservice.microsoft.com/download/A/6/1/A616CCD4-B0CA-4A3D-B975-3EDB38081B38/en/wlsetup-cvr.exe http://download.live.com/?sku=messenger
[09:58:53 DEBUG papyon.transport] >>> USR 2 SSO I MYEMAIL@msn.com
[09:58:54 DEBUG papyon.transport] <<< XFR 2 NS 64.4.61.41:1863 U D
[09:58:54 DEBUG papyon.protocol.notification] <-> Redirecting to 64.4.61.41:1863
[09:58:54 DEBUG papyon.transport] >>> VER 3 MSNP18 MSNP16 MSNP15
[09:58:54 DEBUG papyon.transport] <<< VER 3 MSNP18
[09:58:54 DEBUG papyon.transport] >>> CVR 4 0x0409 winnt 5.1 i386 MSNMSGR 8.1.0178 msmsgs MYEMAIL@msn.com
[09:58:54 DEBUG papyon.transport] <<< CVR 4 14.0.8117 14.0.8117 14.0.8117 http://msgruser.dlservice.microsoft.com/download/A/6/1/A616CCD4-B0CA-4A3D-B975-3EDB38081B38/en/wlsetup-cvr.exe http://download.live.com/?sku=messenger
[09:58:54 DEBUG papyon.transport] >>> USR 5 SSO I MYEMAIL@msn.com
[09:58:55 DEBUG papyon.transport] <<< GCF 0 5900
    [payload]
[09:58:55 DEBUG papyon.transport] <<< USR 5 SSO S MBI_KEY ylBwbkujlr5UNWriFjdD0/s2a3e8Nl8hceAQjUdeVelZR6aSbNQG4PfUC2B0xz8o
Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/papylib/papyon/papyon/gnet/io/ssl_socket.py", line 68, in _io_channel_handler
    self._transport.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 283, in do_handshake
AttributeError: 'NoneType' object has no attribute 'do_handshake'`

**Comment by joshf** [comment]
Whoops dup of #1341
