### ISSUE TITLE
PyNotification.py TraceBack

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1347]
I use:
OS: ArchLinux
emesene verson: Last GIT
WM: fluxbox with GTK3

emesene -vvv output

Reproducible:
1) Open emesene
2) login
3) open conversation
4) close conversation and close emesene window with ESC key

use single-window mode

NOTE: maybe I'm wrong to repost ... but I see a python error.

``` python
[20:24:28 ERROR e3.common.Signal] Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "/usr/share/emesene2/e3/common/notification.py", line 200, in _on_contact_attr_changed
    self._notify(contact, contact.nick, text, contact.account, sound)
  File "/usr/share/emesene2/e3/common/notification.py", line 233, in _notify
    self.notifier(title if title else '', text, uri, 'message-im', None, tooltip)
  File "/usr/share/emesene2/gui/common/PyNotification.py", line 59, in PyNotification
    notification.show()
GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[20:24:29 WARNING papyon.p2p] Trying to publish an empty MSNObject
```

**Comment by Sbte** [comment]
Seems like a broken OS to me. If you have pynotify, but you can't use it, then that's not our fault.

Also, how can closing a conversation cause a notification to appear?

**Comment by pepeleproso** [comment]
I'm using arch and gtk3 and I didn't have this error. As the GError says there's some missing package. Did you have libnotify installed? Maybe the problem could be you didn't have dbus daemon running?
Anyway this isn't an emesene error.

**Comment by KinG-InFeT** [comment]
fix this problem in archlinux package (AUR) https://aur.archlinux.org/packages.php?ID=28048

**Comment by Sbte** [comment]
Good. But maybe they should add the libnotify dependency to the pynotify package (which apparently you DID have)

**Comment by KinG-InFeT** [comment]
I agree
