### ISSUE TITLE
Emesene Empty Contact List on Login

### ISSUE THREAD

**Issue by Bisneff** [emesene/emesene#1348]
Hi.

Some days ago I login Emesene with my WLM account and I see no contact in list.

I thinked no one was online, and didn't care of it. But when someone login I see the notification, but my contact list is still empty.

If I start to mess up with contact list preference, it freeze for some seconds/minutes and then load my contacs.

From terminal:

  File "/home/bisneff/.config/emesene2/plugins/idle_status/plugin.py", line 73, in idle_state
    self.timer = extension.get_and_instantiate('idle timer')
  File "/usr/share/emesene/emesene/extension.py", line 616, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, _args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 487, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(_args, *_kwargs)
  File "/home/bisneff/.config/emesene2/plugins/idle_status/xidletimer.py", line 39, in **init**
    self.xss        = ctypes.cdll.LoadLibrary('libXss.so')
  File "/usr/lib/python2.7/ctypes/**init**.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libXss.so: cannot open shared object file: No such file or directory

Thank's for your help :)

**Comment by c10ud** [comment]
disable the idle plugin, looks like you enabled it but you don't have the necessary libraries for it

**Comment by Bisneff** [comment]
Thank you
I disabled the plug in, but still have the same problem.

**Comment by Bisneff** [comment]
Thank you
I disabled the plug in, but still have the same problem.

**Comment by c10ud** [comment]
then it's still calling the import: i think you must remove /home/bisneff/.config/emesene2/plugins/idle_status/

and possibly poke the plugin's author and let him know about this bug :)

**Comment by Bisneff** [comment]
blablabla~/.config/emesene2/plugins$ ls
contact_status_history_combo  music  typing_notification

:/

**Comment by c10ud** [comment]
it's not the same problem then, do you have some new terminal output?

**Comment by Bisneff** [comment]
when I quit the program the therminal shows:
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/share/emesene/emesene/e3/papylib/Worker.py", line 140, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

**Comment by c10ud** [comment]
that's normal, interpreter shutdown errors are likely to happen, they're harmless

**Comment by pepeleproso** [comment]
I fixed the plugin bug, please update the plugin to get it working.

**Comment by Bisneff** [comment]
Thank You Guys.

Now Seems Work :)
