### ISSUE TITLE
Facebook chat doesn't work...

### ISSUE THREAD

**Issue by saguar** [emesene/emesene#135]
this is what I get when try to log-in on facebook chat:

saverio@saverio-Dell:~/emesene2/emesene$ ./emesene 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/saverio/emesene2/emesene/e3/jabber/Worker.py", line 71, in run
    self._process_action(action)
  File "/home/saverio/emesene2/emesene/e3/base/Worker.py", line 149, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/saverio/emesene2/emesene/e3/jabber/Worker.py", line 189, in _handle_action_login
    proxy=self.proxy_data) == "":
  File "/home/saverio/emesene2/emesene/e3/jabber/xmpp/client.py", line 200, in connect
    if not CommonClient.connect(self,server,proxy,secure,use_srv) or secure<>None and not secure: return self.connected
  File "/home/saverio/emesene2/emesene/e3/jabber/xmpp/client.py", line 184, in connect
    if not self.Process(1): return
  File "/home/saverio/emesene2/emesene/e3/jabber/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "/home/saverio/emesene2/emesene/e3/jabber/xmpp/dispatcher.py", line 215, in streamErrorHandler
    raise exc((name,text))
HostUnknown: (u'host-unknown', '')

**Comment by c10ud** [comment]
Fixed Facebook connection with xmpppy. Closed by 3fd1b8a1b189812a9543198bcf27c828258907cd
