### ISSUE TITLE
AttributeError: 'Signals' object has no attribute 'close' 

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1387]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Window.py", line 257, in _on_delete_event
    return self.cb_on_close()
  File "/home/andre/emesene/emesene/emesene.py", line 330, in close_session
    self._remove_subscriptions()
  File "/home/andre/emesene/emesene/emesene.py", line 378, in _remove_subscriptions
    signals.close.unsubscribe(self.on_close)
AttributeError: 'Signals' object has no attribute 'close'

**Comment by c10ud** [comment]
when did this happen? cannot reproduce here

**Comment by zipatei** [comment]
this, happened to me after i click close after this https://github.com/emesene/emesene/issues/1386

**Comment by c10ud** [comment]
ok then it should work now
