### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1393]
I dont know to reproduce

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session_manager.py", line 63, in <lambda>
    self._on_slp_message_received(peer, guid, msg))
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session_manager.py", line 180, in _on_slp_message_received
    session._on_slp_message_received(message)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 374, in _on_slp_message_received
    self._transreq_accepted(message.body)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 274, in _transreq_accepted
    new_bridge.open(transresp.nonce, transresp.external_ips[0],
IndexError: list index out of range

**Comment by jamesaxl** [comment]
how did you et this lines ? explain more please

**Comment by zipatei** [comment]
nothing... just conversation.

**Comment by c10ud** [comment]
the contact you were talking to probably sent a malformed p2p-direct-connect response

**Comment by c10ud** [comment]
(see his external_ips list was empty, and at least one entry should be available)

**Comment by c10ud** [comment]
fixed
