### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'exc_info'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1394]
Unhandled exception in thread started by <bound method Worker.__bootstrap of <Worker(Thread-2, stopped daemon -1457423552)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 564, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 240, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'

Reproduce:
Click close im Main Menu

**Comment by c10ud** [comment]
unrepr here, if there's any other step please tell us
