### ISSUE TITLE
emesene wont quit or disconnect

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1408]
When i try to quit emesene the tray icon dissapears but the main window stay open. This happens both when selecting quit and using the keyboard. The same happens when i try and disconnect.

emesene 2.12.6-dev
OS X 10.7.4

```
[06:53:13 ERROR e3.common.Signal] Signal handler (on_close.on_close) error: 'DummyExternalAPI' object has no attribute 'stop'
Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/Applications/emesene.app/Contents/Resources/emesene/WeakMethod.py", line 33, in __call__
    self.f(self.c(), *arg)
  File "emesene.py", line 711, in on_close
    self.close_session(close)
  File "emesene.py", line 335, in close_session
    self._remove_subscriptions()
  File "emesene.py", line 397, in _remove_subscriptions
    self.dbus_ext.stop()
AttributeError: 'DummyExternalAPI' object has no attribute 'stop'
```

This happens at the login screen and in all accounts

**Comment by Sbte** [comment]
@joshf if you want to fix this, just add

``` python
def stop(self):
    pass
```

to the dummy api.

**Comment by joshf** [comment]
Will fix when I get home
------Original Message------
