### ISSUE TITLE
messaging menu disappear

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#1411]
hello, messaging menu disappears from ubuntu 12.04 64bit after emesene disconnect and reconnect.
here is the debug:

[23:33:00 DEBUG papyon.transport] <<< QNG 47
[23:33:47 DEBUG papyon.transport] >>> PNG
[23:33:47 DEBUG papyon.transport] <<< QNG 48
[23:34:36 DEBUG papyon.transport] >>> PNG
[23:34:36 DEBUG papyon.transport] <<< QNG 40
[23:35:17 DEBUG papyon.transport] >>> PNG
[23:35:17 DEBUG papyon.transport] <<< QNG 40
[23:35:58 DEBUG papyon.transport] >>> PNG
[23:36:03 DEBUG e3.base.Worker] closing thread
[Thread 0x7fff8df2b700 (LWP 15426) exited]
[Thread 0x7fff7bfff700 (LWP 15427) exited]
[New Thread 0x7fff7bfff700 (LWP 25330)]
[23:36:32 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x28a2c80 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x2b116c0)>
[New Thread 0x7fff8df2b700 (LWP 25331)]
[New Thread 0x7fff82017700 (LWP 25332)]
[New Thread 0x7fff82818700 (LWP 25333)]
[23:36:32 DEBUG papyon.transport] <-> Connecting to messenger.hotmail.com:1863
[23:36:37 ERROR e3.common.Signal] Signal handler (on_disconnected.on_disconnected) error: 'Signals' object has no attribute 'picture_change_succeed'
Traceback (most recent call last):
  File "/home/ammar/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/ammar/emesene/emesene/WeakMethod.py", line 33, in **call**
    self.f(self.c(), *arg)
  File "emesene.py", line 713, in on_disconnected
    self.close_session(False, True)
  File "emesene.py", line 334, in close_session
    conv_manager.close_session()
  File "/home/ammar/emesene/emesene/gui/base/ConversationManager.py", line 295, in close_session
    conversation.unsubscribe_signals()
  File "/home/ammar/emesene/emesene/gui/base/Conversation.py", line 127, in unsubscribe_signals
    self.session.signals.picture_change_succeed.unsubscribe(
AttributeError: 'Signals' object has no attribute 'picture_change_succeed'
[Thread 0x7fff8e72c700 (LWP 15425) exited]

**Comment by moneycat** [comment]
@ammarabdulsalam Which version do you use? Latest git or stable version?

**Comment by ammarabdulsalam** [comment]
latest git version

**Comment by ammarabdulsalam** [comment]
here is another log. when emesene couldn't connect to messenger service, the indicator disappear.
[09:49:35 DEBUG papyon.transport] <-> Connecting to messenger.hotmail.com:1863
[New Thread 0x7fff8d72a700 (LWP 27115)]
[Thread 0x7fff968a6700 (LWP 27106) exited]
[09:49:55 DEBUG e3.base.Worker] closing thread
[Thread 0x7fff7bfff700 (LWP 27114) exited]
[Thread 0x7fff8df2b700 (LWP 27113) exited]

**Comment by c10ud** [comment]
#1406
