### ISSUE TITLE
Mute sound broken

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1415]
[20:56:17 ERROR NotificationObject] Error calling config callback <function _on_b_mute_sounds_changed at 0x1a73938> for b_mute_sounds
Traceback (most recent call last):
  File "emesene/NotificationObject.py", line 46, in notify_change
    callback(value)
  File "emesene/WeakMethod.py", line 31, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object
Traceback (most recent call last):
  File "emesene/gui/gtkui/Preferences.py", line 567, in on_toggled
    self.set_attr(property_name, checkbutton.get_active())
  File "emesene/gui/gtkui/Preferences.py", line 591, in set_attr
    setattr(obj, terms[-1], value)
  File "emesene/e3/common/BaseConfig.py", line 53, in **setattr**
    self.notify_change(item, value)
  File "emesene/NotificationObject.py", line 50, in notify_change
    raise ex
TypeError: Method called on dead object

**Comment by moneycat** [comment]
Traceback (most recent call last):
  File "emesene/gui/common/TrayIcon.py", line 237, in _on_mute_unmute_sounds
    self.handler.session.config.b_mute_sounds = not value
  File "emesene/e3/common/BaseConfig.py", line 53, in __setattr__
    self.notify_change(item, value)
  File "emesene/NotificationObject.py", line 50, in notify_change
    raise ex
TypeError: Method called on dead object

**Comment by moneycat** [comment]
A strange issue that the logic seems correctly.

@Sbte

**Comment by moneycat** [comment]
d182d64 will cause no main tray icon when change from indicator (startup default by myself) to trayicon.
