### ISSUE TITLE
Custom emoticon and account issues

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1429]
This ticket will cover 2 issues:
1. Only the FIRST custom emoticon sent from emesene can be received by WLM 2009.
   Moreover, emesene <-> emesene in the same PC works now.
   The above testing is with a `@hotmail.com` account and an `@livemail.tw` account.
2. The account issue is very strange.
   I've registered a `@live.com` account and do all my test previously. However, I found every function in that account can not work normally, such as receive avatar from others, send avatar to other, custom emoticons sent/received.
   Will capitalization affect this? I found the account will create a `LIVE.COM` directory and sent messages header with `LIVE.COM` even I add it with typing as `@live.com` .

Summary: After I test emesene with another account (the @livemail.tw one), things work well. I'm still confused why the account (@LIVE.COM) will affect too much.

**Comment by c10ud** [comment]
this capitalization thing is interesting. is it happening out of the box or did you type mail@LIVE.COM in the account field?

**Comment by c10ud** [comment]
also, gtkui/Login.py:

```
def do_connect(self):
    '''
    do all the stuffs needed to connect
    '''
    self.nicebar.empty_queue()
    user = self.cmb_account.get_active_text().strip().lower()
```

**Comment by c10ud** [comment]
(just tested with gtk2 and it works as expected)

**Comment by moneycat** [comment]
I typed is lower case. After login procedure, it will create a @LIVE.COM directory in config directory.

**Comment by c10ud** [comment]
...and just lowered in qt4ui

**Comment by moneycat** [comment]
I lost something. The procedure seems: A@hotmail.com and B@live.com. A@hotmail.com add account: B@live.com (What I type is lower case), but it will create a upper case dir in config dir.

I'll test again if I'm free tonight.

**Comment by moneycat** [comment]
I got your message. It seems user account directory created when login, in `emesene/emesene.py` line 134.

Now when I add contact from WLM 2009, emesene will not pop-up add contact window. I need to add it by myself again.
When I click the account in B, an error arise and then the add dialog shown:

<pre>[16:35:50 ERROR papylib.Events] contact moneycat.tw@hotmail.com not found on address book
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/e3/base/Worker.py", line 183, in run
    self._process_action(action)
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/e3/base/Worker.py", line 191, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/e3/papylib/Worker.py", line 1260, in _handle_action_new_conversation
    conv = papyon.Conversation(self, [contact,])
  File "/home/moneycat/Downloads/Program/emesene-m/emesene/e3/papylib/papyon/papyon/conversation.py", line 58, in Conversation
    if contact.network_id == NetworkID.MSN])
AttributeError: 'NoneType' object has no attribute 'network_id'</pre>

**Comment by moneycat** [comment]
And more interesting thing is, the @LIVE.COM problem only affect my hotmail.com account. My @livemail.tw account will not create a upper-case dir in it. Some log from B is:

<pre>[16:35:53 INFO papyon.service.address_book] [B@LIVE.COM] Received sync request:
...contacts: []
...groups: []
...memberships: ['support.service@live.com A-Allow', 'A@hotmail.com A-Pending']
[16:35:53 DEBUG papylib.Events] contact pending: <papyon.Contact id='00000000-0000-0000-0000-000000000000' network='1' account='A@hotmail.com' memberships='PENDING'>
</pre>

**Comment by c10ud** [comment]
ahhh now i get what you meant with add account :)

**Comment by moneycat** [comment]
This is some log when add from A, I will give more detail in private message if you want.

Edit: Github will let html tag work...so the log seems strange...lol

[16:45:17 ERROR papylib.Events] contact B@live.com not found on address book
[16:45:17 DEBUG papyon.service] >>> POST /abservice/abservice.asmx HTTP/1.0
Content-Length: 2214
Proxy-Connection: Keep-Alive
SOAPAction: http://www.msn.com/webservices/AddressBook/ABContactAdd
Host: local-bay.contacts.msn.com:443
Accept: text/*
User-Agent: gnet/0.1 (Linux x86_64)
Connection: Keep-Alive
Cache-Control: no-cache
Content-Type: text/xml; charset=utf-8
Accept-Encoding: gzip
...
[16:45:19 DEBUG papyon.service] <<< Received response for FindMembership
[16:45:19 DEBUG papyon.service] <<<<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">soap:Header<ServiceHeader xmlns="http://www.msn.com/webservices/AddressBook"><Version>16.04.0719.0001</Version><CacheKey>.....<PassportName>B@LIVE.COM</PassportName>....<CreatorPassportName>A@hotmail.com</CreatorPassportName>...<CreateDate>2005-08-24T01:09:14.11-07:00</CreateDate><LastChange>2012-08-09T01:44:59.753-07:00</LastChange></OwnerNamespace></FindMembershipResult></FindMembershipResponse>/soap:Body/soap:Envelope
[16:45:19 INFO papyon.service.address_book] [A@hotmail.com] Received sync request:
...contacts: ['A-B@LIVE.COM']
...groups: []
...memberships: ['B@LIVE.COM A-Allow D-Block']

Very weird...

**Comment by c10ud** [comment]
after testing with moneycat i can say i have absolutely no idea on what's going on here

tried with testing accounts, etc.

**Comment by moneycat** [comment]
It seems it cannot be solved because it is due to MSN sever will pass an upper case name. We close it.
