### ISSUE TITLE
[qt4] "No Group" without counting (0/0)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1457]
I have contact without group, but in qt4 are not counted.

**Comment by Sbte** [comment]
I get this

```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/gui/qt4ui/widgets/ContactListDelegate.py", line 205, in sizeHint
    text_list = self._build_display_role(index, isinstance(data_role, e3.base.Group))
  File "/home/sven/emesene-dev/emesene/gui/qt4ui/widgets/ContactListDelegate.py", line 77, in _build_display_role
    display_role = self.contact_list.format_group(data_role)
  File "/home/sven/emesene-dev/emesene/gui/base/ContactList.py", line 467, in format_group
    if self.order_by_status:
  File "/home/sven/emesene-dev/emesene/gui/base/ContactList.py", line 306, in _get_order_by_status
    return not self.order_by_group
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
