### ISSUE TITLE
Add contact

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1465]
[10:40:39 ERROR papylib.Events] contact alicia_98@live.com.pt not found on address book
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 183, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 191, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 960, in _handle_action_add_contact
    n_id = NetworkID.MSN
NameError: global name 'NetworkID' is not defined

**Comment by c10ud** [comment]
thanks, my bad
