### ISSUE TITLE
Qt4 Error

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1484]
[15:10:00 ERROR e3.common.Signal] Method called on dead object: Controller.on_login_succeed
Traceback (most recent call last):
  File "/home/devil/linux/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/devil/linux/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/devil/linux/emesene/emesene/emesene.py", line 570, in on_login_succeed
    self.draw_main_screen()
  File "/home/devil/linux/emesene/emesene/emesene.py", line 482, in draw_main_screen
    self.tray_icon.quit_on_close)
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/TopLevelWindow.py", line 148, in go_main
    main_page = main_window_cls(session, on_new_conversation, self.setMenuBar)
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/pages/MainPage.py", line 52, in **init**
    self._setup_ui()
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/pages/MainPage.py", line 64, in _setup_ui
    self.contact_list = contact_list_cls(self.session)
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/widgets/ContactList.py", line 51, in __init__
    gui.ContactList.**init**(self, session)
  File "/home/devil/linux/emesene/emesene/gui/base/ContactList.py", line 79, in **init**
    self.order_by_group = self.session.config.b_order_by_group
  File "/home/devil/linux/emesene/emesene/gui/base/ContactList.py", line 323, in _set_order_by_group
    self.fill()
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/widgets/ContactList.py", line 112, in fill
    gui.ContactList.fill(self, clear)
  File "/home/devil/linux/emesene/emesene/gui/base/ContactList.py", line 549, in fill
    self.add_contact(contact, group)
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/widgets/ContactList.py", line 94, in add_contact
    self._model.add_contact(contact, group)
  File "/home/devil/linux/emesene/emesene/gui/qt4ui/widgets/ContactListModel.py", line 97, in add_contact
    new_contact_item.setData(contact.identifier + 'FLN', Role.UidRole)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by AmiZya** [comment]
Can you tell me how to re-produce this error please?

**Comment by shwangdev** [comment]
*Login WebQQ Session.
*
On Mon, Aug 27, 2012 at 5:06 PM, Mohammed Amine ZYAD <
notifications@github.com> wrote:

> Can you tell me how to re-produce this error please?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emesene/emesene/issues/1484#issuecomment-8050545.

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by shwangdev** [comment]
*But No Error with gtk
*
On Mon, Aug 27, 2012 at 5:07 PM, Xiang Wang wxjeacen@gmail.com wrote:

> *Login WebQQ Session.
> *
> 
> On Mon, Aug 27, 2012 at 5:06 PM, Mohammed Amine ZYAD <
> notifications@github.com> wrote:
> 
> > Can you tell me how to re-produce this error please?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/emesene/emesene/issues/1484#issuecomment-8050545.
> 
> ## 
> 
> _Best Regards~_
> 
> _Xiang Wang_
> 
> _CDC, TrendMicro_

## 

_Best Regards~_

_Xiang Wang_

_CDC, TrendMicro_

**Comment by shwangdev** [comment]
@c10ud ok ,I changed webqq implementation.
