### ISSUE TITLE
TypeError: QDialog.exec_(): first argument of unbound method must have type 'QDialog'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1485]
[19:53:40 ERROR e3.common.Signal] Method called on dead object: ContactList.on_contact_list_ready
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/base/ContactList.py", line 182, in on_contact_list_ready
    self.on_pending_contacts()
  File "/home/andre/emesene/emesene/gui/base/ContactList.py", line 202, in on_pending_contacts
    dialog.contact_added_you(accounts, on_contact_added_you)
  File "/home/andre/emesene/emesene/gui/qt4ui/Dialog.py", line 170, in contact_added_you
    response = dialog.exec_()
  File "/home/andre/emesene/emesene/gui/qt4ui/Dialog.py", line 840, in exec_
    QtGui.QDialog.exec_(self)
TypeError: QDialog.exec_(): first argument of unbound method must have type 'QDialog'

**Comment by c10ud** [comment]
here i have:

```
def exec_(self):
    QtGui.QDialog.exec_(self)
```

**Comment by c10ud** [comment]
(in line 840)

**Comment by c10ud** [comment]
ahhhhh github ate the line
