### ISSUE TITLE
Set changed size during iteration

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1506]
Traceback (most recent call last):
  File "/home/pepe/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 424, in _sb_state_changed
    for handler in list(self._orphaned_handlers):
  File "/usr/lib/python2.7/_weakrefset.py", line 66, in __len__
    return sum(x() is not None for x in self.data)
  File "/usr/lib/python2.7/_weakrefset.py", line 66, in <genexpr>
    return sum(x() is not None for x in self.data)
RuntimeError: Set changed size during iteration

I've no idea how to reproduce it.

**Comment by c10ud** [comment]
https://github.com/emesene/emesene/commit/402708747b72ed9818aabf92490abbc67dc7d8a4

WeakSet papyon implementation looks a little bit different from python's own one. 
We should probably remove papyons and take some extra safety measure when using the WeakSet?

**Comment by c10ud** [comment]
Also, first time ever i see this error, but i saw another orphaned_switchboard thing showed up some days ago (handlers being assigned to wrong switchboard), probably there's some underlying mess due to this weakset thing, or worse...
