### ISSUE TITLE
Can't access "properties"

### ISSUE THREAD

**Issue by BramKaandorp** [emesene/emesene#1515]
When trying to access the preferences window (through the main window as well as the tray icon), nothing happens (on the face of it).

After doing a complete reinstall (including a removal of the folder in .config just to be sure) the following happens in the terminal when starting emesene, logging in and then clicking "properties" in the main menu:

bram@bram-desktop:~$ emesene
[19:32:22 WARNING e3.common.Config] couldn't load config: /home/bram/.config/emesene2/messenger.hotmail.com/user@mailserver.nl/config (no file)
[19:32:22 ERROR e3.common.Signal] Signal handler (Controller.on_login_succeed) error: [Errno 2] Bestand of map bestaat niet: 'plugins'
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), _arg)
  File "/usr/share/emesene/emesene/emesene.py", line 590, in on_login_succeed
    self._setup_plugins()
  File "/usr/share/emesene/emesene/emesene.py", line 572, in _setup_plugins
    plugin_manager.scan_directory('plugins')
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 180, in scan_directory
    for filename in os.listdir(dir_):
OSError: [Errno 2] Bestand of map bestaat niet: 'plugins'
[19:32:23 ERROR papyon.msnp2p.session_manager] Session_id == 0
[19:32:23 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[19:32:23 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/MainMenu.py", line 288, in <lambda>
    lambda *args: handler.on_preferences_selected())
  File "/usr/share/emesene/emesene/gui/base/Handler.py", line 133, in on_preferences_selected
    self.session)
  File "/usr/share/emesene/emesene/extension.py", line 621, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, *args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 492, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(_args, *_kwargs)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 112, in **init**
    self.general = GeneralTab(session)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 1292, in **init**
    'session.config.b_check_for_updates')
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 460, in append_check
    widget = self.create_check(text, property_name)
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 452, in create_check
    widget.set_active(default)
TypeError: an integer is required

I'm at a loss here.

ETA: I changed the email address.

**Comment by Sbte** [comment]
Looks like a packaging error. What OS are you using?

**Comment by Sbte** [comment]
I fixed this bug for future versions of emesene, but my original question still holds, because we need to fix the package you're using.

**Comment by BramKaandorp** [comment]
I use Ubuntu 12.04, specifically the repository "Emesene-team/Emesene-stable".

If it helps even more, I use 64 bit Ubuntu.

**Comment by Sbte** [comment]
This seems to be because all gitignore files were removed, and therefore the plugins folder was empty and apparently removed.

**Comment by BramKaandorp** [comment]
I did this test (the one in the report) from a clean install. How could the gitignore files get removed?

Also (showing my ignorance), what are gitignore files (if it is at all appropriate of me to ask that here)?

**Comment by Sbte** [comment]
It's probably because of a new version of bzr-git they use in launchpad (which we use to create the package). The plugins dir is an empty folder except for a hidden file, which was apparently removed by launchpad and this caused the plugins dir to be removed from the package. There should be a new package available in a minute.

**Comment by Sbte** [comment]
Is it working now?

**Comment by BramKaandorp** [comment]
Sure is. Better than ever in fact.

Thanks again.
