### ISSUE TITLE
Prefs wont open on first launch

### ISSUE THREAD

**Issue by joshf** [emesene/emesene#1529]
```
Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/MainMenu.py", line 288, in <lambda>
    lambda *args: handler.on_preferences_selected())
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/base/Handler.py", line 133, in on_preferences_selected
    self.session)
  File "/Applications/emesene.app/Contents/Resources/emesene/extension.py", line 621, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, *args, **kwargs)
  File "/Applications/emesene.app/Contents/Resources/emesene/extension.py", line 492, in get_and_instantiate
    return category.get_and_instantiate(*args, **kwargs)
  File "/Applications/emesene.app/Contents/Resources/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(*args, **kwargs)
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/Preferences.py", line 147, in __init__
    self.__init_list()
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/Preferences.py", line 262, in __init_list
    self.facebook = Facebook(self.session)
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/Preferences.py", line 1407, in __init__
    'session.config.b_fb_enable_integration')
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/Preferences.py", line 460, in append_check
    widget = self.create_check(text, property_name)
  File "/Applications/emesene.app/Contents/Resources/emesene/gui/gtkui/Preferences.py", line 452, in create_check
    widget.set_active(default)
TypeError: an integer is required
```

**Comment by joshf** [comment]
This isn't fixed for me
