### ISSUE TITLE
improvvise reconnect...close...and...

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1533]
emesene suddenly reconnects, I try to close it and log in I get this error:

``` python
[20:52:26 ERROR papyon.msnp2p.session_manager] Session_id == 0
[21:02:43 WARNING papyon.p2p] Trying to publish an empty MSNObject
[21:03:05 WARNING papyon.p2p] Trying to publish an empty MSNObject
[21:08:14 WARNING papyon.service] Transport Error : Couldn't resolve hostname for "local-bay.contacts.msn.com"
[21:08:14 ERROR papylib.Events] Client got an error handling addressbook: 4 Couldn't resolve hostname for "local-bay.contacts.msn.com"
Exception in thread Thread-14 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/share/emesene2/e3/base/Worker.py", line 184, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

emesene last git version

**Comment by Sbte** [comment]
See #840, but probably also others.

**Comment by c10ud** [comment]
Actually the issue here is that it cannot resolve the local-bay.contacts.msn.com address, and i think it's either a temporary issue or you should use a better DNS.
