### ISSUE TITLE
Discconectig after opening mail through mail icon in emesene 2.12.9

### ISSUE THREAD

**Issue by juanraig** [emesene/emesene#1536]
Hello I have noticed that if I open mail, everything is set to zero (contacts andnumber of mails) and I have to close and start new session. What's wrong?
Thanks

**Comment by Sbte** [comment]
If you run emesene from a terminal, could you paste here what you see? Or if it's really long paste it on pastebin and put a link here.

**Comment by juanraig** [comment]
No handlers could be found for logger "emesene.e3.common.DBus"
D:\Program Files (x86)\emesene2.\Crypto\Util\randpool.py:40:
RandomPool_Depreca
tionWarning: This application uses RandomPool, which is BROKEN in older
releases
.  See http://www.pycrypto.org/randpool-broken
D:\Program Files (x86)\emesene2.\gui\gtkui__init__.py:102: Warning:
g_object_s
et_qdata: assertion `G_IS_OBJECT (object)' failed

2012/10/6 Sven notifications@github.com

**Comment by juanraig** [comment]
Problem persists in Windows 7 Ultimate 64 bits, has somebody found the same problem. How can it be fixed or are you preparing new release. Thanks and apologizes.

**Comment by Sbte** [comment]
Not fixed yet I think. If you're using the msn session, it could possibly be a duplicate of #1534

**Comment by Sbte** [comment]
Ok, it excepts in calling _on_endpoint_added

**Comment by juanraig** [comment]
Sorry but it keeps on with the issue, I have checked it and after closing hotmail account emesene's contacts a message numbers revert to 0 (zero) as disconnected

**Comment by Sbte** [comment]
Yes, you need to disable it in hotmail if that's possible. If it's not then the only way to solve it will still be to reconnect with emesene. Hotmail forces emesene to disconnect.

**Comment by Sbte** [comment]
I just removed all unrelated comments. If you need further assistance, please post it on the google group or in our IRC channel: #emesene on freenode.net. This tracker is for solving bugs, not for questions from users, sorry.

The problem here seems to be that the contact list loads twice, but the second time with no contacts. It also seems that papyon stays connected. Maybe we should be disconnecting emesene because we're forced to by the other endpoint. I don't really understand yet what's going on. 

Anyhow, it's reproducible under linux too:

```
...
[21:53:37 INFO papyon.service.address_book] [???] Received sync request:
...contacts: ['******']
...groups: ['A-blka', 'A-test']
...memberships: ['**** A-Allow']
[21:53:37 DEBUG papyon.transport] >>> ADL 24 118
    [payload]
[21:53:37 DEBUG papyon.transport] <<< ADL 24 OK
[21:53:37 INFO papyon.service.content_roaming] Synchronizing
[21:53:37 DEBUG papyon.transport] >>> BLP 25 BL
[21:53:37 DEBUG papyon.transport] >>> PNG
[21:53:37 DEBUG papyon.transport] >>> UUX 26 71
    [payload]
[21:53:37 DEBUG papyon.transport] >>> UUX 27 129
    [payload]
[21:53:37 DEBUG pluginmanager] Imported plugins: gnome_session_manager, typing_notification, contact_status_history_combo, youtube, idle_status, cmdline, music, last_said, snarl_notifications, ye_old_status_combo
[21:53:37 DEBUG pluginmanager] Imported plugins: gnome_session_manager, typing_notification, contact_status_history_combo, youtube, idle_status, cmdline, music, last_said, snarl_notifications, ye_old_status_combo
[21:53:37 INFO pluginmanager] starting plugin "last_said"
[21:53:38 DEBUG papyon.transport] <<< BLP 25 BL
[21:53:38 ERROR e3.common.Signal] Method called on dead object: NoneType._on_endpoint_added
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene-dev/emesene/WeakMethod.py", line 29, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object
[21:53:38 DEBUG papyon.transport] <<< QNG 42
[21:53:38 DEBUG papyon.transport] <<< UUX 26 0
[21:53:38 DEBUG papyon.transport] <<< UUX 27 0
[21:53:38 DEBUG papyon.service] >>> POST /RST.srf HTTP/1.0
...
```

**Comment by juanraig** [comment]
What I have noticed is that if I am available (green) it happens else in other state not, checked with hidden and inactive.

**Comment by KinG-InFeT** [comment]
INFO My LOG: http://sprunge.us/ObaO

**Comment by moopoint-zz** [comment]
I also got this conflict with hotmail's webmail. I often have to restart Emesene after logging in to hotmail.

Windows 7 (32bit), Firefox 16.0.2, Emesene 2.12.9.
