### ISSUE TITLE
can't open preference window

### ISSUE THREAD

**Issue by planykao** [emesene/emesene#1540]
Traceback (most recent call last):
  File "/usr/share/emesene/gui/gtkui/MainMenu.py", line 288, in <lambda>
    lambda _args: handler.on_preferences_selected())
  File "/usr/share/emesene/gui/base/Handler.py", line 133, in on_preferences_selected
    self.session)
  File "/usr/share/emesene/extension.py", line 621, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, *args, *_kwargs)
  File "/usr/share/emesene/extension.py", line 492, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/share/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(_args, *_kwargs)
  File "/usr/share/emesene/gui/gtkui/Preferences.py", line 112, in **init**
    self.general = GeneralTab(session)
  File "/usr/share/emesene/gui/gtkui/Preferences.py", line 1292, in **init**
    'session.config.b_check_for_updates')
  File "/usr/share/emesene/gui/gtkui/Preferences.py", line 460, in append_check
    widget = self.create_check(text, property_name)
  File "/usr/share/emesene/gui/gtkui/Preferences.py", line 452, in create_check
    widget.set_active(default)
TypeError: an integer is required

disro: Archlinux
kernel: 3.6.2-1-ARCH 32bit
python2: 2.7
python3: 3.2

**Comment by planykao** [comment]
sorry, i find the solution.
https://github.com/Sbte/emesene/commit/eb1a99a651d61708ccbdf9e635977f84ee60711d
