### ISSUE TITLE
ERROR NotificationObject] Error calling config callback 

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1543]
``` python

[20:29:41 WARNING gui.base.ImageThemes] tema di immagini incompleto
[20:30:02 ERROR papyon.msnp2p.session_manager] Session_id == 0
[20:30:02 ERROR papyon.msnp2p.session_manager] Session_id == 0
[20:30:02 ERROR papyon.msnp2p.session_manager] Session_id == 0
/usr/share/emesene2/gui/gtkui/__init__.py:106: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[20:30:06 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[20:30:06 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[20:30:06 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[20:30:06 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[20:30:06 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[20:30:06 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
/usr/share/emesene2/gui/gtkui/Renderers.py:707: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  if model.get_value(iter, 0) == image:
[20:30:45 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 3f ab ff 54 00 00 00 00 00 00 00 00
df 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
97 6d 4e 54 2a 60 a4 01 df 02 00 00 00 00 00 00
START /usr/lib/firefox/firefox "http://emesene.github.com/emesene-pages/hotmail?&&https://login.live.com/ppsecure/sha1auth.srf?1040?&&nonce=VK72e5QmfYH2A1rRl2CDZ1hYs%2FZxmRjQ&bver=4&js=yes&rru=%2Fcgi%2Dbin%2FHoTMaiL&da=%3CEncryptedData+xmlns%3D%22http%3A%2F%2Fwww%2Ew3%2Eorg%2F2001%2F04%2Fxmlenc%23%22Id%3D%22BinaryDAToken0%22+Type%3D%22http%3A%2F%2Fwww%2Ew3%2Eorg%2F2001%2F04%2Fxmlenc%23Element%22%3E%3CEncryptionMethodAlgorithm%3D%22http%3A%2F%2Fwww%2Ew3%2Eorg%2F2001%2F04%2Fxmlenc%23tripledes%2Dcbc%22%2F%3E%3Cds%3AKeyInfo+xmlns%3Ads%3D%22http%3A%2F%2Fwww%2Ew3%2Eorg%2F2000%2F09%2Fxmldsig%23%22%3E%3Cds%3AKeyName%3Ehttp%3A%2F%2FPassport%2ENET%2FSTS%3C%2Fds%3AKeyName%3E%3C%2Fds%3AKeyInfo%3E%3CCipherData%3E%3CCipherValue%3ECuhdJF7ajn9QeKXHsoFqsvAxSq5Gs65ZInR9JgPRD09wL5J7sCfgfxpcPxctiTmEhrtZnSDcL9%2FAik%2B%2FGVTq0XuvsHdGIYxjJBPE3POh6fDVLbZqTSaCV5PswPbbMBhsiendxv22YWhS8vm86iAbXANh18im6mwDhhFScpBus%2Bbpy%2FGSfjzwKt%2BQEBi283xC3eqGf%2Bq0gKEaYspZ7yEebI%2Br5QHzLUPr4eE4ECR1IYiCJwMr965GNdpFqOniNGJpxMAHBLJYEoaEl4Nmm2AqkHt6oyCITuV%2FkKWVwJwiLvqntffy4CuAMBuE47Mct8W%2Fs37sfNT2O6n7laPWarC89Como1lbEkHAMdfY8MFj31PegwsKBilCPd%2FFbixIrK4bqKuhVuyStmTcKD7HGsUFOmG04V9Qr5S84F3b8%2B1DhJZTcMbfeLOX4pp4ZH%2FU7PtKGIOSWbIA7u%2B82aos%2BXck5h9SXnMF4AjagtMyAbJ4DuNt%2B6kIGtbvl0tPk%2FcZHQLgSU9ODBAdKXuOYFtloDlOjG48GpJFUgvXUSNTT2n6n32l0yJP6zl2yfd3nH%2Fa1phbfFucIRMmIAT7K6meBhxxazY%2BSnNPqbtO8945wdC85WOY%3C%2FCipherValue%3E%3C%2FCipherData%3E%3C%2FEncryptedData%3E&id=2&ct=1351281885&ru=%2Fcgi%2Dbin%2FHoTMaiL&svc=mail&sru=%2Fcgi%2Dbin%2FHoTMaiL&pl=%3Fid%3D2&hash=05hMOgF7c4GKjxzI7s2n9M375t0%3D"
[22:05:33 WARNING gui.base.ImageThemes] tema di immagini incompleto
Traceback (most recent call last):
  File "/usr/share/emesene2/gui/gtkui/Renderers.py", line 718, in animation_timeout
    model.foreach(self.func, (image, tree))
AttributeError: 'NoneType' object has no attribute 'foreach'
[22:06:14 ERROR e3.common.Signal] Method called on dead object: NoneType._on_endpoint_added
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 29, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object
[22:06:57 WARNING papyon.p2p] Trying to publish an empty MSNObject
[22:06:57 WARNING gui.base.ImageThemes] tema di immagini incompleto
[22:06:57 ERROR NotificationObject] Error calling config callback <weakref at 0x9a599dc; to 'function' at 0x8dea994 (_on_notification_gui_changed)> for notificationGUI
Traceback (most recent call last):
  File "/usr/share/emesene2/NotificationObject.py", line 46, in notify_change
    callback(value)
  File "/usr/share/emesene2/WeakMethod.py", line 29, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object
[22:06:57 ERROR e3.common.Signal] Method called on dead object: Controller.on_login_succeed
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 31, in __call__
    self.f()(self.c(), *arg)
  File "/usr/share/emesene2/emesene.py", line 589, in on_login_succeed
    self.draw_main_screen()
  File "/usr/share/emesene2/emesene.py", line 495, in draw_main_screen
    self.session.set_default_extensions_from_config()
  File "/usr/share/emesene2/e3/base/Session.py", line 170, in set_default_extensions_from_config
    extension.set_default_by_id(cat_name, ext_id)
  File "/usr/share/emesene2/extension.py", line 645, in set_default_by_id
    return extension_manager.set_default_by_id(category_name, id_)
  File "/usr/share/emesene2/extension.py", line 527, in set_default_by_id
    self.notify_change(category_name, new_ext)
  File "/usr/share/emesene2/NotificationObject.py", line 50, in notify_change
    raise ex
TypeError: Method called on dead object
[22:06:58 WARNING papyon.p2p] Trying to publish an empty MSNObject
[22:07:05 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 c3 5b cd b0 00 00 00 00 00 00 00 00
de 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
aa fe 0e 20 c9 b4 86 42 de 02 00 00 00 00 00 00
[22:07:05 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 6d 3c 43 df 00 00 00 00 00 00 00 00
de 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
aa de ac 60 ca b4 86 42 de 02 00 00 00 00 00 00
[22:08:18 WARNING papyon.p2p] Trying to publish an empty MSNObject
[22:08:18 WARNING gui.base.ImageThemes] tema di immagini incompleto
[22:08:18 ERROR NotificationObject] Error calling config callback <weakref at 0x9a599dc; to 'function' at 0x8dea994 (_on_notification_gui_changed)> for notificationGUI
Traceback (most recent call last):
  File "/usr/share/emesene2/NotificationObject.py", line 46, in notify_change
    callback(value)
  File "/usr/share/emesene2/WeakMethod.py", line 29, in __call__
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object
[22:08:18 ERROR e3.common.Signal] Method called on dead object: Controller.on_login_succeed
Traceback (most recent call last):
  File "/usr/share/emesene2/e3/common/Signal.py", line 65, in emit
    if callback(*args, **kwargs) == False:
  File "/usr/share/emesene2/WeakMethod.py", line 31, in __call__
    self.f()(self.c(), *arg)
  File "/usr/share/emesene2/emesene.py", line 589, in on_login_succeed
    self.draw_main_screen()
  File "/usr/share/emesene2/emesene.py", line 495, in draw_main_screen
    self.session.set_default_extensions_from_config()
  File "/usr/share/emesene2/e3/base/Session.py", line 170, in set_default_extensions_from_config
    extension.set_default_by_id(cat_name, ext_id)
  File "/usr/share/emesene2/extension.py", line 645, in set_default_by_id
    return extension_manager.set_default_by_id(category_name, id_)
  File "/usr/share/emesene2/extension.py", line 527, in set_default_by_id
    self.notify_change(category_name, new_ext)
  File "/usr/share/emesene2/NotificationObject.py", line 50, in notify_change
    raise ex
TypeError: Method called on dead object
[22:08:19 WARNING papyon.p2p] Trying to publish an empty MSNObject
[22:08:19 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 0c bb c9 ac 00 00 00 00 00 00 00 00
df 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
a6 9f 50 2a 92 fe 16 01 df 02 00 00 00 00 00 00
```

**Comment by KinG-InFeT** [comment]
[22:08:18 ERROR NotificationObject] Error calling config callback <weakref at 0x9a599dc; to 'function' at 0x8dea994 (_on_notification_gui_changed)> for notificationGUI

**Comment by Sbte** [comment]
This is again the same bug as #1534. You performed the exact same actions and you get the exact same logs. Please stop reporting duplicates.
