### ISSUE TITLE
TrayIcon not work

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1557]
LOG: http://sprunge.us/iRQY

I try to click on the icon to open the main window is in exception, but if I click with the right mouse button and visualize the main windows and then try to tap again on the trayicon, it continues to operate as if freed.

**Comment by Sbte** [comment]
This method is deprecated and should be removed. Not sure if we have a good alternative.

**Comment by pepeleproso** [comment]
we could try to change the icon when there's a new message, instead of the blink icon.

**Comment by KinG-InFeT** [comment]
you could insert an image of type gif? so you would in any case an animated icon but without using code.

**Comment by pepeleproso** [comment]
I think I'll use this http://developer.gnome.org/gtk3/3.2/GtkNumerableIcon.html
So instead of a blink icon we get a number of unread messages on gtk3.

**Comment by pepeleproso** [comment]
I make it use NumerableIcon on gtk3. Patch need testing to make sure counting works fine.

**Comment by Sbte** [comment]
If it works, we could also extend this to the Indicator. Or maybe make counting a generic thing and use the same structure as in the messaging menu extension.

**Comment by Sbte** [comment]
Now I think of it, the unity launcher also already has this.

**Comment by pepeleproso** [comment]
Now I see the code there and is better than mine. I'll try to reuse it. Indicator is a bit more complicated if we want to support this because it uses icon names and icon path. We need to create the NumericIcon, save it and then use it. But it'll be really slow

**Comment by pepeleproso** [comment]
I need someone who can test this patch https://github.com/pepeleproso/emesene/commit/274dd4aa0c73d2491d5b63705292a29a7f5b26ee on unity to be sure it's working.

**Comment by c10ud** [comment]
[13:28:29 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in __call__
    self.f()(self.c(), _arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'
[13:28:29 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'
[13:28:29 ERROR e3.common.Signal] Method called on dead object: MessagingMenu._on_conv_message
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/MessagingMenu.py", line 99, in _on_conv_message
    contact.nick), account, icid=icid)
  File "/home/riccardo/msn/emesene/emesene/gui/common/MessagingMenu.py", line 146, in _create_indicator
    ind.set_property_time("time", time.time())
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
TypeError: Expected GLib.TimeVal, but got StructMeta
[13:28:29 ERROR e3.common.Signal] Method called on dead object: MessagingMenu._on_conv_message
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/MessagingMenu.py", line 99, in _on_conv_message
    contact.nick), account, icid=icid)
  File "/home/riccardo/msn/emesene/emesene/gui/common/MessagingMenu.py", line 146, in _create_indicator
    ind.set_property_time("time", time.time())
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(_args, *_kwargs)
TypeError: Expected GLib.TimeVal, but got StructMeta
[13:28:30 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'
[13:28:30 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'
[13:28:31 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'
[13:28:31 ERROR e3.common.Signal] Signal handler (UnityLauncher._on_conv_message) error: 'NoneType' object has no attribute 'get_conversation_manager'
Traceback (most recent call last):
  File "/home/riccardo/msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, **kwargs) == False:
  File "/home/riccardo/msn/emesene/emesene/WeakMethod.py", line 31, in **call**
    self.f()(self.c(), *arg)
  File "/home/riccardo/msn/emesene/emesene/gui/common/NumerableTrayIcon.py", line 39, in _on_conv_message
    conv_manager = self.session.get_conversation_manager(cid, [account])
AttributeError: 'NoneType' object has no attribute 'get_conversation_manager'

**Comment by pepeleproso** [comment]
This is finished so i'm closing this.
