### ISSUE TITLE
Fedora 17 Cannot open emesene

### ISSUE THREAD

**Issue by Reap3RGHS** [emesene/emesene#1559]
When i run emesen i getting this error: 
[root@Reap3R ]# emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No module named Crypto.Util.randpool
Traceback (most recent call last):
  File "/usr/bin/emesene", line 30, in <module>
    from emesene import emesene
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 108, in <module>
    from e3 import papylib
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/**init**.py", line 21, in <module>
    from Session import Session
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Session.py", line 22, in <module>
    from Worker import Worker
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 65, in <module>
    from PapyEvents import *
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/PapyEvents.py", line 23, in <module>
    import papyon.event
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
    from client import *
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
    import papyon.profile as profile
AttributeError: 'module' object has no attribute 'profile'
[root@Reap3R ]#

**Comment by jamesaxl** [comment]
why are you running emesne in mode root, try to run it  1st as simple user

**Comment by Reap3RGHS** [comment]
Ok now i am running it as simple user and again >> 
bash-4.2$ emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No module named Crypto.Util.randpool
Traceback (most recent call last):
  File "/usr/bin/emesene", line 30, in <module>
    from emesene import emesene
  File "/usr/lib/python2.7/site-packages/emesene/emesene.py", line 108,
in <module>
    from e3 import papylib
  File
"/usr/lib/python2.7/site-packages/emesene/e3/papylib/**init**.py", line
21, in <module>
    from Session import Session
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Session.py",
line 22, in <module>
    from Worker import Worker
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py",
line 65, in <module>
    from PapyEvents import *
  File
"/usr/lib/python2.7/site-packages/emesene/e3/papylib/PapyEvents.py",
line 23, in <module>
    import papyon.event
  File
"/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
    from client import *
  File
"/usr/lib/python2.7/site-packages/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
    import papyon.profile as profile
AttributeError: 'module' object has no attribute 'profile'

**Comment by Sbte** [comment]
Do you have the papyon package installed? If this is the case, you should uninstall it.

**Comment by Reap3RGHS** [comment]
No,

# yum remove papyon

Loaded plugins: langpacks, presto, refresh-packagekit
No Match for argument: papyon
No Packages marked for removal
