### ISSUE TITLE
IconView should skip non-image files

### ISSUE THREAD

**Issue by GVisconti84** [emesene/emesene#156]
```
<class 'glib.GError'>
Unhandled exception in thread started by <bound method IconView.fill of <IconView object at 0xa001824 (GtkHBox at 0xa120ec8)>>
Traceback (most recent call last):
  File "/home/fastfading/src/emesene/emesene/gui/gtkui/IconView.py", line 60, in fill
    self.add_picture(os.path.join(search_path, path))
  File "/home/fastfading/src/emesene/emesene/gui/gtkui/IconView.py", line 129, in add_picture
    self.model.append([pixbuf, path])
UnboundLocalError: local variable 'pixbuf' referenced before assignment
```

Steps to reproduce:
1. go to `~/.config/emesene2/messenger.hotmail.com/[account]/avatars` with your preferred filemanager
2. create a directory
3. start emesene2
4. click on your display picture

**Comment by c10ud** [comment]
Fix directories present in user avatar dir. Closed by 7912b7d16ef18fe4ad3510e15e2104ca0067233e
