### ISSUE TITLE
strange behavior of plugin management

### ISSUE THREAD

**Issue by pengshao** [emesene/emesene#1572]
Hi, thanks for reading. I am using emesene 2.12.9 in KDE/Arch linux ( a recent clean install) and I noticed that it has the following strange behaviors in Preference-->Plugins section
1. After the installation, by default emesene does not creat /usr/share/emesene/plugins folder. And without this folder, if you click Preference Menu, the preference window will not show up at all
2. After I manually creat the /usr/share/emesene/plugins folder, I can open the Preference window now. However, if I go to plugins section and hit the refresh button then install the plugs I need (I will use "Idle Status" as an example), there are some really weird things happening:

a. After I click "download" button, nothing happened, I could not see "Idle Status" plugin installed

b. Restart emesene and go to Plugins section, there was only one available plugin left, "Idle Status". However I still have no way to install it--clicking download triggered nothing.

c. Restart emesene again, then now there is NO available plugins at all. Clicking "Refresh" button leads to nothing

d. To make things even more confusing: if I remove .config/emesene2 and emeseme and make a clean install of emesene, there is certain possibility that if I go directly to "Plugins" section then find NO available plugins at all, just like step c.

Then I managed to download the plugins from git source and put them under .config/emesene/plugins folder (I had to manually creat this folder if I run into condition d).  Emesene will show these plugins installed. However, not all of them work and if I check all of them to enable them, after an emesene restart, only part of them remain enabled and the others turn to be disabled by some unknown reason.

I don't think this is likely an Arch issue since I was using emesene on a gentoo machine for years before and I remember I had these issues during the past few month. I have a very stable internet connection so I didn't suspect it.

If I run emesene from a terminal, then the moment when I click "Refresh" button in the Plugins section the terminal will dump out the following error message:

```
[05:52:05 ERROR gtkui.utils] 'tree'
Traceback (most recent call last):
  File "/usr/share/emesene/gui/gtkui/utils.py", line 283, in run
    result = (True, self.func(*self.args, **self.kwargs))
  File "/usr/share/emesene/gui/gtkui/ExtensionList.py", line 276, in update
    current_collection.fetch(refresh)
  File "/usr/share/emesene/e3/common/Collections.py", line 152, in fetch
    for i, item in enumerate(self._tree['tree']):
KeyError: 'tree'
```

It is worthy to point out that I also tried the git version of emesene and the above problems remain.

Thank you!

**Comment by Sbte** [comment]
Part 1 should be fixed in the git version.

About part 2 I really don't have a clue. Everything (updating, downloading, removing) works perfectly fine here.
