### ISSUE TITLE
https://escargot.log1p.xyz/

### ISSUE THREAD

**Issue by FelipeAzambuja** [emesene/emesene#1592]
Make suport for 
https://escargot.log1p.xyz/

**Comment by ghost** [comment]
Please do.

**Comment by maop** [comment]
now is https://escargot.chat/

**Comment by inukaze** [comment]
I need the same, and if possible you can adapt the client for python3, under slackware 15.0 i can't find the way to solve the follow output

`python emesene.py `

> error: pygi compat not found
> Traceback (most recent call last):
>   File "emesene.py", line 122, in <module>
>     from e3 import papylib
>   File "/home/inukaze/Desktop/src/emesene/build/lib/emesene/e3/papylib/__init__.py", line 21, in <module>
>     from Session import Session
>   File "/home/inukaze/Desktop/src/emesene/build/lib/emesene/e3/papylib/Session.py", line 22, in <module>
>     from Worker import Worker
>   File "/home/inukaze/Desktop/src/emesene/build/lib/emesene/e3/papylib/Worker.py", line 705
> SyntaxError: Non-ASCII character '\xe2' in file /home/inukaze/Desktop/src/emesene/build/lib/emesene/e3/papylib/Worker.py on line 705, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

that server is the unique functional server of MSN/Windows Live Messenger. i need a lightweight client can work with the servers of https://escargot.chat/
