### ISSUE TITLE
Gray Conversation Window Problem

### ISSUE THREAD

**Issue by adrielparedes** [emesene/emesene#179]
When i tryied to start a new conversation, i only get a gray window...
The Stack Trace...

TypeError: **get_display_picture_errback() takes exactly 2 arguments (1 given)
TypeError: can't convert return value to desired type
[17:58:57 WARNING e3.common.Signal] Signal handler (_on_contact_selected._on_contact_selected) error: error de contexto para el lenguaje: es_AR.utf8
Traceback (most recent call last):
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/e3/common/Signal.py", line 63, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/e3/common/Signal.py", line 110, in __call**
    apply(self.f, (self.c(),) + arg)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/gui/gtkui/MainWindow.py", line 144, in _on_contact_selected
    self.on_new_conversation(cid, [contact.account], False)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/emesene.py", line 497, in on_new_conversation
    conversation = self.conversations.new_conversation(cid, members)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/gui/base/ConversationManager.py", line 148, in new_conversation
    conversation = self.add_new_conversation(self.session, cid, members)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/gui/gtkui/ConversationManager.py", line 188, in add_new_conversation
    conversation = Conversation(self.session, cid, self.update_window, None, members)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/gui/gtkui/Conversation.py", line 51, in __init__
    self.cycle_history)
  File "/home/adriel/workspaces/emesene/emesene2/src/emesene/emesene/gui/gtkui/TextBox.py", line 162, in **init**
    self.spell_checker = gtkspell.Spell(self._textbox)

greets!

**Comment by c10ud** [comment]
can you try updating?

**Comment by c10ud** [comment]
Catch everything when initializing spell checker. Closed by 953197674ba3b6e12a36774cd9d081b7828a861f
