### ISSUE TITLE
Disconects Makes Emesene unuseable

### ISSUE THREAD

**Issue by NickCis** [emesene/emesene#2]
When you disconnect the emesene, the windows disappears. And if you re open it from the systray icon, a blank window appears, making it unuseable. This either happends disconnecting from "File --- Desconectar" or from the menu of the systray icon. (Note: The emesene disconnects correctly but if you want to continue using you will have to reopen it). In addition, you can't close the emesene, and the systray icon continuo existing.
Screen of the bug: http://i.imagehost.org/view/0070/disconnect_bug

Traceback (most recent call last):
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/gui/gtkui/MainMenu.py", line 77, in <lambda>
    lambda *args: self.handler.on_disconnect_selected())
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/gui/base/Handler.py", line 40, in on_disconnect_selected
    self.on_disconnect()
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/gui/gtkui/MainWindow.py", line 205, in on_disconnect
    self.on_disconnect_cb()
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/emesene.py", line 471, in on_disconnect
    self.start()
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/emesene.py", line 461, in start
    self.config.session, proxy, use_http, self.config.session)
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/gui/gtkui/Window.py", line 55, in go_login
    proxy, use_http, session_id)
  File "/home/newpc/Emesene/emesene-emesene-567115e/mesinyer/gui/gtkui/Login.py", line 84, in **init**
    self.throbber = gtk.image_new_from_animation(th_pix)
TypeError: image_new_from_animation() argument 1 must be gtk.gdk.PixbufAnimation, not None

**Comment by marianoguerra** [comment]
added option to group offline contacts in a special group closed by 64dd9da078aff5b513dbe5f9bc294013e9d79a5f

**Comment by c10ud** [comment]
cando fixed that (?)

**Comment by cando** [comment]
i don't have this problem....i think it's fixed...
