### ISSUE TITLE
Call Manager causes repeated messages

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#234]
A contact attempted to initiate a call with me, which opened the Call Manager window.

This causes all subsequent messages to be repeated 

<pre>
X: Me hiciste un video call? @ 21:33    

Y: accidentalmente @ 21:33
Y: accidentalmente 21:33
</pre>

Also, this traceback may or not be related (was dumped a minute afterwards):

<pre><code>
Traceback (most recent call last):
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/sip/core.py", line 268, in _on_request_received
    handler(request)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/sip/core.py", line 323, in _handle_cancel_request
    if type(transaction) is SIPClientTransaction:
NameError: global name 'SIPClientTransaction' is not defined
[21:35:33 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49e5-95C3-F126696BDBF6}
Traceback (most recent call last):
  File "/home/ancanus/Programs/emesene/emesene/gui/gtkui/MessagingMenu.py", line 187, in _display
    if self.r_indicator_dict[conv.cid] is not None:
UnboundLocalError: local variable 'conv' referenced before assignment
Traceback (most recent call last):
  File "/home/ancanus/Programs/emesene/emesene/gui/gtkui/MessagingMenu.py", line 177, in _display
    cid = self.indicator_dict[indicator]
KeyError: indicate.Indicator object at 0xb22d824 (IndicateIndicator at 0xb689cf0)

</code></pre>

**Comment by c10ud** [comment]
No call invites, closed by dccd789e2947a9fd9c87e9cf5d769fb2a695fd32

**Comment by c10ud** [comment]
please open another issue for the indicator
