### ISSUE TITLE
Pluginmanager fails when Emesene is on /usr/share/pyshared/

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#236]
My Ubuntu package installs Emesene on /usr/share/pyshared/, running from there I get this error on start:

```
[16:40:33 WARNING pluginmanager] error importing "ye_old_status_combo": No module named ye_old_status_combo
[16:40:33 WARNING pluginmanager] error importing "music": No module named music
Traceback (most recent call last):
  File "/usr/share/pyshared/emesene/e3/common/Signal.py", line 64, in emit
if callback(*args, **kwargs) == False:
  File "/usr/share/pyshared/emesene/e3/common/Signal.py", line 111, in __call__
apply(self.f, (self.c(),) + arg)
  File "/usr/share/pyshared/emesene/emesene.py", line 404, in on_login_succeed
for plugin in self.session.config.l_active_plugins:
TypeError: 'NoneType' object is not iterable
```

Launching Emesene with:
    /usr/share/pyshared/emesene/emesene

Regards!!

**Comment by EibrielInv** [comment]
related with:
https://github.com/emesene/emesene/issues#issue/270
