### ISSUE TITLE
messaging menu exception

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#24]
Traceback (most recent call last):
  File "/home/riky/msn/emesene2/mesinyer/e3/common/Signals.py", line 26, in _handle_events
    signal.emit(_event.args)
  File "/home/riky/msn/emesene2/mesinyer/e3/common/Signal.py", line 50, in emit
    if callback(_args, **kwargs) == False:
  File "/home/riky/msn/emesene2/mesinyer/gui/gtkui/MessagingMenu.py", line 98, in _on_message_read
    if conv.cid in self.r_indicator_dict.keys():
AttributeError: 'NoneType' object has no attribute 'cid'

mmm possible steps to reproduce it:

-> emesene2 starts conversation with buddy
-> send messages from both parties
-> send a message to emesene2, and close emesene2 conversation window (unfocused) directly

**Comment by cando** [comment]
i'm trying but i can't reproduce....

**Comment by c10ud** [comment]
this seems gone, i'll reopen if it pops up again
