### ISSUE TITLE
Messages are not being sent: affects some contacts only

### ISSUE THREAD

**Issue by Ancanus** [emesene/emesene#248]
My observations are as follows:

There are three contacts in my list that I've been sending messages to and they do not receive them. I confirm this by logging to pidgin and asking them if they received any messages.
It is worth noting that these three contacts all have in common that they are the only ones whose profile picture is not being retrieved either (it shows the default emesene picture)

From the Debug menu:

<pre>
<code>
(18:57:15) papyon.msnp2p.transport.switchboard:>>> TLPv2 chunk 0x3865283f: blob 0, ACK 0x1fc6c9ea, RAK, SYN,
(18:57:15) papyon.transport:>>> MSG 6 D 244
    P2P-Src: 'xxx@hotmail.com;{f73885c2-ec21-4561-9be7-756cca27b3e6}'\r\n
    P2P-Dest: 'xxx@MSN.com;{c0f92133-1e6b-43b0-9fd5-43f50957feee}'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (28 bytes)]
(18:57:15) papyon.msnp2p.transport:Transport is not ready to send, bail out
(18:57:15) papyon.msnp2p.transport:Transport is not ready to send, bail out
(18:57:15) papyon.msnp2p.transport:Transport is not ready to send, bail out
(18:57:16) papyon.transport: NAK 6
(18:57:16) papyon.msnp2p.transport.switchboard:Received error 1 (type=4)
(18:57:16) papylib.Events:Error sending message: 4 1
</code>
</pre>

**Comment by Sandres** [comment]
same here :-/

**Comment by c10ud** [comment]
can you ask your contacts which client are they using? also, a longer debug would be better, thanks

**Comment by c10ud** [comment]
also: bumped papyon version, update and try again

**Comment by Ancanus** [comment]
I updated. Tried again and this trace occurred while in gdb:

<pre>
<code>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/Worker.py", line 129, in run
    self._process_action(action)
  File "/home/ancanus/Programs/emesene/emesene/e3/base/Worker.py", line 177, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/Worker.py", line 1123, in _handle_action_send_message
    papyconversation.send_text_message(msg)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/conversation.py", line 337, in send_text_message
    self._send_message_ex(content_type, body, headers, callback)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/conversation.py", line 365, in _send_message_ex
    return self._send_message(message, callback, errback)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/conversation.py", line 490, in _send_message
    callback=callback, errback=errback)
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 108, in _send_message
    self._process_pending_queues()
  File "/home/ancanus/Programs/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 240, in _process_pending_queues
    self._delivery_callbacks[transaction_id] = (None, errback)
UnboundLocalError: local variable 'transaction_id' referenced before assignment
</code>
</pre>


Their display picture is not being retrieved either.

**Comment by c10ud** [comment]
updated too fast :p, get back in track because that is a 0day issue that has been fixed by papyon mantainer as soon as i told him...the commit is the same, but he fixed that line like...10mins ago

**Comment by Sbte** [comment]
I updated this morning, and apparently, only the first message is being sent. So emesene is basically unusable

**Comment by c10ud** [comment]
issues cleanup.
