### ISSUE TITLE
conversation exception

### ISSUE THREAD

**Issue by ivan25** [emesene/emesene#25]
During a dummy session i get this:

Traceback (most recent call last):
  File "/home/ivan/SVN/emesene2/mesinyer/e3/common/Signals.py", line 26, in _handle_events
    signal.emit(_event.args)
  File "/home/ivan/SVN/emesene2/mesinyer/e3/common/Signal.py", line 50, in emit
    if callback(_args, **kwargs) == False:
TypeError: _on_message() takes exactly 5 arguments (4 given)

steps to reproduce:
- change from adium output to text output and when you send a message there will be no more clone answer
  (even if once i get this even with adium output)

**Comment by marianoguerra** [comment]
update and try again, it worked for me

**Comment by ivan25** [comment]
yes, now it works
