### ISSUE TITLE
'transaction_id' referenced before assignment -> after Papyon 0.5.4

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#253]
Now, every time I send a message, the same first message is send.

EDIT: Papyon 0.5.4

Error:

```
[20:44:09 DEBUG papyon.transport] >>> MSG 3 N 160
    X-MMS-IM-Format: 'FN=Sans; EF=; CO=000000; CS=1; PF=00'\r\n
    Content-Type: 'text/plain; charset=utf-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    Hola!! Anda? jejejje
Traceback (most recent call last):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 80, in <lambda>
    lambda sb, pspec: self.__on_user_inviting_changed()))
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 166, in __on_user_inviting_changed
    self._process_pending_queues()
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 240, in _process_pending_queues
    self._delivery_callbacks[transaction_id] = (None, errback)
UnboundLocalError: local variable 'transaction_id' referenced before assignment
```

Regards!!

**Comment by EibrielInv** [comment]
Works now :)
