### ISSUE TITLE
[Papyon] __common_errback() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#254]
Hi people!!

```
[23:22:53 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[23:22:54 DEBUG papyon.service] >>> GET /y1pRJ3EnUUs5vNH_TyAvseRat1UKsWLMC50aRTvfskXg_P3MEbSfl6Zgz1nty8s    VWlNztUP5K7z1ws HTTP/1.0
Content-Length: 0
Proxy-Connection: Keep-Alive
Host: byfiles.storage.msn.com:80
Accept: */*
User-Agent: gnet/0.1 (Linux x86_64)
Connection: Keep-Alive


[23:22:54 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
Traceback (most recent call last):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
TypeError: __common_errback() takes at least 3 arguments (2 given)
```

Regards!!!

**Comment by c10ud** [comment]
are you having this with 0.5.4?

**Comment by EibrielInv** [comment]
Yep.

**Comment by c10ud** [comment]
fix your profile through preferences-live messenger and follow the instructions, meanwhile, i'll notify papyon-devs

**Comment by c10ud** [comment]
issues cleanup.

**Comment by EibrielInv** [comment]
This issue still exists...

```
Traceback (most recent call last):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene2/emesene-emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
TypeError: __common_errback() takes at least 3 arguments (2 given)
```

TypeError: __common_errback() takes at least 3 arguments (2 given)

**Comment by c10ud** [comment]
did you fix your profile? i think you didn't

**Comment by EibrielInv** [comment]
I have fixed my profile (uploaded a image) some time ago, but now I've changed the image again after chenge my personal status from the web (a couple days back) and now works :D
I see the image, my nick and status now.

Regards!
