### ISSUE TITLE
keyerror: Location

### ISSUE THREAD

**Issue by Zincr0** [emesene/emesene#261]
No contact list loaded and not actually conected:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/pymodules/python2.6/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/pymodules/python2.6/papyon/p2p.py", line 179, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/pymodules/python2.6/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/pymodules/python2.6/papyon/p2p.py", line 179, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'

**Comment by Zincr0** [comment]
Fixed changing the papyon version.
