### ISSUE TITLE
Content roaming 404

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#265]
Every time I login, I get this:

[20:20:50 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[20:20:50 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[20:20:52 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 148, in request_static_tile
    self.get_resource(scheme, host, resource, callback, errback)
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 180, in get_resource
    transport.request(resource, http_headers, method='GET')
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 186, in request
    self._process_queue()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 163, in _process_queue
    self._setup_transport()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 99, in _setup_transport
    self._transport.open()
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/iochannel.py", line 150, in open
    if not self._configure():
  File "/home/sven/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/abstract.py", line 102, in _configure
    (self._host, self._port) )
ValueError: Wrong host or port number : (, 80)

but everything works AFAIK.

**Comment by c10ud** [comment]
seems like there's no _host? did you update papyon through the git submodule?

**Comment by Sbte** [comment]
git submodule
 e68ab58ed43b1d743de60f87e249cdf731528277 emesene/e3/papylib/papyon (papyon-0.5.4)

so yes

**Comment by c10ud** [comment]
ok..would you please file a bug in here
https://bugs.freedesktop.org//buglist.cgi?product=papyon

so papyon devs can have a look? unfortunately it's been a while since i last seen the main dev so i can't talk directly...

**Comment by Sbte** [comment]
Will do

**Comment by c10ud** [comment]
BTW, it comes to my mind that you can possibly fix this with the profile-recovery "option" i put in preferences-live messenger. just follow the procedure and see if it helps :)

**Comment by Sbte** [comment]
Logging in to my live profile didn't help if that's what you mean.

**Comment by c10ud** [comment]
and, change your dp from there once?

**Comment by Sbte** [comment]
Did that. Now all my contacts are removed....

**Comment by Sbte** [comment]
But after logging in a few times on emesene 1 and emesene 2 back and forth, it now seems to work.

**Comment by c10ud** [comment]
beware: emesene-1 trashes profiles usually

**Comment by Sbte** [comment]
Now apparently it fixed it...

My contacts were all blocked instead of removed, and that was quite annoying because I had to unblock all of them manually. But it was logging in on live that did that. Not emesene 1. Emesene 1 fixed my nickname.

**Comment by Sbte** [comment]
Actually, it's back. So I didn't fix it.

**Comment by c10ud** [comment]
if you're using multiple clients, there're some that break your profile on the server (very much likely emesene-1). once you fix it through the procedure in preferences-live messenger (emesene-2) you shouldn't use a breaky client anymore...

**Comment by Sbte** [comment]
I didn't use a different client since it was fixed for me. It broke again while I was still using emesene 2. 

Here are the steps I took and what happened:
- On emesene 2 I got the error in the original post.
- I logged in to my live profile and did everything I was told to do there.
- Logged back in on emesene 2. All my contacts were blocked, settings were reset, but setting my name still didn't work. Still got the same error and I was more pissed off because all my contacts were blocked (and I think the blocked ones where fully removed). I tried a few times if I could get the nickname to work, but it didn't.
- Then I logged in on emesene 1, to unblock all my contacts (because it's easier in emesene 1). Also, my nickname was good in emesene 1. When I logged back in on emesene 2, my nickname now worked in emesene 2 too, and I could also change it there.
- 3 days ago, it didn't work any more. I got the same error, and my nickname was set back to my email. 

No emesene 1 involved other than to fix the problem (apparently).

Also, still no reply from the papyon devs.

**Comment by c10ud** [comment]
that is really weird: the 404 is effectively because of a screwed profile -- any chance you can login with WLM?

**Comment by Sbte** [comment]
Did that just now. Didn't work.

**Comment by c10ud** [comment]
this _could_ have been fixed by papyon 0.5.4 and andrea's commit in papyon.. anyway, if further problems happen, they're papyons :D

**Comment by c10ud** [comment]
closing to diminuish some ticket volume
