### ISSUE TITLE
papyon problem?

### ISSUE THREAD

**Issue by Zincr0** [emesene/emesene#280]
At login time:

<blockquote>
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/papyon/client.py", line 385, in state_changed
    self._state = ClientState.OPEN
  File "/usr/lib/pymodules/python2.6/papyon/client.py", line 278, in fset
    self._dispatch("on_client_state_changed", state)
  File "/usr/lib/pymodules/python2.6/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/usr/lib/pymodules/python2.6/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/daniel/proyectos/python projects/emesene/emesene/e3/papylib/PapyEvents.py", line 36, in on_client_state_changed
    self._client.set_initial_infos()
  File "/home/daniel/proyectos/python projects/emesene/emesene/e3/papylib/Worker.py", line 138, in set_initial_infos
    self.content_roaming.connect("notify::state", \
AttributeError: 'Worker' object has no attribute 'content_roaming'
</blockquote>

What version of papyon should i use for emesene2?
Regards!

**Comment by Sbte** [comment]
0.5.4 (the latest), but at least 0.5.2 I think. Just do

git submodule init
git submodule update

In git and git submodule update after you update emesene itself by git pull origin master or something alike.

**Comment by Zincr0** [comment]
done, fixed. The ubuntu´s (10,04) papyon was the problem.
