### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 257: invalid continuation byte

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#282]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 455, in _sb_message_received
    handler._on_message_received(message)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/conversation.py", line 388, in _on_message_received
    msg = ConversationMessage(unicode(message.body, message_encoding),
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 257: invalid continuation byte

**Comment by c10ud** [comment]
can't we get the message that triggered the error?

**Comment by c10ud** [comment]
next time it pops up this kind of error please note down the offending message

**Comment by zipatei** [comment]
ya... sorry for this time.
