### ISSUE TITLE
Emesene doesn't start due to no handlers found for logger. (Fedora 14, Python 2.7 )

### ISSUE THREAD

**Issue by corvx** [emesene/emesene#283]
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "e3.common.Config"
Traceback (most recent call last):
File "emesene.py", line 680, in 
main()
File "emesene.py", line 677, in main
main_method(Controller)
File "/home/eric/Source/emesene/emesene/gui/gtkui/**init**.py", line 92, in gtk_main
controller.start()
File "emesene.py", line 186, in start
self.go_login(proxy, use_http)
File "emesene.py", line 205, in go_login
use_http, self.config.session, cancel_clicked, no_autologin)
File "/home/eric/Source/emesene/emesene/gui/gtkui/Window.py", line 72, in go_login
cancel_clicked, no_autologin)
File "/home/eric/Source/emesene/emesene/gui/gtkui/Login.py", line 283, in **init**
self._show_sessions()
File "/home/eric/Source/emesene/emesene/gui/gtkui/Login.py", line 294, in _show_sessions
self.new_combo_session(self.session_combo,self.__on_session_changed)
File "/home/eric/Source/emesene/emesene/gui/gtkui/Login.py", line 312, in new_combo_session
if service == service_name:
UnboundLocalError: local variable 'service' referenced before assignment

**Comment by astagi** [comment]
Hi, thank you for this notification and your contribute :) Bug has been fixed in Mariano Guerra repository ( https://github.com/marianoguerra/emesene ) and will be soon avaible here... Bests

**Comment by c10ud** [comment]
fixed
