### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by hit** [emesene/emesene#286]
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/home/hit/Apps/emesene2/emesene/emesene.py", line 677, in main
    main_method(Controller)
  File "/home/hit/Apps/emesene2/emesene/gui/gtkui/**init**.py", line 92, in gtk_main
    controller.start()
  File "/home/hit/Apps/emesene2/emesene/emesene.py", line 186, in start
    self.go_login(proxy, use_http)
  File "/home/hit/Apps/emesene2/emesene/emesene.py", line 205, in go_login
    use_http, self.config.session, cancel_clicked, no_autologin)
  File "/home/hit/Apps/emesene2/emesene/gui/gtkui/Window.py", line 72, in go_login
    cancel_clicked, no_autologin)
  File "/home/hit/Apps/emesene2/emesene/gui/gtkui/Login.py", line 283, in **init**
    self._show_sessions()
  File "/home/hit/Apps/emesene2/emesene/gui/gtkui/Login.py", line 294, in _show_sessions
    self.new_combo_session(self.session_combo,self.__on_session_changed)
  File "/home/hit/Apps/emesene2/emesene/gui/gtkui/Login.py", line 312, in new_combo_session
    if service == service_name:
UnboundLocalError: local variable 'service' referenced before assignment

Commenting out "if account in self.accounts:" in Login.py:304 allows me to start emesene again.

**Comment by Sbte** [comment]
Could you test again with current git?

**Comment by c10ud** [comment]
bing, fixed
