### ISSUE TITLE
emesene not opening: UnboundLocalError: local variable 'service' referenced before assignment

### ISSUE THREAD

**Issue by targxs13** [emesene/emesene#293]
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/usr/share/pyshared/emesene/emesene.py", line 677, in main
    main_method(Controller)
  File "/usr/share/pyshared/emesene/gui/gtkui/**init**.py", line 92, in gtk_main
    controller.start()
  File "/usr/share/pyshared/emesene/emesene.py", line 186, in start
    self.go_login(proxy, use_http)
  File "/usr/share/pyshared/emesene/emesene.py", line 205, in go_login
    use_http, self.config.session, cancel_clicked, no_autologin)
  File "/usr/share/pyshared/emesene/gui/gtkui/Window.py", line 72, in go_login
    cancel_clicked, no_autologin)
  File "/usr/share/pyshared/emesene/gui/gtkui/Login.py", line 283, in **init**
    self._show_sessions()
  File "/usr/share/pyshared/emesene/gui/gtkui/Login.py", line 294, in _show_sessions
    self.new_combo_session(self.session_combo,self.__on_session_changed)
  File "/usr/share/pyshared/emesene/gui/gtkui/Login.py", line 312, in new_combo_session
    if service == service_name:
UnboundLocalError: local variable 'service' referenced before assignment

I was trying to use Jabber to access my facebook account. When I clicked on Sign up, it was taking too much time, so i decided to close emesene. But the next time i tried to open emesene, i got this message. I did a reboot, and it didnt work, Next, I uninstalled the program and then installed it again and the same happened. 
What can i do?

**Comment by Sbte** [comment]
Please update to the latest git version. Should be fixed there...

**Comment by c10ud** [comment]
indeed
