### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by hit** [emesene/emesene#3]
Traceback (most recent call last):
  File "./emesene", line 33, in <module>
    emesene.main()
  File "/home/hit/Apps/mesinyer/mesinyer/emesene.py", line 535, in main
    main_method(Controller)
  File "/home/hit/Apps/mesinyer/mesinyer/gui/gtkui/**init**.py", line 44, in gtk_main
    controller.start()
  File "/home/hit/Apps/mesinyer/mesinyer/emesene.py", line 414, in start
    print "Debug" + int(self.config.d_remembers[account])
TypeError: 'NoneType' object is unsubscriptable

**Comment by cando** [comment]
you have to delete your old config in emesene2 folder....

**Comment by cando** [comment]
have you solved the problem??

**Comment by hit** [comment]
Doesn't change anything.

**Comment by cando** [comment]
what branch are you trying?because i haven't your error (that is strange...self.config in the start method should not be None...).If you want try my branch...

**Comment by hit** [comment]
For some very weird reason I had that line different from git (according to git diff). Reverted that and works again.

**Comment by c10ud** [comment]
kaboom
