### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#316]
when i try to start emesene:

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "emesene/emesene.py", line 40, in <module>
    from e3 import jabber
  File "/home/fabio/emesene2/emesene/e3/jabber/**init**.py", line 2, in <module>
    from Session import Session
  File "/home/fabio/emesene2/emesene/e3/jabber/Session.py", line 30
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by astagi** [comment]
Update your local repo or reclone from emesene/emesene..

**Comment by astagi** [comment]
Closing
