### ISSUE TITLE
ImportError: No module named UserPanel

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#319]
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/home/david/emesene/emesene/emesene.py", line 688, in main
    main_method(Controller)
  File "/home/david/emesene/emesene/gui/gtkui/**init**.py", line 79, in gtk_main
    import UserPanel
ImportError: No module named UserPanel

**Comment by c10ud** [comment]
Re-add UserPanel.py. closed by 00fbe0eb93d7c923d9f1cebcd152209b81df1768
