### ISSUE TITLE
Settings are reset upon reconnect

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#322]
First of all, clicking reconnect gives:

Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/Login.py", line 612, in _on_connect_clicked
    self.do_connect()
  File "/home/sven/emesene/emesene/gui/gtkui/Login.py", line 394, in do_connect
    self.server_host)
AttributeError: 'ConnectingWindow' object has no attribute 'server_host'

This doesn't work for me, but that could be the connection problems I have atm. Anyway, as soon as I'm connected all my settings are reset i.e. notification sound messages, chat window size, contact list layout. Everything.

I'll look into this this weekend or so, but is there an easy way to simulate this other than by disconnecting from the internet?

**Comment by c10ud** [comment]
ah-- interesting, here's why sometimes settings were reset. i guess disconnecting from the internet is the only way unfortunately

**Comment by c10ud** [comment]
damn network buffering..this is extremely difficult for me to test..
this could be worth a try..in emesene.py the _new_session method seems like is not calling the close_session method but just creates a new one?

**Comment by c10ud** [comment]
nvm, seems unrelated. someone should really look into this

**Comment by ammarabdulsalam** [comment]
I've tried to disconnect Internet but emesene didn't detect that, and there is no debug info at all.

**Comment by Sbte** [comment]
Ok, here we go. This is what happens when you connect the normal way:

```
[21:50:21 INFO gtkui.Login] Login initialization called
[21:50:21 INFO gtkui.Login] LoginBase initialization called
[21:50:21 INFO gtkui.Login] Login window created
[21:50:21 INFO gtkui.Login] _reload_account_list called
[21:50:21 INFO gtkui.Login] _on_account_changed called
[21:50:21 INFO gtkui.Login] _update_fields called
[21:50:21 INFO gtkui.Login] _clear_all called
[21:50:21 INFO gtkui.Login] _on_password_changed called
[21:50:21 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:21 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:21 INFO gtkui.Login] _check_autologin called
[21:50:21 INFO gtkui.Login] _show_sessions called
[21:50:21 INFO gtkui.Login] new_combo_session called
[21:50:21 INFO gtkui.Login] Login initialized
[21:50:22 INFO gtkui.Login] _on_connect_clicked called
[21:50:22 INFO gtkui.Login] do_connect called
[21:50:22 INFO gtkui.Login] _config_account called
[21:50:22 INFO gtkui.Login] ConnectingWindow initialization called
[21:50:22 INFO gtkui.Login] LoginBase initialization called
[21:50:22 INFO gtkui.Login] Login window created
[21:50:22 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:22 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:22 INFO gtkui.Login] _on_account_changed called
[21:50:22 INFO gtkui.Login] _update_fields called
[21:50:22 INFO gtkui.Login] _on_password_changed called
```

And here is what happens when it fails, first, then the reconnect button is clicked (and doesn't work), and then reconnect works after the timeout):

```
[21:50:50 INFO gtkui.Login] Login initialization called
[21:50:50 INFO gtkui.Login] LoginBase initialization called
[21:50:50 INFO gtkui.Login] Login window created
[21:50:50 INFO gtkui.Login] _reload_account_list called
[21:50:50 INFO gtkui.Login] _on_account_changed called
[21:50:50 INFO gtkui.Login] _update_fields called
[21:50:50 INFO gtkui.Login] _clear_all called
[21:50:50 INFO gtkui.Login] _on_password_changed called
[21:50:50 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:50 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:50 INFO gtkui.Login] _check_autologin called
[21:50:50 INFO gtkui.Login] _show_sessions called
[21:50:50 INFO gtkui.Login] new_combo_session called
[21:50:50 INFO gtkui.Login] Login initialized
[21:50:51 INFO gtkui.Login] _on_connect_clicked called
[21:50:51 INFO gtkui.Login] do_connect called
[21:50:51 INFO gtkui.Login] _config_account called
[21:50:51 INFO gtkui.Login] ConnectingWindow initialization called
[21:50:51 INFO gtkui.Login] LoginBase initialization called
[21:50:51 INFO gtkui.Login] Login window created
[21:50:51 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:51 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:51 INFO gtkui.Login] _on_account_changed called
[21:50:51 INFO gtkui.Login] _update_fields called
[21:50:51 INFO gtkui.Login] _on_password_changed called
[21:50:51 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x2457410 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x25fe760)>
[21:50:51 DEBUG papyon.transport] <-> Connecting to messenger.hotmail.com:1863
[21:50:52 INFO gtkui.Login] ConnectingWindow initialization called
[21:50:52 INFO gtkui.Login] LoginBase initialization called
[21:50:52 DEBUG papylib.Events] closing thread
[21:50:52 WARNING papyon.client] alreay logged out
[21:50:52 INFO gtkui.Login] Login window created
[21:50:52 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:52 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:52 INFO gtkui.Login] _on_account_changed called
[21:50:52 INFO gtkui.Login] _update_fields called
[21:50:52 INFO gtkui.Login] _on_password_changed called
[21:50:52 INFO gtkui.Login] on_reconnect called
[21:50:52 INFO gtkui.Login] update_reconnect_timer called
[21:50:53 INFO gtkui.Login] update_reconnect_timer called
[21:50:53 INFO gtkui.Login] _on_connect_clicked called
[21:50:53 INFO gtkui.Login] do_connect called
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/gui/gtkui/Login.py", line 637, in _on_connect_clicked
    self.do_connect()
  File "/home/sven/emesene-dev/emesene/gui/gtkui/Login.py", line 406, in do_connect
    self.server_host)
AttributeError: 'ConnectingWindow' object has no attribute 'server_host'
[21:50:53 INFO gtkui.Login] _on_connect_now_clicked called
[21:50:53 INFO gtkui.Login] clear_connect called
[21:50:53 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x7f9b70017960 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x262baa0)>
[21:50:53 DEBUG papyon.transport] <-> Connecting to messenger.hotmail.com:1863
[21:50:54 INFO gtkui.Login] ConnectingWindow initialization called
[21:50:54 INFO gtkui.Login] LoginBase initialization called
[21:50:54 DEBUG papylib.Events] closing thread
[21:50:54 WARNING papyon.client] alreay logged out
[21:50:54 INFO gtkui.Login] Login window created
[21:50:54 INFO gtkui.Login] _on_remember_password_toggled called
[21:50:54 INFO gtkui.Login] _on_remember_account_toggled called
[21:50:54 INFO gtkui.Login] _on_account_changed called
[21:50:54 INFO gtkui.Login] _update_fields called
[21:50:54 INFO gtkui.Login] _on_password_changed called
[21:50:54 INFO gtkui.Login] on_reconnect called
[21:50:54 INFO gtkui.Login] update_reconnect_timer called
[21:50:55 INFO gtkui.Login] update_reconnect_timer called
[21:50:56 INFO gtkui.Login] update_reconnect_timer called
[21:50:57 INFO gtkui.Login] update_reconnect_timer called
[21:50:58 INFO gtkui.Login] update_reconnect_timer called
[21:50:59 INFO gtkui.Login] update_reconnect_timer called
[21:51:00 INFO gtkui.Login] update_reconnect_timer called
[21:51:01 INFO gtkui.Login] update_reconnect_timer called
[21:51:02 INFO gtkui.Login] update_reconnect_timer called
[21:51:03 INFO gtkui.Login] update_reconnect_timer called
[21:51:04 INFO gtkui.Login] update_reconnect_timer called
[21:51:05 INFO gtkui.Login] update_reconnect_timer called
[21:51:06 INFO gtkui.Login] update_reconnect_timer called
[21:51:07 INFO gtkui.Login] update_reconnect_timer called
[21:51:08 INFO gtkui.Login] update_reconnect_timer called
[21:51:09 INFO gtkui.Login] update_reconnect_timer called
[21:51:10 INFO gtkui.Login] update_reconnect_timer called
[21:51:11 INFO gtkui.Login] update_reconnect_timer called
[21:51:12 INFO gtkui.Login] update_reconnect_timer called
[21:51:13 INFO gtkui.Login] update_reconnect_timer called
[21:51:14 INFO gtkui.Login] update_reconnect_timer called
[21:51:15 INFO gtkui.Login] update_reconnect_timer called
[21:51:16 INFO gtkui.Login] update_reconnect_timer called
[21:51:17 INFO gtkui.Login] update_reconnect_timer called
[21:51:18 INFO gtkui.Login] update_reconnect_timer called
[21:51:19 INFO gtkui.Login] update_reconnect_timer called
[21:51:20 INFO gtkui.Login] update_reconnect_timer called
[21:51:21 INFO gtkui.Login] update_reconnect_timer called
[21:51:22 INFO gtkui.Login] update_reconnect_timer called
[21:51:23 INFO gtkui.Login] update_reconnect_timer called
[21:51:23 INFO gtkui.Login] clear_connect called
```

**Comment by c10ud** [comment]
apart from the exception, seems like
on_connect called
 _config_account called
are not called after reconnecting? should they be mandatory?

2011/3/25 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
_config_account is called by do_connect. do_connect just sets the login variables, so maybe 

```
    self._config_account(account, remember_account, remember_password,
                         auto_login)
```

before the callback in update_reconnect_timer would fix it.

**Comment by Sbte** [comment]
I think it would be better to find where the default settings come from. They just shouldn't be set at all here. I don't think calling config_account would help, even if it would work. It would simply save the config, which would be overwritten again in emesene.py. As least that's what I can make of it.

**Comment by Sbte** [comment]
Ok, first part of the bug fixed (the error), but I think the second part has something to do with the config not saved to the right place (like saving to the config_path instead of the config_dir or something). But I don't really understand how all that stuff works. Maybe this could be fixed while someone fixes #340

**Comment by Sbte** [comment]
Dammit, just clicked comment and close. Can someone reopen this?

**Comment by Sbte** [comment]
Ok, it's not due to saving, so now I'm guessing the wrong config file is loaded somewhere
