### ISSUE TITLE
Emesene 1.6.3 Disable Sounds

### ISSUE THREAD

**Issue by nandru85** [emesene/emesene#326]
Hello!
I'll like to see an option to disable sounds from emesene (notification, nudge, etc) in my case, i'm on a server without a sound board and emesene complains and crash when is trying to play a sound. this is the report (no debuggin')

Exception
You are using emesene 1.6.X - "Uberlândia undrgz" BETAFIX? so you're free to complain here:
http://forum.emesene.org/index.php/board,19.0.html
Check already existing tickets for duplicates first, please.
Traceback (most recent call last):

  File "Sound.pyo", line 233, in offline

  File "Sound.pyo", line 101, in play

  File "Sound.pyo", line 106, in play_path

RuntimeError: Failed to play sound

**Comment by nandru85** [comment]
It's portable edition, but I'm asuming this error will be present in the install version as well.

This could be useful when you are listening music very loud and don't want to be bothered by msn notifications...
