### ISSUE TITLE
OFFLINE_MESSAGGES

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#338]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 521, in error
    self._dispatch("on_client_error", ClientErrorType.OFFLINE_MESSAGES, error_code)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/andre/emesene/emesene/e3/papylib/PapyEvents.py", line 78, in on_client_error
    elif error_type == papyon.event.ClientErrorType.OFFLINE_MESSAGGES:#TODO
AttributeError: type object 'ClientErrorType' has no attribute 'OFFLINE_MESSAGGES'

**Comment by c10ud** [comment]
typo? only one G needed? can you try it?

**Comment by zipatei** [comment]
Error. Offline messages are empty.
1. Offline messages received after login

**Comment by c10ud** [comment]
fixed by sbte
