### ISSUE TITLE
msn backend: 'Session' object has no attribute 'create_config'

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#34]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/sweetth/emesene/mesinyer/e3/msn/Worker.py", line 167, in run
    self._process(data)
  File "/home/sweetth/emesene/mesinyer/e3/msn/Worker.py", line 207, in _process
    self._process_login(message)
  File "/home/sweetth/emesene/mesinyer/e3/msn/Worker.py", line 216, in _process_login
    handler(message)
  File "/home/sweetth/emesene/mesinyer/e3/msn/Worker.py", line 434, in _on_login_message
    self.session.create_config()
AttributeError: 'Session' object has no attribute 'create_config'

(this log is not mine, but I have the same exception, I used this one reported on emesene forum\* because I can't happily copy/paste from a terminal on windows...)

I removed everything on my computer to start a fresh clone of my repo, made a rebase with emesene/emesene and tried to run emesene (without papyon).

*http://forum.emesene.org/index.php/topic,3370.msg23139.html#msg23139

NOTE: Maybe related, just before that exception, another one appears on my computer and on the reported bug on emesene's forum:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in **bootstrap_inner
    self.run()
  File "/home/sweetth/emesene/mesinyer/e3/base/Logger.py", line 719, in run
    self.logger = Logger(self.path)
  File "/home/sweetth/emesene/mesinyer/e3/base/Logger.py", line 279, in __init**
    self.connection = sqlite.connect(path)
OperationalError: unable to open database file

**Comment by marianoguerra** [comment]
update and try again, should be fixed
