### ISSUE TITLE
Login and get error messages 

### ISSUE THREAD

**Issue by thomasysliu** [emesene/emesene#351]
emesene just login and get several error message below.

I use the version git from trunk

<Data><UserTileLocation>&lt;msnobj Creator="xxxxxx@hotmail.com" Type="3" SHA1D="hzopb0jUs+bAZ2riW0m2E3I1LqA=" Size="3005" Location="0" Friendly="PwAAAA=="/&gt;</UserTileLocation><FriendlyName>Jack</FriendlyName><PSM></PSM><DDP></DDP><Scene>&lt;msnobj Creator="xxxxxxx@hotmail.com" Type="16" SHA1D="AObGoRzl+hGH4rdS7gbF9qIRmos=" Size="413909" Location="0" Friendly="SwBlAGUAcABlAHIAIABPAGYAIABUAGgAZQAgAFMAZQB2AGUAbgAgAEsAZQB5AHMAIABQAGEAcgB0ACAAMgAAAA=="/&gt;</Scene><ASN></ASN><ColorScheme>-3</ColorScheme><BDG></BDG><RUM></RUM><RUL></RUL><RLT>0</RLT><RID></RID><SUL></SUL><CurrentMedia></CurrentMedia><EndpointData id="{759a4e0c-cba3-4035-b093-37adbb1ae458}"><Capabilities>3055849776:2609258384</Capabilities></EndpointData></Data>
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/papyon/client.py", line 368, in property_changed
    self._dispatch(method_name, contact)
  File "/usr/lib/pymodules/python2.6/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/usr/lib/pymodules/python2.6/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/liu/tmp/emesene/emesene/e3/papylib/PapyEvents.py", line 148, in on_contact_msn_object_changed
    self._client._on_contact_msnobject_changed(contact)
  File "/home/liu/tmp/emesene/emesene/e3/papylib/Worker.py", line 671, in _on_contact_msnobject_changed
    (download_ok, download_failed), peer=contact)
  File "/usr/lib/pymodules/python2.6/papyon/p2p.py", line 334, in request
    session.invite()
  File "/usr/lib/pymodules/python2.6/papyon/p2p.py", line 587, in invite
    session.invite()
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/msnobject.py", line 64, in invite
    self._invite(self._context)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/session.py", line 156, in _invite
    self._send_slp_message(message)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/session.py", line 261, in _send_slp_message
    self._application_id, message)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/transport_manager.py", line 127, in send_slp_message
    self.send_data(peer, peer_guid, application_id, 0, str(message))
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/transport_manager.py", line 132, in send_data
    transport.send(peer, peer_guid, blob)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/base.py", line 103, in send
    self._process_send_queue()
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/base.py", line 206, in _process_send_queue
    self.__send_chunk(peer, peer_guid, chunk)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/base.py", line 224, in __send_chunk
    self._send_chunk(peer, peer_guid, chunk)
  File "/usr/lib/pymodules/python2.6/papyon/msnp2p/transport/switchboard.py", line 102, in _send_chunk
    peer_guid + "}"}
TypeError: cannot concatenate 'str' and 'NoneType' objects
<Data><UserTileLocation>&lt;msnobj Creator="xxxxx@hotmail.com" Size="9306" Type="3" Location="0" Friendly="" SHA1D="h98YyxtDE8ce1LgmMIKDYVnAhTc=" SHA1C="/Rk1PL4VPhlqynLu1afoTB2F51k="/&gt;</UserTileLocation><FriendlyName>xxxxx@hotmail.com</FriendlyName><RUM>test al,al</RUM><PSM>test al,al</PSM><MachineGuid></MachineGuid><CurrentMedia></CurrentMedia></Data>
<Data><UserTileLocation></UserTileLocation><EndpointData id="{6dc82cd1-f709-49e5-8ee4-5f1e924c577b}"><Capabilities>2754609424:2550273072</Capabilities></EndpointData><EndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><Capabilities>2684355072:2147484936</Capabilities><DMN>mail.live.com</DMN><WebAppData domain="mail.live.com"><MsgIds><Id>json</Id></MsgIds><Properties></Properties></WebAppData></EndpointData><PrivateEndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><EpName>Messenger 網路版</EpName><ClientType>2</ClientType></PrivateEndpointData></Data>
<Data><UserTileLocation></UserTileLocation><FriendlyName>甫</FriendlyName><EndpointData id="{6dc82cd1-f709-49e5-8ee4-5f1e924c577b}"><Capabilities>2754609424:2550273072</Capabilities></EndpointData><EndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><Capabilities>2684355072:2147484936</Capabilities><DMN>mail.live.com</DMN><WebAppData domain="mail.live.com"><MsgIds><Id>json</Id></MsgIds><Properties></Properties></WebAppData></EndpointData><PrivateEndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><EpName>Messenger 網路版</EpName><ClientType>2</ClientType></PrivateEndpointData></Data>
<Data><UserTileLocation>&lt;msnobj Creator="xxxxxxx@hotmail.com" Type="3" SHA1D="8Dr39aME4o//tYr4KTzDV42LLJI=" Size="4468" Location="f03af7f5a304e28fffb58af8293cc3578d8b2c92.tmp" Friendly=""/&gt;</UserTileLocation><FriendlyName>甫</FriendlyName><EndpointData id="{6dc82cd1-f709-49e5-8ee4-5f1e924c577b}"><Capabilities>2754609424:2550273072</Capabilities></EndpointData><EndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><Capabilities>2684355072:2147484936</Capabilities><DMN>mail.live.com</DMN><WebAppData domain="mail.live.com"><MsgIds><Id>json</Id></MsgIds><Properties></Properties></WebAppData></EndpointData><PrivateEndpointData id="{50eca15b-e042-4eb2-8306-1a075e2f059a}"><EpName>Messenger 網路版</EpName><ClientType>2</ClientType></PrivateEndpointData></Data>

**Comment by thomasysliu** [comment]
After I run 

git submodule init
git submodule update

It seems fixed !!! :-)

**Comment by c10ud** [comment]
if you have papyon0.5.4 this has been fixed.

2011/3/19 thomasysliu
reply@reply.github.com:

**Comment by marianoguerra** [comment]
old version of papyon, closing
