### ISSUE TITLE
TypeError: __common_errback() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#356]
don't know if it is know, but better to say:

[11:30:58 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[11:30:59 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error)
  File "/usr/lib/python2.7/site-packages/papyon/util/async.py", line 40, in run
    callback[0](*args)
TypeError: __common_errback() takes at least 3 arguments (2 given)

**Comment by astagi** [comment]
Hi, yes it is but it's not a fatal error...patch just sent to papyon team ( https://github.com/4ndreaSt4gi/papyon/commit/c643c7b431a46ad78a6a312cb20908f4b01e9908 )... Attending the merge...

Anyway thanks ;)
