### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by luislezcair** [emesene/emesene#369]
I'm getting this error on startup (when I execute ./emesene or python emesene.py):
    luis@Kassius:~/Descargas/emesene-git/emesene/emesene$ python emesene.py
    No handlers could be found for logger "gui.gtkui.Indicator"
    Traceback (most recent call last):
      File "emesene.py", line 708, in <module>
        main()
      File "emesene.py", line 705, in main
        main_method(Controller)
      File "/home/luis/Descargas/emesene-git/emesene/emesene/gui/gtkui/**init**.py", line 99, in gtk_main
        controller.start()
      File "emesene.py", line 201, in start
        self.tray_icon = trayiconcls(handler, self.window)
      File "/home/luis/Descargas/emesene-git/emesene/emesene/gui/gtkui/Indicator.py", line 72, in **init**
        self.set_login()
      File "/home/luis/Descargas/emesene-git/emesene/emesene/gui/gtkui/Indicator.py", line 87, in set_login
        if self.messaging_menu: return
    AttributeError: 'Indicator' object has no attribute 'messaging_menu'

If I comment out that line it works, and emesene starts, but the tray icon does not show an icon and it won't open when I click on it.

I'm using Kubuntu 11.04 beta with the emesene I just clonned from the repo.

**Comment by Sbte** [comment]
I think I fixed it. Could you try again?

**Comment by c10ud** [comment]
fixed by sbte: https://github.com/emesene/emesene/commit/0a8aaa7155d009073055186b3adc20c50c9f3542

**Comment by luislezcair** [comment]
Yes, that fixed it. Thank you!
