### ISSUE TITLE
Memenu and notifications get confused by new cids

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#379]
At the moment every time a contact logs in and sends you a message, and you don't open it, a new memenu entry will be created. This means that all the old ones are dead. When you click on them, you get this:

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/MessagingMenu.py", line 197, in _display
    if self.r_indicator_dict[conv.cid] is not None:
UnboundLocalError: local variable 'conv' referenced before assignment
```

Only the most recent one works. Apparently, the memenu entry is decoupled from the message when the contact sends you a new message (after he logged back in).

**Comment by Sbte** [comment]
And when you try to shut down:

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/MainMenu.py", line 97, in <lambda>
    lambda *args: self.handler.on_quit_selected())
  File "/home/sven/emesene/emesene/gui/base/Handler.py", line 82, in on_quit_selected
    self.on_quit()
  File "/home/sven/emesene/emesene/emesene.py", line 631, in on_close
    self.close_session()
  File "/home/sven/emesene/emesene/emesene.py", line 290, in close_session
    self.tray_icon.set_visible(False)
  File "/home/sven/emesene/emesene/gui/gtkui/Indicator.py", line 79, in set_visible
    self.messaging_menu.set_visible(arg)
  File "/home/sven/emesene/emesene/gui/gtkui/MessagingMenu.py", line 82, in set_visible
    if self.indicator_dict[ind] is not None:
KeyError: <indicate.Indicator object at 0x3759af0 (IndicateIndicator at 0x46548c0)>
```

**Comment by c10ud** [comment]
@cando ^

2011/4/9 Sbte reply@reply.github.com:

**Comment by cando** [comment]
Mmmm ok. Right now i'm  a bit busy, but asap i'll look into this...:)

**Comment by c10ud** [comment]
[22:07] <c10ud> sbte, maybe we just fire an event
[22:07] <c10ud> when we call reuse
[22:07] <c10ud> (!!!)
[22:07] <c10ud> like -- when reusing, signal that cid is being updated

**Comment by c10ud** [comment]
[21:25] <sbte> On 1111, talk to 2222
[21:25] <sbte> Close 1111's emesene
[21:25] <sbte> Open 1111's emesene
[21:25] <sbte> talk to 2222 again
[21:25] <sbte> Now you'll see two times 1111 in the memenu
[21:25] <sbte> Now open the chat through the taskbar
[21:25] <sbte> Now there is still one instance of 2222 in the memenu
[21:25] <sbte> Click it
[21:25] <sbte> Error

**Comment by Sbte** [comment]
Same issue with notifications btw:

```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene-dev/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene-dev/emesene/e3/common/notification.py", line 90, in _on_message
    not(self.session.conversations[cid].get_parent().is_active()):
KeyError: 1302692652.0439019
```

**Comment by c10ud** [comment]
workarounded, closing
