### ISSUE TITLE
Commit 7617c13d47e5 has broken the dummy session

### ISSUE THREAD

**Issue by sledgehammer999** [emesene/emesene#38]
When I use the dummy session to test emesene I get these warnings in the terminal and the main window isn't drawn correctly(just the windows decorations show up and nothing else):

[00:37:02 WARNING e3.common.Signal] Signal handler (Controller.on_login_succeed) error: global name 'gui' is not defined
Traceback (most recent call last):
  File "/home/hammered/Desktop/emesene2/emesene/e3/common/Signal.py", line 55, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/hammered/Desktop/emesene2/emesene/emesene.py", line 399, in on_login_succeed
    self.draw_main_screen()
  File "/home/hammered/Desktop/emesene2/emesene/emesene.py", line 343, in draw_main_screen
    self.tray_icon.set_main(self.session)
  File "/home/hammered/Desktop/emesene2/emesene/gui/gtkui/Indicator.py", line 75, in set_main
    self.menu = MainMenu(self.handler, self.main_window)
  File "/home/hammered/Desktop/emesene2/emesene/gui/gtkui/Indicator.py", line 164, in **init**
    self.list_contacts = ContactsMenu(handler, main_window)
  File "/home/hammered/Desktop/emesene2/emesene/gui/gtkui/Indicator.py", line 207, in **init**
    self.__append_contact(contact)
  File "/home/hammered/Desktop/emesene2/emesene/gui/gtkui/Indicator.py", line 217, in __append_contact
    pict = self.__get_contact_pixbuf_or_default(contact)
  File "/home/hammered/Desktop/emesene2/emesene/gui/gtkui/Indicator.py", line 287, in __get_contact_pixbuf_or_default
    pix = utils.safe_gtk_pixbuf_load(gui.theme.user,
NameError: global name 'gui' is not defined
[00:37:02 WARNING e3.common.Signal] Signal handler (Controller.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/home/hammered/Desktop/emesene2/emesene/e3/common/Signal.py", line 55, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/hammered/Desktop/emesene2/emesene/emesene.py", line 450, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'

**Comment by c10ud** [comment]
sorry, missing import, fixed now
