### ISSUE TITLE
Emesene dont start

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#381]
Traceback (most recent call last):
  File "./emesene", line 34, in <module>
    emesene.main()
  File "/home/andre/emesene/emesene/emesene.py", line 725, in main
    main_method(Controller)
  File "/home/andre/emesene/emesene/gui/gtkui/**init**.py", line 50, in gtk_main
    import FileTransferWidget
  File "/home/andre/emesene/emesene/gui/gtkui/FileTransferWidget.py", line 254
    <<<<<<< HEAD
    ^
IndentationError: expected an indented block

**Comment by arielj** [comment]
You have conflicts on that file, try getting a fresh FileTransferWidget.py file and you're done.

I'll close this because it's not an emesene bug, your local copy of the file is wrong.
