### ISSUE TITLE
No se guarda el nick

### ISSUE THREAD

**Issue by javijec** [emesene/emesene#389]
primero disculpen, no se nada de ingles

cada vez que entro al emesene, me borra el nick

**Comment by ghost** [comment]
From Google Translate
Nick is not saved

first sorry, no English is not

every time I go to emesene, I delete the nick

---

If that is a close enough translation, then I also have been experiencing this a bit. Not every time I log in, but sometimes when I login my display name and personal message have been deleted.

**Comment by arielj** [comment]
hola javijec, podés correr el emesene desde una terminal con el comando "emesene -vv"? así podemos ver algún log, a ver si informa algún error

Hi javijec, can you run emesene from a terminal with the command "emesene -vv"? so we can see som log, an error or something

**Comment by javijec** [comment]
Quisiera saber que error busco en el log.

I wonder what you look for in the error log.

**Comment by javijec** [comment]
[22:51:30 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from blufiles.storage.msn.com:80
Traceback (most recent call last):
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error)
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 148, in request_static_tile
    self.get_resource(scheme, host, resource, callback, errback)
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 180, in get_resource
    transport.request(resource, http_headers, method='GET')
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 186, in request
    self._process_queue()
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 163, in _process_queue
    self._setup_transport()
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 99, in _setup_transport
    self._transport.open()
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/iochannel.py", line 150, in open
    if not self._configure():
  File "/home/javijec/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/abstract.py", line 102, in _configure
    (self._host, self._port) )
ValueError: Wrong host or port number : (, 80)

**Comment by Sbte** [comment]
Your profile is broken. Go to Preferences -> Live messenger and log in there, then change your avatar on there. This will fix it.

**Comment by c10ud** [comment]
your profile is screwed, follow the instructions in Preferences - Live Messenger

someone translate this to him please

2011/4/13 javijec
reply@reply.github.com:

**Comment by arielj** [comment]
javijec, tenés que arreglar tu perfil, andá a las opciones de emesene, a preferencias > live messenger, tocá en el botón que te abre el perfil online de windows live y cambiá tu avatar y tu nick ahí, después de eso tendría que andarte todo bien
