### ISSUE TITLE
Problem with recent file tranfer implementation.

### ISSUE THREAD

**Issue by sledgehammer999** [emesene/emesene#39]
Using papyon session. If (in emesene2) press the button to upload something to the current contact, this is what I get in the console:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/hammered/Desktop/emesene2/emesene/e3/papylib/Worker.py", line 118, in run
    self._process_action(action)
  File "/home/hammered/Desktop/emesene2/emesene/e3/base/Worker.py", line 148, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/hammered/Desktop/emesene2/emesene/e3/papylib/Worker.py", line 999, in _handle_action_ft_invite
    papysession = self._ft_manager.send(papycontact, filename, os.path.getsize(completepath))
AttributeError: 'Worker' object has no attribute '_ft_manager'

But "_ft_manager" should exist since Worker derives from papyon.Client. I am buffled. :S

**Comment by c10ud** [comment]
if you're using the papyon submodule, did you git pull from /emesene/e3/papylib/papyon? if yes, can you check (from that directory) if git log is == to http://git.collabora.co.uk/?p=papyon.git;a=summary ?

**Comment by sledgehammer999** [comment]
Yes, I have the latest papyon commit.
But I don't think this is a problem with papyon.

**Comment by c10ud** [comment]
try self.ft_manager, it should be the same, but seems like it's picking up the wrong version of papyon...maybe it prefers the system-wide install instead of the one provided within the directory?

**Comment by sledgehammer999** [comment]
How did you deduce that it is a papyon problem? I don't see something relevant in the output.

The same effect with "self.ft_manager"

I uninstalled the system's papyon and now I get this at the terminal:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/hammered/Desktop/emesene2/emesene/e3/papylib/Worker.py", line 118, in run
    self._process_action(action)
  File "/home/hammered/Desktop/emesene2/emesene/e3/base/Worker.py", line 148, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/hammered/Desktop/emesene2/emesene/e3/papylib/Worker.py", line 999, in _handle_action_ft_invite
    papysession = self._ft_manager.send(papycontact, filename, os.path.getsize(completepath))
  File "/usr/lib/python2.6/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/tmp/test'

**Comment by sledgehammer999** [comment]
oops sorry. Now I found that you have hardcoded the path for testing purposes.

**Comment by c10ud** [comment]
ok then, it's taking system version instead of the other one, we must change the code to choose "our" version first. :)

and yes, i have hardcoded the path because i was too lazy to put a generic dialog since i didn't remember how to do it :p

p.s. if you can, open another issue "papyon should choose "own" version instead of system-wide one" if someone know how to fix this... :p
