### ISSUE TITLE
Can't add new contact

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#392]
I would like to add a new contact with emesene 2 (fully updated), I am add the address, the group, but nothing happen (my friend don't see the request), and no error message in terminal.

**Comment by Sbte** [comment]
I do get an error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/home/sven/emesene-dev/emesene/e3/papylib/Worker.py", line 131, in run
    self._process_action(action)
  File "/home/sven/emesene-dev/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/sven/emesene-dev/emesene/e3/papylib/Worker.py", line 861, in _handle_action_add_to_group
    papycontact = self.address_book.contacts.search_by('account', account)[0]
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/service/AddressBook/address_book.py", line 53, in __getitem__
    raise IndexError("Index out of range")
IndexError: Index out of range
```
