### ISSUE TITLE
Chat window blank after opening preferences

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#404]
This issue is directly related to #403

After opening preferences, hovering over contacts, the next chat window you open is completely blank. After closing it, no other chat windows can be open until you disconnect and reconnect. Once reconnected, everything is fine until preferences is opened again.

Steps to reproduce:
1. Start emesene and login
2. Open preferences
3. Open a chat window with a contact, its blank.

Picture of contact list and blank chat window:
http://img222.imageshack.us/i/blankchat.png/

Git Terminal when opening chat window:

```
Traceback (most recent call last):
  File "c:\Users\Shawn\emesene\emesene\e3\common\Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "c:\Users\Shawn\emesene\emesene\e3\common\Signal.py", line 111, in __call
__
    self.f(self.c(), *arg)
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\MainWindow.py", line 166, in _o
n_contact_selected
    self.on_new_conversation(cid, [contact.account], False)
  File "emesene.py", line 607, in on_new_conversation
    conversation = conv_manager.new_conversation(cid, members)
  File "c:\Users\Shawn\emesene\emesene\gui\base\ConversationManager.py", line 19
9, in new_conversation
    conversation = self.add_new_conversation(self.session, cid, members)
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\ConversationManager.py", line 2
26, in add_new_conversation
    conversation = Conversation(self.session, cid, self.update_window, None, mem
bers)
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\Conversation.py", line 85, in _
_init__
    self.toolbar = ConversationToolbar(toolbar_handler)
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\ConversationToolbar.py", line 4
5, in __init__
    self.draw()
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\ConversationToolbar.py", line 8
3, in draw
    theme_tool_call = utils.gtk_ico_image_load(gui.theme.call, size)
  File "c:\Users\Shawn\emesene\emesene\gui\gtkui\utils.py", line 47, in gtk_ico_
image_load
    iconset = gtk.IconSet(pixbuf)
TypeError: pixbuf should be a GdkPixbuf
```

Full text from git terminal:
http://pastebin.com/7ag8Syaa

Tested on Windows 7.

**Comment by Sbte** [comment]
Just wondering, if you change line 65 of Preferences.py in gui/gtkui from

```
    self.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_MENU)
```

to

```
    self.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DIALOG)
```

does that help? Would be quite funny...

**Comment by c10ud** [comment]
@sbte: reminder: if os.name=="nt" set DIALOG_HINT else the "gnome3 fix"

2011/4/14 syst3mfailur3
reply@reply.github.com:

**Comment by arielj** [comment]
Check my last commit, it's a problem with absolute paths and python for windows, it should be fixed

**Comment by ghost** [comment]
Still blank chat windows, and after opening the first window you cant open a new one once closing the old one.
Maybe Preferences might be is breaking something?

**Comment by c10ud** [comment]
yes, we must set it as Modal but without using that setting otherwise
GNOME3 won't show the X button...

2011/4/14 syst3mfailur3
reply@reply.github.com:
