### ISSUE TITLE
It freezes a couple of seconds before loggin in. 

### ISSUE THREAD

**Issue by kidonaipe** [emesene/emesene#421]
## On ubuntun maverick . 

It happens to me only with my acc . 

the issue goes like this: i sign in normally with my e-mail and password. and while it is loggin in , emesene freezes a couple of seconds , sometimes a minute , and then unfreezes and finally log in . 

the terminal output is the following: 

kidonaipe@kido-M68M-S2P:~/emesene/emesene$ ./emesene 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
No handlers could be found for logger "emesene"
[17:31:36 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[17:31:36 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[17:31:36 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[17:31:36 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[17:31:38 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
Traceback (most recent call last):
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error, None)
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 148, in request_static_tile
    self.get_resource(scheme, host, resource, callback, errback)
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 180, in get_resource
    transport.request(resource, http_headers, method='GET')
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 186, in request
    self._process_queue()
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 163, in _process_queue
    self._setup_transport()
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 99, in _setup_transport
    self._transport.open()
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/iochannel.py", line 150, in open
    if not self._configure():
  File "/home/kidonaipe/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/abstract.py", line 102, in _configure
    (self._host, self._port) )
ValueError: Wrong host or port number : (, 80)
[17:31:40 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 0c b0 0d 00 00 00 00 00 00 00 00 00
d5 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
34 73 79 33 19 94 34 17 d5 02 00 00 00 00 00 00
[17:31:54 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data

I thought it was 'cause i have a thousand of contacts but in emesene 1.6.3 it does not happen.

**Comment by Sbte** [comment]
Your profile is broken. Go to Preferences -> Live Messenger and follow the instructions. After that, never use emesene 1 again, or it will break again.

**Comment by c10ud** [comment]
emesene1 is broken and breaks your msn profile. you must remove
emesene1 entirely and fix your profile with emesene2 through
Preferences-Live Messenger and follow the instructions there. Also,
you should update your papyon submodule as stated in the instructions
for testers

2011/4/15 kidonaipe
reply@reply.github.com:

**Comment by kidonaipe** [comment]
hoy i update my papyon submodule? updating the git repo?

**Comment by Sbte** [comment]
http://emesene-msn.blogspot.com/2010/10/instructions-for-testers.html
