### ISSUE TITLE
error in login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#462]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 171, in failed_cb
    run(errback, error, None)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 148, in request_static_tile
    self.get_resource(scheme, host, resource, callback, errback)
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/ContentRoaming/storage.py", line 180, in get_resource
    transport.request(resource, http_headers, method='GET')
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 186, in request
    self._process_queue()
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 163, in _process_queue
    self._setup_transport()
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/protocol/HTTP.py", line 99, in _setup_transport
    self._transport.open()
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/iochannel.py", line 150, in open
    if not self._configure():
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/abstract.py", line 102, in _configure
    (self._host, self._port) )
ValueError: Wrong host or port number : (, 80)

Do not ask me why or how, but this error happens whenever I connect to the account of my uncle.

**Comment by Sbte** [comment]
Broken profile, for sure this time. You know the instructions.

@c10ud, maybe we can handle this papyon exception inside emesene and make a pop up a dialog telling them to fix their profile? I have no idea how to do that though.

**Comment by Sbte** [comment]
Oh, and after you fix your profile, don't use emesene 1, or it will break again.

**Comment by c10ud** [comment]
i think papyon is not doing the right thing here, it's a bug in some
automagic errback that's called when the get profile request is
issued. we should fix that, but i have no idea on how to properly
reproduce, i don't have a broken account and still, people shouldn't
have a broken profile :(

2011/4/28 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
They shouldn't be people who have been using emesene in the past (emesene 1) most likely have a broken profile. So those people should be warned at least. 

One of my test accounts has a broken profile (did that on purpose). I'll mail you the password if you want.

**Comment by c10ud** [comment]
thanks to zipatei that loaned me his accounts, "fixed" the issue upstream
https://bugs.launchpad.net/ubuntu/+source/papyon/+bug/772326
https://bugs.freedesktop.org/show_bug.cgi?id=36655

2011/4/28 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
Nice, but we still need a way to tell people to fix their profile, or to get papyon to fix it for them :P

**Comment by c10ud** [comment]
it's a manual operation for now, and i'm not sure if i can get the thing to tell if there's some kind of error or something else. i count on the fact that if you care about your avatar etc. you'll read preferences-live messenger
