### ISSUE TITLE
emesene2 don't show incoming messages from previous emesene

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#464]
When I try to comunicate with another person who has the previous emesene, the other person can see my messages but i can't see the incomming messages, i know that the person has wrote to me because i see the text in notifyosd...

**Comment by Sbte** [comment]
Are you using Adium Output or Output Text? If you run emesene from a terminal, what do you see? What operating system do you use?

**Comment by c10ud** [comment]
some debug output? also, your friend shouldn't use emesene1, trust me

**Comment by danielgomon** [comment]
i'm using Adium, which came by default, in Ubuntu 10.04... here is the output of the terminal...

$ emesene
/usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha,base64,random,dispatcher,re
/usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
No handlers could be found for logger "gui.gtkui.Indicator"
[00:04:19 WARNING papyon.protocol.notification] Contact is on both Allow and Block list; removing from Allow list (daniel_go_mon@yahoo.com)
[00:04:19 WARNING e3.common.Config] couldn't load config: /home/maloy/.config/emesene2/messenger.hotmail.com/daniel_go_mon@yahoo.com/config (no file)
[00:04:25 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[00:04:28 ERROR papyon.gnet.HTTP] Received error code 404 (Not Found) from byfiles.storage.msn.com:80
[00:04:28 ERROR papyon.service.content_roaming] Content Roaming service got error: HTTP Error (404): Not Found
[00:04:40 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[00:04:43 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[00:04:52 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[00:04:57 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 85 91 e9 27 00 00 00 00 00 00 00 00
c2 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
13 cc e6 41 ae de ae 04 c2 02 00 00 00 00 00 00
[00:04:59 ERROR papyon.msnp2p.session_manager] Session_id == 0
[00:04:59 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 8a 91 e9 27 00 00 00 00 00 00 00 00
85 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
cb 46 d9 01 b1 de ae 04 85 01 00 00 00 00 00 00
[00:05:56 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'utf8' codec can't decode bytes in position 24-26: invalid data
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), _arg)
  File "/usr/share/emesene/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/usr/share/emesene/emesene/gui/base/Conversation.py", line 285, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 218, in receive_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 96, in add_message
    html = self.theme.format_incoming(msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 93, in format_incoming
    return self.replace(template, msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 138, in replace
    template = template.replace('%sender%', escape(plus_parser.removeMarkup(msg.display_name)))
  File "/usr/share/emesene/emesene/gui/base/Plus.py", line 405, in removeMarkup
    text = unicode(text,'utf8')
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 24-26: invalid data
[00:05:57 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'utf8' codec can't decode bytes in position 24-26: invalid data
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/usr/share/emesene/emesene/gui/base/Conversation.py", line 285, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 218, in receive_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 96, in add_message
    html = self.theme.format_incoming(msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 93, in format_incoming
    return self.replace(template, msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 138, in replace
    template = template.replace('%sender%', escape(plus_parser.removeMarkup(msg.display_name)))
  File "/usr/share/emesene/emesene/gui/base/Plus.py", line 405, in removeMarkup
    text = unicode(text,'utf8')
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 24-26: invalid data
[00:06:06 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'utf8' codec can't decode bytes in position 24-26: invalid data
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/usr/share/emesene/emesene/gui/base/Conversation.py", line 285, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 218, in receive_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 96, in add_message
    html = self.theme.format_incoming(msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 93, in format_incoming
    return self.replace(template, msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 138, in replace
    template = template.replace('%sender%', escape(plus_parser.removeMarkup(msg.display_name)))
  File "/usr/share/emesene/emesene/gui/base/Plus.py", line 405, in removeMarkup
    text = unicode(text,'utf8')
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 24-26: invalid data
[00:06:35 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'utf8' codec can't decode bytes in position 24-26: invalid data
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, **kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/usr/share/emesene/emesene/gui/base/Conversation.py", line 285, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 218, in receive_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 96, in add_message
    html = self.theme.format_incoming(msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 93, in format_incoming
    return self.replace(template, msg, style, cedict, cedir)
  File "/usr/share/emesene/emesene/gui/base/AdiumTheme.py", line 138, in replace
    template = template.replace('%sender%', escape(plus_parser.removeMarkup(msg.display_name)))
  File "/usr/share/emesene/emesene/gui/base/Plus.py", line 405, in removeMarkup
    text = unicode(text,'utf8')
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 24-26: invalid data
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
[00:08:16 WARNING extension] Choosing a default extension for option provider RANDOMLY! --> <class 'emesene.SingleInstanceOption'>
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/Preferences.py", line 790, in _on_extension_changed
    self.session.config.d_extensions[category] = identifier
TypeError: 'NoneType' object does not support item assignment

**Comment by c10ud** [comment]
mmm do you know what the contact was trying to send you? seems there's
some issue decoding the message, maybe some strange characters?

2011/4/29 danielgomon
reply@reply.github.com:

**Comment by Sbte** [comment]
Also, the name of the contact would be useful.

**Comment by danielgomon** [comment]
it's just simple text, no strange characters; the only "unusual" thing is that the person have a Plus colored nickname.... now i've figured out that it doesn't work at all, not only with emesene 1, i can't see any  incoming messages from any client...

**Comment by c10ud** [comment]
then your friend could be using some unhandled char. getting the
complete nick with markup would be real helpful...e.g.
[c=45]whatever[/c]

2011/4/29 danielgomon
reply@reply.github.com:

**Comment by danielgomon** [comment]
this is my friend's nickname:

·#[c=#F960E5]❤ЄℓЄ❤[/c=#F960E5]

**Comment by Sbte** [comment]
```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/gui/gtkui/TextBox.py", line 202, in _on_message_send
    self.on_send_message(self.text)
  File "/home/sven/emesene-dev/emesene/gui/base/Conversation.py", line 268, in _on_send_message
    message, self.emcache.parse(), self.emcache.path, self.first)
  File "/home/sven/emesene-dev/emesene/gui/gtkui/AdiumTextBox.py", line 213, in send_message
    self.view.add_message(msg, message.style, cedict, cedir)
  File "/home/sven/emesene-dev/emesene/gui/gtkui/AdiumTextBox.py", line 105, in add_message
    html = self.theme.format_outgoing(msg, style, cedict, cedir)
  File "/home/sven/emesene-dev/emesene/gui/base/AdiumTheme.py", line 119, in format_outgoing
    return self.replace(template, msg, style, cedict, cedir)
  File "/home/sven/emesene-dev/emesene/gui/base/AdiumTheme.py", line 138, in replace
    template = template.replace('%sender%', escape(plus_parser.removeMarkup(msg.display_name)))
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 405, in removeMarkup
    text = unicode(text,'utf8')
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 24-26: invalid data
```

Fails only with exactly that name. Using parts of it all worked.

**Comment by c10ud** [comment]
now, sbte, do you like plus markups? :D

**Comment by Sbte** [comment]
No, I hate them. That's why I remove them.
