### ISSUE TITLE
Adding myself

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#485]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 131, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 875, in _handle_action_add_to_group
    done_cb=tuple([add_to_group_succeed, gid]), failed_cb=tuple([add_to_group_fail]))
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/address_book.py", line 325, in add_messenger_contact
    old_memberships = (contact and contact.memberships) or Membership.NONE
AttributeError: 'Profile' object has no attribute 'memberships'

**Comment by c10ud** [comment]
actually this is a bug in papyon

```
def add_messenger_contact(self, account, invite_display_name='',
        invite_message='', groups=[], network_id=NetworkID.MSN,
        auto_allow=True, done_cb=None, failed_cb=None):
    def callback(contact_infos, memberships):
        c = self.__build_or_update_contact(account, network_id,
                memberships, contact_infos)
        self.__common_callback('messenger-contact-added', done_cb, c)
        for group in groups:
            self.add_contact_to_group(group, c)

    contact = self.search_contact(account, network_id)
    old_memberships = (contact and contact.memberships) or Membership.NONE

    if contact is self._client.profile:
        return # can't add ourself to the address book
```

i guess the check should be before the old_membership thing

**Comment by c10ud** [comment]
still, seems like you can't add yourself with papyon :D

**Comment by c10ud** [comment]
[17:08] <c10ud> https://bugs.freedesktop.org/show_bug.cgi?id=36774

bug upstream
