### ISSUE TITLE
cannot log in 1.6.3 anymore 

### ISSUE THREAD

**Issue by pengshao** [emesene/emesene#491]
Today afternoon when I was using emesene it suddenly crashed up, after that time I cannot login it anymore. Every time I started the program I received the following message:

Exception
You are using emesene 1.6.3 - "Uberlândia" so you're free to complain here:
http://forum.emesene.org/index.php/board,19.0.html
Check already existing tickets for duplicates first, please.
Traceback (most recent call last):

  File "/usr/share/emesene/PluginManager.py", line 257, in startActivePlugins
    self.startPlugin(name)

  File "/usr/share/emesene/PluginManager.py", line 232, in startPlugin
    self.loaded_plugin[ name ].start()

  File "/usr/share/emesene/plugins_base/IdleStatus.py", line 62, in start
    if self.msn.status == "IDL":

AttributeError: 'NoneType' object has no attribute 'status'

Thank you.

**Comment by c10ud** [comment]
use emesene2

**Comment by pengshao** [comment]
thx.
