### ISSUE TITLE
Problem with Menu: An integer is required

### ISSUE THREAD

**Issue by saguar** [emesene/emesene#51]
I'm running last Mariano's repo and I get this error when I try to open preferences:

Traceback (most recent call last):
  File "/home/saverio/emesene2/emesene/gui/gtkui/MainMenu.py", line 157, in <lambda>
    lambda *args: self.handler.on_preferences_selected())
  File "/home/saverio/emesene2/emesene/gui/base/Handler.py", line 100, in on_preferences_selected
    Preferences(self.session).show()
  File "/home/saverio/emesene2/emesene/gui/gtkui/Preferences.py", line 86, in **init**
    self.interface = Interface(session)
  File "/home/saverio/emesene2/emesene/gui/gtkui/Preferences.py", line 379, in **init**
    'session.config.b_toolbar_small')
  File "/home/saverio/emesene2/emesene/gui/gtkui/Preferences.py", line 228, in append_check
    widget.set_active(default)
TypeError: an integer is required

**Comment by c10ud** [comment]
rm -rf ~/.config/emesene2

and don't use his branch, he does evil stuff with git

**Comment by c10ud** [comment]
reopening, this happens with a test account of mine. WTF

**Comment by c10ud** [comment]
problem is: until you open a conversation, the value isn't set and it's returned as None. wariano? i'm unsure on the _proper_ solution

**Comment by marianoguerra** [comment]
see if my latest push works

**Comment by c10ud** [comment]
closing ololol
