### ISSUE TITLE
Error on mac os x snow leopard

### ISSUE THREAD

**Issue by Metflar** [emesene/emesene#513]
Error: 1. Traceback (most recent call last):
  File "/Applications/emesene.app/Contents/Resources/emesene/emesene.py", line 60, in <module>
    import e3
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/**init**.py", line 3, in <module>
    import common
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/common/**init**.py", line 22, in <module>
    import play_sound
  File "/Applications/emesene.app/Contents/Resources/emesene/e3/common/play_sound.py", line 41, in <module>
    from AppKit import NSSound
  File "/Library/Python/2.6/site-packages/pyobjc_framework_Cocoa-2.2b1-py2.6-macosx-10.6-universal.egg/AppKit/**init**.py", line 10, in <module>
    from Foundation import *
  File "/Library/Python/2.6/site-packages/pyobjc_framework_Cocoa-2.2b1-py2.6-macosx-10.6-universal.egg/Foundation/**init**.py", line 10, in <module>
    from CoreFoundation import *
  File "/Library/Python/2.6/site-packages/pyobjc_framework_Cocoa-2.2b1-py2.6-macosx-10.6-universal.egg/CoreFoundation/**init**.py", line 17, in <module>
    scan_classes=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 147, in initFrameworkWrapper
    _parseBridgeSupport(data, globals, frameworkName, inlineTab=inlineTab)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 58, in _parseBridgeSupport
    objc.parseBridgeSupport(data, globals, frameworkName, _args, *_kwds)
SyntaxError: Syntax error for struct CFSocketSignature

**Comment by marianoguerra** [comment]
we don't use that library, does it affect emesene's functionality?

**Comment by Metflar** [comment]
emesene don't run

**Comment by Metflar** [comment]
nothing?

**Comment by ghost** [comment]
Did you just download the zipball from github or did you download an actual OS X build from http://sidhosting.co.uk?

Okay, first run the uninstaller located in /Applications
Download the latest DMG from http://sidhosting.co.uk/emesene and copy the app to /Applications
Open it
If it doesn't work look on the ~/Desktop for a file called emesene error log.txt and paste that here

I have never seen an error output like yours before :/

I thinks its PyObjC interfering with emesene

**Comment by Metflar** [comment]
python emeseneTraceback (most recent call last):
  File "emesene", line 32, in <module>
    import emesene
  File "/Users/giordanocristini/emesene/emesene/emesene.py", line 51, in <module>
    import glib
ImportError: No module named glib

**Comment by ghost** [comment]
Right now that seems to be a missing GTK error

Open Terminal and run:

rm /Library/Python/2.6/site-packages/gtkredirect.pth > /dev/null 2>&1

It may give you an error. Then run:

echo "import site; site.addsitedir('/Applications/emesene.app/Contents/Resources/gtk/inst/lib/python2.6/site-packages')" > /Library/Python/2.6/site-packages/gtkredirect.pth

Now open the DMG from sidhosting.co.uk and drag emesene.app into /Applications

Then open /Applications/emesene.app

Hopefully it should work.

**Comment by Metflar** [comment]
thanks but it give me the same error...

**Comment by ghost** [comment]
Hmm i cant understand why. The above commands should work. 

Can you run in Terminal:

rm /Applications/emesene.app/Contents/Resources/installdone
sh /Applications/emesene.app/Contents/Resources/payload/install.sh

And post the output

Do you have not system python e.g a version you have installed yourself?

**Comment by Metflar** [comment]
sh /Applications/emesene.app/Contents/Resources/payload/install.sh
Starting emesene install check...
emesene is located in /Applications. Checking install status...
emesene has not been installed...
Installing dependencies. This may take a few seconds...
Done...
Launching emesene...
and emesene doesn't work

i have python 2.6.6 and 2.6.5

**Comment by ghost** [comment]
Thats why then, My bundled PyGTK is compiled for Python 2.6.1, which is the default on Snow Leopard systems. I can only recommend trying to find a version of PyGTK that has been compiled for your Python version.

**Comment by c10ud** [comment]
closing issue for bugtracker readability (and not-emesene related)
