### ISSUE TITLE
Errors in login.. Emesene unusable

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#529]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 493, in on_login_succeed
    self.draw_main_screen()
  File "/home/andre/emesene/emesene/emesene.py", line 421, in draw_main_screen
    self.tray_icon.quit_on_close)
AttributeError: 'Indicator' object has no attribute 'quit_on_close'

and:
[18:01:57 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/emesene.py", line 589, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'

**Comment by zipatei** [comment]
Thanks Sbte...
