### ISSUE TITLE
No Preferences Window before open a conversation Window

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#53]
The Preferences Window don't open until I open some conversation Window...

<pre>
Traceback (most recent call last):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene-mariano/emesene/gui/gtkui/MainMenu.py", line 157, in <lambda>
    lambda *args: self.handler.on_preferences_selected())
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene-mariano/emesene/gui/base/Handler.py", line 100, in on_preferences_selected
    Preferences(self.session).show()
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene-mariano/emesene/gui/gtkui/Preferences.py", line 86, in __init__
    self.interface = Interface(session)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene-mariano/emesene/gui/gtkui/Preferences.py", line 379, in __init__
    'session.config.b_toolbar_small')
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene-mariano/emesene/gui/gtkui/Preferences.py", line 228, in append_check
    widget.set_active(default)
TypeError: an integer is required
</pre>

Regards!

**Comment by c10ud** [comment]
ping mariano

**Comment by arielj** [comment]
I don't have this issue, I removed config, logged in and I was able to enter preferences without problems.

**Comment by c10ud** [comment]
ok

**Comment by c10ud** [comment]
closing

**Comment by EibrielInv** [comment]
Woks now :)
