### ISSUE TITLE
it just stop working

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#531]
i'm using it, and then i can't send and can't receive anything

here what goes on terminal

Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError
[22:45:01 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 d0 29 05 00 00 00 00 00 00 00 00 00
da 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
6f 18 33 70 d8 d9 72 44 da 02 00 00 00 00 00 00

i'm using Ubuntu 11.04
and emesene 2.11.5-devel

**Comment by c10ud** [comment]
you're just not connected, restart emesene and it will work
