### ISSUE TITLE
Error on startup:  IndexError: list index out of range

### ISSUE THREAD

**Issue by imran-iq** [emesene/emesene#534]
Exception
You are using emesene 1.6.3 - "Uberlândia" so you're free to complain here:
http://forum.emesene.org/index.php/board,19.0.html
Check already existing tickets for duplicates first, please.
Traceback (most recent call last):

  File "/usr/share/emesene/emesenelib/soap/manager.py", line 139, in process
    return process()

  File "/usr/share/emesene/emesenelib/soap/manager.py", line 76, in process
    response.callback(response, *response.args)

  File "/usr/share/emesene/emesenelib/ProfileManager.py", line 155, in onGetProfile
    photo = response.body.split('</Photo>')[0].split('<Photo>')[1]

IndexError: list index out of range

I get that every time i start up emesene, also name remains as email instead of what was previously set and status message does not update either

**Comment by ghost** [comment]
Update to emesene 2.11.4.

**Comment by c10ud** [comment]
^
