### ISSUE TITLE
blank contact screen emesene 2 ubuntu

### ISSUE THREAD

**Issue by jjnilton** [emesene/emesene#551]
after clicking 'connect' button to enter in my emesene account i got this blank contact screen:

log in terminal:

jj@jj-linux:~$ emesene
[15:02:39 WARNING papyon.p2p] Trying to publish an empty MSNObject
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), _arg)
  File "/usr/share/emesene/emesene/emesene.py", line 471, in on_login_succeed
    self.draw_main_screen()
  File "/usr/share/emesene/emesene/emesene.py", line 416, in draw_main_screen
    self.on_new_conversation, self.on_close, self.on_user_disconnect)
  File "/usr/share/emesene/emesene/gui/gtkui/Window.py", line 98, in go_main
    on_close, on_disconnect)
  File "/usr/share/emesene/emesene/gui/gtkui/MainWindow.py", line 70, in **init**
    self.panel = UserPanel(session)
  File "/usr/share/emesene/emesene/gui/gtkui/UserPanel.py", line 83, in **init**
    True)
  File "/usr/share/emesene/emesene/gui/gtkui/TextField.py", line 58, in **init**
    self.text = self._text or self.empty_text
  File "/usr/share/emesene/emesene/gui/gtkui/TextField.py", line 114, in _set_text
    gobject.markup_escape_text(self._text or self.empty_text)))
TypeError: glib.markup_escape_text() argument 1 must be string or read-only buffer, not tuple
[15:02:40 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, **kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene/emesene.py", line 566, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'
[15:02:41 WARNING papyon.p2p] Trying to publish an empty MSNObject

**Comment by Sbte** [comment]
What is your personal message?

**Comment by jjnilton** [comment]
is the song that i'm playing, i think it was the problem, some conflict between nowplaying plugin of wlm and emesene

**Comment by Sbte** [comment]
What music player are you using?

**Comment by jjnilton** [comment]
foobar2000 on windows...

and another issue: when i clear chat window, my sent messages no longer appear until my contact talk to me:

/usr/share/emesene/emesene/gui/gtkui/**init**.py:102: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[12:43:48 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 8a 77 ac 2b 00 00 00 00 00 00 00 00
48 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
2a f1 e1 25 04 1f b3 4e 48 01 00 00 00 00 00 00
*\* Message: console message: undefined @0: TypeError: 'null' is not an object

*\* Message: console message: undefined @0: TypeError: 'null' is not an object

[12:44:29 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 9e 62 b9 56 00 00 00 00 00 00 00 00
48 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
9b fc ad 0f ce 46 6a 53 48 01 00 00 00 00 00 00

**Comment by Sbte** [comment]
That error has been fixed in the most recent development version.

**Comment by jjnilton** [comment]
how do I get it?
