### ISSUE TITLE
Another cid notification bug

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#554]
```
[15:21:19 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 1305722667.130878
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/gui/gtkui/MessagingMenu.py", line 110, in _on_message
    conv = conv_manager.conversations[cid]
KeyError: 1305722667.130878
[15:21:19 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'message_waiting'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/e3/common/notification.py", line 111, in _on_message
    conversation.message_waiting:
AttributeError: 'NoneType' object has no attribute 'message_waiting'
```

I get this almost every day. No clue where it comes from. Seems to me that the cid is still not properly reassigned.

**Comment by c10ud** [comment]
notification is checking on a dead conversation, notifications really are a mess, wow m3n

**Comment by arielj** [comment]
maybe this was caused because of the problem unsubscribing functions from signals? some signal never got unsubscribed, the object got deleted and the callback was still called?

@Sbte, does it still happen? if not, I vote to close this issue until it's repeating again :P

**Comment by Sbte** [comment]
Awesome idea arielj. Anyway, it happens very rarely. But it seems logical to me that that bug was the cause. I'll just reopen if it happens again.
