### ISSUE TITLE
Contact list empty

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#578]
After updating to the latest emesene from git
the following exception appears and contact list empty
Traceback (most recent call last):
  File "/home/ammar/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/ammar/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
TypeError: _on_mail_count_changed() takes exactly 2 arguments (1 given)

**Comment by c10ud** [comment]
there have been major changes, we're looking into the issue, meanwhile revert to some older commit

**Comment by c10ud** [comment]
fixed by mariano
