### ISSUE TITLE
Adium : No message when receiving a nudge

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#590]
When sending a nudge, I get the message "You jut sent a nudge", but when I receive one, I see no message, only a system notification in the upper right corner ( ubuntu )

Error: 

<pre>[09:51:59 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'str' object has no attribute 'display_name'
[09:51:59 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'str' object has no attribute 'display_name'
Traceback (most recent call last):
  File "/home/echo/emesene-emesene-2595e78/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/echo/emesene-emesene-2595e78/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/Conversation.py", line 293, in on_receive_message
    _('%s just sent you a nudge!') % (contact.display_name,))
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/gtkui/AdiumTextBox.py", line 256, in information
    msg = gui.Message.from_information(contact, message)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/Message.py", line 72, in from_information
    message.display_name if message.display_name else contact.display_name,
AttributeError: 'str' object has no attribute 'display_name'
[09:51:59 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'str' object has no attribute 'display_name'
[09:51:59 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'str' object has no attribute 'display_name'
Traceback (most recent call last):
  File "/home/echo/emesene-emesene-2595e78/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/echo/emesene-emesene-2595e78/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/ConversationManager.py", line 75, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/Conversation.py", line 293, in on_receive_message
    _('%s just sent you a nudge!') % (contact.display_name,))
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/gtkui/AdiumTextBox.py", line 256, in information
    msg = gui.Message.from_information(contact, message)
  File "/home/echo/emesene-emesene-2595e78/emesene/gui/base/Message.py", line 72, in from_information
    message.display_name if message.display_name else contact.display_name,
AttributeError: 'str' object has no attribute 'display_name'</pre>

Edit: And yes, the 2nd contact has no nickname,  only the mail address, I don't think it happens with contacts having their nickname set properly.

**Comment by pepeleproso** [comment]
Sbte fix this yesterday, try with lastest git.

**Comment by Sbte** [comment]
Yes, I usually fix bugs the day before they get reported. Please tell if you find any more bugs ;)

Closed by d59af023afa4f804f79b49ecec7c7764cb1aed05
