### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#593]
i was just talking on emesene, then i notice i stop recieving messages, then i take a look at terminal, and that's what happens

Traceback (most recent call last):
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 239, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack, callback)
  File "/home/alexandre2/emesene/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError

it keep appering all the time, just like an infinity loop, i disconneted, and connected again, and worked...
but it's not the first time that it happens...

i'm using emesene 2.11.5-devel on Ubuntu 11.04

**Comment by EchoUSB** [comment]
It happened to me too when I had a really bad wifi.
I think it's because you are actually disconnected but emesene thinks you are connected.
But maybe I'm wrong

**Comment by Sbte** [comment]
Just got it too. No Wifi issue.

https://bugs.freedesktop.org/show_bug.cgi?id=36258

**Comment by c10ud** [comment]
original issue should have been fixed

try with papyon-0.5.6 (currently unreleased) we will probably make emesene-2.11.8 dependent on that version
