### ISSUE TITLE
Multichat emoticon issue

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#599]
In multichat, I don't receive emoticons from other contacts when they are not in my contacts. Only see a square.

<pre>
[17:28:48 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[17:28:48 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[17:28:48 ERROR papyon.p2p] MSN Object creator is not in address book
[17:28:48 ERROR papyon.p2p] MSN Object creator is not in address book
[17:28:48 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'nick'
[17:28:48 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'nick'
Traceback (most recent call last):
  File "/home/echo/emesene-emesene-3862535/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/echo/emesene-emesene-3862535/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/echo/emesene-emesene-3862535/emesene/e3/common/notification.py", line 118, in _on_message
    self._notify(contact, contact.nick , text, contact.account, None)
AttributeError: 'NoneType' object has no attribute 'nick'
</pre>

**Comment by GVisconti84** [comment]
Mmmmmhhh I may be wrong, since it has been a long time since last time I used it, but.... Doesn't this happen in the official client too?

**Comment by Sbte** [comment]
Maybe, but the error shouldn't happen for sure. Maybe if we fix that, we also fix the issue.

**Comment by c10ud** [comment]
iirc you can't do p2p with contacts who are not in your contact list, anyway the error is just because contact object is none and notifications try to use it .. message.display_name can be used instead

**Comment by Sbte** [comment]
Partial fix. Next error is in logger, but I have no idea how it should be handled there...

**Comment by c10ud** [comment]
i'll close this issue, please open a new one for the logger breaking
