### ISSUE TITLE
emesene Qt4: AttributeError: 'TopLevelWindow' object has no attribute 'maximize'

### ISSUE THREAD

**Issue by matthewgall** [emesene/emesene#609]
On emesene 2.11.5-0+emesene1 running on Ubuntu 11.04, attempting to run emesene using "emesene -e main:qt4_main" results in the following error:

matthew@matthew-laptop:~$ emesene -e main:qt4_main
Traceback (most recent call last):
  File "/usr/bin/emesene", line 34, in <module>
    emesene.main()
  File "/usr/share/emesene/emesene/emesene.py", line 805, in main
    main_method(Controller)
  File "/usr/share/emesene/emesene/gui/qt4ui/**init**.py", line 42, in qt4_main
    controller.start()
  File "/usr/share/emesene/emesene/emesene.py", line 236, in start
    self._set_location(self.window)
  File "/usr/share/emesene/emesene/emesene.py", line 484, in _set_location
    window.maximize()
AttributeError: 'TopLevelWindow' object has no attribute 'maximize'

Currently installed python-qt4, version 4.8.3-2

**Comment by GVisconti84** [comment]
Should be fixed. Could you try again with latest git version?

**Comment by matthewgall** [comment]
Just pulled the latest git, issue resolved.
