### ISSUE TITLE
Emesene2 doesn't connect but disconnects other clients

### ISSUE THREAD

**Issue by elzoona** [emesene/emesene#648]
In short: Emesene2 doesn't connect, doesn't show anything, but if I'm connected in other client (for example, Emesene1.6) this disconnects because it says "Connected from another location". Emesene2 only shows the "connecting" animation, and nothing more happens.

Emesene 2.11.5 (Archlinux package emesene2 2.11.5-1)
Papyon 0.5.5 (Archlinux package papyon 0.5.5-1)
Python2 2.7.1 (Archlinux package python2 2.7.1-9)

Console log: 

[elzoona]$ emesene2 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
[13:35:21 WARNING emesene] Errors occurred while importing jabber backend: No module named xmpp
[13:35:42 ERROR papyon.service] SOAP Parse Error: invalid xml+soap data
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 215, in _response_handler
    soap_response = SOAPResponse(decoded_body)
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 128, in __init__
    raise SOAPParseError("invalid xml+soap data", soap_data)
SOAPParseError: SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papyon.service] SOAP Parse Error: invalid xml+soap data
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 215, in _response_handler
    soap_response = SOAPResponse(decoded_body)
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 128, in __init__
    raise SOAPParseError("invalid xml+soap data", soap_data)
SOAPParseError: SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papyon.service] Couldn't build or process SOAP response
[13:35:42 ERROR papyon.service] Couldn't build or process SOAP response
[13:35:42 ERROR papylib.Events] Client got an error handling addressbook: 4 SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papylib.Events] Client got an error handling addressbook: 4 SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papyon.service] SOAP Parse Error: invalid xml+soap data
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 215, in _response_handler
    soap_response = SOAPResponse(decoded_body)
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 128, in __init__
    raise SOAPParseError("invalid xml+soap data", soap_data)
SOAPParseError: SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papyon.service] SOAP Parse Error: invalid xml+soap data
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 215, in _response_handler
    soap_response = SOAPResponse(decoded_body)
  File "/usr/lib/python2.7/site-packages/papyon/service/SOAPService.py", line 128, in __init__
    raise SOAPParseError("invalid xml+soap data", soap_data)
SOAPParseError: SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papyon.service] Couldn't build or process SOAP response
[13:35:42 ERROR papyon.service] Couldn't build or process SOAP response
[13:35:42 ERROR papylib.Events] Client got an error handling addressbook: 4 SOAP Parse Error: invalid xml+soap data
[13:35:42 ERROR papylib.Events] Client got an error handling addressbook: 4 SOAP Parse Error: invalid xml+soap data
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/gnet/parser.py", line 180, in _on_status_change
    self.__emit_result()
  File "/usr/lib/python2.7/site-packages/papyon/gnet/parser.py", line 212, in __emit_result
    response.parse(self._receive_buffer)
  File "/usr/lib/python2.7/site-packages/papyon/gnet/message/HTTP.py", line 153, in parse
    start_line, message = chunk.split("\r\n", 1)
ValueError: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/papyon/gnet/parser.py", line 180, in _on_status_change
    self.__emit_result()
  File "/usr/lib/python2.7/site-packages/papyon/gnet/parser.py", line 212, in __emit_result
    response.parse(self._receive_buffer)
  File "/usr/lib/python2.7/site-packages/papyon/gnet/message/HTTP.py", line 153, in parse
    start_line, message = chunk.split("\r\n", 1)
ValueError: need more than 1 value to unpack

**Comment by c10ud** [comment]
..and yet another address book error - some other people experienced
this, but talking with upstream we haven't been able to identify the
cause yet :(

2011/6/11 elzoona
reply@reply.github.com:

**Comment by elzoona** [comment]
Closed, duplicated. Sorry!

https://github.com/emesene/emesene/issues/510
