### ISSUE TITLE
Trillian causes emesene2 to misbehave?

### ISSUE THREAD

**Issue by Soulsuke** [emesene/emesene#685]
Allright, I really  dunno what's causing this problem, but here it goes. Emesene2 is working well with all my contacts, BUT one. His avatar isn't loaded at all, everytime i send him a message i get flooded with 'error sending message' errors (it gets printed 4 times whenever i send the message, then it gets printed over and over after that, about 1 line very 4-5 seconds), and after a while emesene2 actually freezes. The funny part is that he actually receives the messages i send, and vice versa. To make it everything worse, this doesn't happen if I use any other messenger program (emesene1, pidgin, amsn), I don't have any connection problem (did a full checkup) and neither does he.

I don't know if this may be the cause, but he uses Trillian Astra 4.2 and (so far) is the only one giving me such problems.

This is the shell output I get (since i start emesene to right before the freeze):

$ emesene2 <<< just an alias
[18:47:34 ERROR root] Could not find any typelib for Unity
[18:47:34 ERROR root] Could not find any typelib for Dbusmenu
/usr/lib/python2.6/dist-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
/opt/share/emesene2/emesene/gui/gtkui/**init**.py:107: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[18:47:49 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[18:47:49 WARNING papyon.p2p] Unknown MSN object, another end point might have it
[18:47:49 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
[18:47:49 ERROR papyon.msnp2p.session_manager] No handler could handle euf-guid {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}
/opt/share/emesene2/emesene/gui/gtkui/Dialog.py:678: Warning: g_object_set_qdata: assertion`G_IS_OBJECT (object)' failed
  InviteWindow(session, callback).show()
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:21 ERROR papylib.Events] Error sending message: 4 1
[18:48:30 ERROR papylib.Events] Error sending message: 4 1
[18:48:30 ERROR papylib.Events] Error sending message: 4 1
/opt/share/emesene2/emesene/gui/gtkui/**init**.py:107: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()
[18:48:40 ERROR papylib.Events] Error sending message: 4 1
[18:48:40 ERROR papylib.Events] Error sending message: 4 1
[18:48:49 ERROR papyon.msnp2p.session_manager] 

Then the following message gets repeated over and over and emesene2 freezes:

Traceback (most recent call last):
  File "/opt/share/emesene2/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 98, in process_pending_queues
    self._process_pending_queues()
  File "/opt/share/emesene2/emesene/e3/papylib/papyon/papyon/switchboard_manager.py", line 236, in _process_pending_queues
    transaction_id = self.switchboard.send_message(message, ack)
  File "/opt/share/emesene2/emesene/e3/papylib/papyon/papyon/msnp/switchboard.py", line 171, in send_message
    assert(self.state == ProtocolState.OPEN)
AssertionError

**Comment by c10ud** [comment]
please run emesene -vvv and let the papyon devs know of this

**Comment by pepeleproso** [comment]
maybe same as https://bugs.freedesktop.org/show_bug.cgi?id=36258?

**Comment by c10ud** [comment]
i think it's different here: i guess something bad happens with the
switchboard till the server disconnects papyon in some weird manner..

2011/6/27 pepeleproso
reply@reply.github.com:

**Comment by Soulsuke** [comment]
Sorry for the delay, I've been out for a while... Now, I've been trying to replicate the issue, but things got a little weird: I updated emesene2 and I was still experiencing the same issue with the same contact, but after deleting my user config file, the Assertion Error thing stopped (while the avatar of contacts using trillian still isn't shown properly). Point is, I haven't manually edited the file (besides the changes to a single line as i explained in bug #676, setting the transfers directory), so I can't explain what was causing the issue

**Comment by Soulsuke** [comment]
Ok, the problem suddenly started to happen again, this time i managed to save the logs of emesene -vvv:
https://rapidshare.com/files/3406032495/log0_-_error_sending_message <<< log of when the window gets spammed with "error sending message" errors, while both me and the contact using Trillian are actually receiving them correctly
https://rapidshare.com/files/1928155211/log1_-_crash <<< log of when the crash occurs

**Comment by Sbte** [comment]
Did you report this to the papyon devs yet?

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by Soulsuke** [comment]
Sorry, kind of forgot about it...

https://bugs.freedesktop.org/show_bug.cgi?id=39471

**Comment by c10ud** [comment]
p2p bug in trillian (imho)

**Comment by c10ud** [comment]
closing because we can do little here and upstream responds ;)

**Comment by c10ud** [comment]
[15:13] <c10ud> lfrb, about the trillian "bug": when we leave a switchboard its state is set to ProtocolState.CLOSING..so why not ProtocolState.CLOSED? Also when papyon tries to reuse the switchboard in switchboard_manager, it doesn't set the state to ProtocolState.OPEN so here's the infinite looping
[15:13] <c10ud> This maybe a trillian bug because it's sending p2p data even if we sent OUT, but still papyon shouldn't break
[15:13] <c10ud> and i think this re-use thing has something wrong

**Comment by Soulsuke** [comment]
So... Since nobody on papyon's bug tracker is answering... Any news about this? Blocking contacts each time I (or them) log out is getting annoying...

**Comment by Soulsuke** [comment]
It's been 6 months and this issue is still there; there are no answers from upstream papyon, and since you're now using a custom version of it, could somebody at least tell me the status of this bug? Is there a chance it'll get fixed?

**Comment by c10ud** [comment]
sbte fixed the assertion errors already.. for the other stuff, we need
someone able to test with trillian

2011/12/3 Soulsuke
reply@reply.github.com:

**Comment by Soulsuke** [comment]
I'll gladly volunteer as a guinea pig for this, just tell me what to do :p
