### ISSUE TITLE
another filetransfer issue

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#690]
1- sender send a file transfer invitation
2- sender cancel that invitation
3- you don't notice that and click cancel filetransfer button, and you get

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/home/pepe/emesene-main/emesene/e3/papylib/Worker.py", line 132, in run
    self._process_action(action)
  File "/home/pepe/emesene-main/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/pepe/emesene-main/emesene/e3/papylib/Worker.py", line 1351, in _handle_action_ft_cancel
    self.rfiletransfers[t].cancel()
  File "/usr/lib/pymodules/python2.7/papyon/msnp2p/filetransfer.py", line 74, in cancel
    self._close()
  File "/usr/lib/pymodules/python2.7/papyon/msnp2p/session.py", line 239, in _close
    self._dispose()
  File "/usr/lib/pymodules/python2.7/papyon/msnp2p/session.py", line 275, in _dispose
    self._session_manager._unregister_session(self)
  File "/usr/lib/pymodules/python2.7/papyon/msnp2p/session_manager.py", line 79, in _unregister_session
    del self._sessions[session.id]
  File "/usr/lib/python2.7/UserDict.py", line 25, in __delitem**
    def **delitem**(self, key): del self.data[key]
KeyError: 2132216729

4- papyon it's complete broken after that, you had to restart emesene.

we need to process file transfer cancel signals from papyon and remove that transfer automatically.

**Comment by pepeleproso** [comment]
I have a working patch in my tree
https://github.com/pepeleproso/emesene/commit/bbbadcf5f21acad16d4cb82e69d47058ea8d106e

but @c10ud could take a look?

**Comment by zipatei** [comment]
works the first time you click cancel ... the second time no longer works

reproduce:
1) Receive two transfer
2) Click cancel one transfer
3) after, click cancel another transfer
