### ISSUE TITLE
Exception on login

### ISSUE THREAD

**Issue by hit** [emesene/emesene#7]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in **bootstrap_inner
    self.run()
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/Worker.py", line 167, in run
    self._process(data)
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/Worker.py", line 207, in _process
    self._process_login(message)
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/Worker.py", line 216, in _process_login
    handler(message)
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/Worker.py", line 395, in _on_user
    succeed = self.do_passport_identification()
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/Worker.py", line 292, in do_passport_identification
    self.session.extras.update(SSoParser(data).tokens)
  File "/home/hit/Apps/emesene2/mesinyer/e3/msn/XmlParser.py", line 192, in __init**
    self.parser.Parse(xml_raw)
ExpatError: syntax error: line 1, column 0

**Comment by marianoguerra** [comment]
can you add a print xml_raw before the last line XmlParser.py", line 192 and paste the result?

**Comment by hit** [comment]
result: 500

**Comment by cando** [comment]
an user has the same error and he says that it happens only with @msn.com accounts...hope this helps..

**Comment by c10ud** [comment]
```
    if '@msn.com' not in self.session.account.account:
        server = "login.live.com"
        url = "/RST.srf"
    else:
        server = "msnia.login.live.com"
        url = "/pp550/RST.srf"
```

now everyone uses the same server, that "else" is deprecated

**Comment by marianoguerra** [comment]
fixed
