### ISSUE TITLE
Two error in chat

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#705]
1) I think this error should be the webcam in chat window

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 132, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 181, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 1397, in _handle_action_call_invite
    ca = e3.base.Call(papysession, papycontact.account)
AttributeError: 'NoneType' object has no attribute 'account'

2) I dont know...
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Conversation.py", line 474, in rotate_picture
    contact = self.session.contacts.get(self.members[self.index])
IndexError: list index out of range

**Comment by Sbte** [comment]
Fixed the second error.

About the first: Was this during a group chat?

**Comment by c10ud** [comment]
"fixed" the 1st error...
[16:15] <CIA-83> Riccardo (C10uD) master rd05f2bd
[16:15] <CIA-83> papylib: disable audio/video calls since we don't have the codecs available in
[16:15] <CIA-83> gstreamer (and there's still no other foss implementation yet) -
[16:15] <CIA-83> https://github.com/emesene/emesene/commit/d05f2bd4a52257fb75006b8c9772abf75367bc08
