### ISSUE TITLE
File transfer issue (button)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#710]
Reproduce:
1. Open conversation
2. Click button for choose file

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/ConversationToolbar.py", line 131, in <lambda>
    lambda *args: self.handler.on_invite_file_transfer_selected())
  File "/home/andre/emesene/emesene/gui/base/Handler.py", line 560, in on_invite_file_transfer_selected
    self.dialog.choose_file(os.path.expanduser("~"), open_file_cb)
NameError: global name 'os' is not defined

**Comment by Mystro256** [comment]
I would suspect perhaps the "os" was removed by accident, as complained in the last line.
