### ISSUE TITLE
Fail in the notification that should notify users of failures

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#712]
[22:41:47 ERROR papylib.Events] Error sending message: 4 1
[22:41:47 ERROR papylib.Events] Error sending message: 4 1
[22:41:47 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 06 45 92 78 00 00 00 00 00 00 00 00
ca 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
29 bf 38 71 d0 8c dd 37 ca 02 00 00 00 00 00 00
[22:41:47 WARNING papyon.msnp2p.transport.switchboard] Invalid TLP chunk in SB message: TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 06 45 92 78 00 00 00 00 00 00 00 00
ca 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
29 bf 38 71 d0 8c dd 37 ca 02 00 00 00 00 00 00
[22:41:47 WARNING e3.common.Signal] Signal handler (_on_message_send_failed._on_message_send_failed) error: 'str' object has no attribute 'display_name'
[22:41:47 WARNING e3.common.Signal] Signal handler (_on_message_send_failed._on_message_send_failed) error: 'str' object has no attribute 'display_name'
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/usr/share/emesene/emesene/gui/base/ConversationManager.py", line 108, in _on_message_send_failed
    conversation.on_send_message_failed(error)
  File "/usr/share/emesene/emesene/gui/base/Conversation.py", line 302, in on_send_message_failed
    _('Error delivering message'))
  File "/usr/share/emesene/emesene/gui/gtkui/AdiumTextBox.py", line 256, in information
    msg = gui.Message.from_information(contact, message)
  File "/usr/share/emesene/emesene/gui/base/Message.py", line 72, in from_information
    message.display_name if message.display_name else contact.display_name,
AttributeError: 'str' object has no attribute 'display_name'
[22:41:49 ERROR papyon.msnp2p.session_manager] Session_id == 0
[22:41:49 ERROR papyon.msnp2p.session_manager] Session_id == 0

**Comment by Sbte** [comment]
Oh, wait. forgot to mention that this is on my laptop, and didn't have time to look if this was already fixed in 2.11.6-dev. Just posting it here so I don't forget.

**Comment by Sbte** [comment]
Yeah, seems fixed already
