### ISSUE TITLE
Custom emoticons received not showing and "eating" next line-break

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#713]
An image explains better than words:
![screenshot sample](http://img837.imageshack.us/img837/9163/screenshot3ej.png)

Thor is the guy whom I'm talking and igorsantos07@gmail.com is me.
He sent me a custom emoticon, and the message came empty. When another thing is said, the message is not wraped to the next line.

I can send custom emoticons normally and default emoticons are not affected.

**Comment by Mystro256** [comment]
I can't confirm this, I don't seem to have any issue with custom emotions, sending or receiving (tested with 2.11.5+). Can you give any more information to help replicate this?

**Comment by igorsantos07** [comment]
No more info right now :|
I'll try to run emesene from the command line and see if there is any info
there about that, and add it here.

I'm running Mint 11 (Ubuntu 11.04 like) and emesene 2.11.5.

Also, I noticed that sometimes the emoticon appears. In fact, the same
emoticon appeared a couple of times, like one time appears and another
doesn't appear. lol
Anyway, in another chat no custom emoticons appeared, so it doesn't look to
be localized to one user/emoticon.

Igor Santos
   Programador Web

**Comment by Mystro256** [comment]
Well if you do run it in terminal, you can also run "emesene -vvv" to provide more info, which may help.

**Comment by c10ud** [comment]
that looks like TextOutput extension, not AdiumTextOutput, which is the current focus of development.. so i wouldn't know what's wrong

**Comment by Mystro256** [comment]
Yeah, I noticed his screenshot and tested using text output, but I still can't reproduce this...

@igorsantos07

What client is your friend using?

**Comment by igorsantos07** [comment]
He's using the version before the last (the one that don't have Facebook
integration yet).
I'll try with another friend and then ask him what's his version.

**Comment by c10ud** [comment]
bug in OutputText, easy as that.. 

preferred output widget is the AdiumTextOutput, but if someone wants to fix this.. (e.g. mac or win)

**Comment by c10ud** [comment]
can you try if the issue persists with 2.11.8-devel?

**Comment by EchoUSB** [comment]
You can reproduce it talking with a Pidgin client.
I get this error :
(" Impossible d'ouvrir le fichier X Aucun fichier ou dossier de ce type" means "Can't open file X, no such file or directory")

<pre>[11:16:09 DEBUG papyon.transport] <<< MSG mail1@live.fr Ethan 282
    Content-Type: 'text/x-mms-emoticon'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    :awe:   <msnobj Creator="mail1@live.fr" Size="6924" Type="2" Location="19a58e796872d70a539a8131e68817b7fbaf1050.png" Friendly="AAA=" SHA1D="GaWOeWhy1wpTmoEx5ogXt/uvEFA=" SHA1C="iLmkRQSvkUKHCGtuu2AJSnaIQMk="/>
[11:16:09 DEBUG papyon.conversation] [':awe:', '<msnobj Creator="mail1@live.fr" Size="6924" Type="2" Location="19a58e796872d70a539a8131e68817b7fbaf1050.png" Friendly="AAA=" SHA1D="GaWOeWhy1wpTmoEx5ogXt/uvEFA=" SHA1C="iLmkRQSvkUKHCGtuu2AJSnaIQMk="/>']
[11:16:18 DEBUG papyon.transport] <<< MSG mail1@live.fr Ethan 177
    X-MMS-IM-Format: 'FN=Segoe%20UI; EF=; CO=0; PF=0; RL=0'\r\n
    User-Agent: 'pidgin/2.7.3'\r\n
    Content-Type: 'text/plain; charset=UTF-8'\r\n
    MIME-Version: '1.0'\r\n
    \r\n
    :awe:
[11:16:18 WARNING papyon.p2p] Deprecated: Using MSNObject creator to guess peer
[11:16:18 INFO papyon.p2p] Requesting a MSNObject from mail1@live.fr (1 end points)
[11:16:18 DEBUG papyon.msnp2p.transport.switchboard] >>> TLPv1 chunk 0x2735e7d5: blob 1122670543, SLP Message
    INVITE MSNMSGR:mail1@live.fr MSNSLP/1.0\r\n
    To: <msnmsgr:mail1@live.fr>\r\n
    From: <msnmsgr:mail2@hotmail.com>\r\n
    Via: MSNSLP/1.0/TLP ;branch={cea0b4d7-aea8-4e1c-88dc-99215853e46f}\r\n
    CSeq: 0\r\n
    Call-ID: {2455e375-b3ae-4733-8117-245af701cc3d}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 411\r\n
    \r\n
    SessionID: 2103160107\r\n
    SChannelState: 0\r\n
    Capabilities-Flags: 1\r\n
    EUF-GUID: {A4268EEC-FEC5-49E5-95C3-F126696BDBF6}\r\n
    AppID: 11\r\n
    Context: PG1zbm9iaiBDcmVhdG9yPSJldGhhbjEzMUBsaXZlLmZyIiBTaXplPSI2OTI0IiBUeXBlPSIyIiBMb2NhdGlvbj0iMTlhNThlNzk2ODcyZDcwYTUzOWE4MTMxZTY4ODE3YjdmYmFmMTA1MC5wbmciIEZyaWVuZGx5PSJBQUE9IiBTSEExRD0iR2FXT2VXaHkxd3BUbW9FeDVvZ1h0L3V2RUZBPSIgU0hBMUM9ImlMbWtSUVN2a1VLSENHdHV1MkFKU25hSVFNaz0iLz4=\r\n
    \r\n
    \x00
[11:16:18 DEBUG papyon.transport] >>> MSG 3 D 131
    MIME-Version: '1.0'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    P2P-Dest: 'mail1@live.fr'\r\n
    [P2P message (797 bytes)]
[11:16:18 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: Impossible d'ouvrir le fichier « /home/echo/.config/emesene2/messenger.hotmail.com/mail2@hotmail.com/mail1@live.fr/emoticons/19a58e796872d70a539a8131e68817b7fbaf1050 » : Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "/home/echo/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(*args, **kwargs) == False:
  File "/home/echo/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/echo/emesene/emesene/gui/base/ConversationManager.py", line 98, in _on_message
    conversation.on_receive_message(message, account, cedict)
  File "/home/echo/emesene/emesene/gui/base/Conversation.py", line 371, in on_receive_message
    received_custom_emoticons, user_emcache.path, self.first)
  File "/home/echo/emesene/emesene/gui/gtkui/TextBox.py", line 388, in receive_message
    self.config.b_allow_auto_scroll)
  File "/home/echo/emesene/emesene/gui/gtkui/TextBox.py", line 361, in append
    TextBox.append(self, text, scroll)
  File "/home/echo/emesene/emesene/gui/gtkui/TextBox.py", line 79, in append
    self._buffer.put_formatted(text)
  File "/home/echo/emesene/emesene/gui/gtkui/RichWidget.py", line 49, in put_formatted
    bold, italic, underline, strike)
  File "/home/echo/emesene/emesene/gui/gtkui/RichWidget.py", line 91, in _put_formatted
    bold, italic, underline, strike)
  File "/home/echo/emesene/emesene/gui/gtkui/RichWidget.py", line 91, in _put_formatted
    bold, italic, underline, strike)
  File "/home/echo/emesene/emesene/gui/gtkui/RichWidget.py", line 84, in _put_formatted
    self.put_image(child.src, child.alt)
  File "/home/echo/emesene/emesene/gui/gtkui/RichBuffer.py", line 78, in put_image
    pixbuf = gtk.gdk.PixbufAnimation(path)
GError: Impossible d'ouvrir le fichier « /home/echo/.config/emesene2/messenger.hotmail.com/mail2@hotmail.com/mail1@live.fr/emoticons/19a58e796872d70a539a8131e68817b7fbaf1050 » : Aucun fichier ou dossier de ce type
[11:16:18 DEBUG papyon.transport] <<< ACK 3
[11:16:18 DEBUG papyon.transport] <<< MSG mail1@live.fr Ethan 140
    P2P-Dest: 'mail2@hotmail.com'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (48 bytes)]
[11:16:18 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 fc 85 8f 2e 00 00 00 00 00 00 00 00
ed 02 00 00 00 00 00 00 00 00 00 00 02 00 00 00
cf 97 ea 42 d5 e7 35 27 ed 02 00 00 00 00 00 00
[11:16:18 DEBUG papyon.msnp2p.transport.switchboard] <<< TLPv1 chunk 0x42ea97cf: blob 781157884, ACK 0x42ea97cf 0x2735e7d5
[11:16:18 DEBUG papyon.transport] <<< MSG mail1@live.fr Ethan 141
    P2P-Dest: 'mail2@hotmail.com'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (386 bytes)]
[11:16:18 DEBUG papyon.msnp2p.transport.switchboard] <<< TLPv1 chunk 0x7f7b9073: blob 781157881, SLP Message
    MSNSLP/1.0 200 OK\r\n
    To: <msnmsgr:mail2@hotmail.com>\r\n
    From: <msnmsgr:mail1@live.fr>\r\n
    Via: MSNSLP/1.0/TLP ;branch={cea0b4d7-aea8-4e1c-88dc-99215853e46f}\r\n
    CSeq: 1\r\n
    Call-ID: {2455e375-b3ae-4733-8117-245af701cc3d}\r\n
    Max-Forwards: 0\r\n
    Content-Type: application/x-msnmsgr-sessionreqbody\r\n
    Content-Length: 26\r\n
    \r\n
    SessionID: 2103160107\r\n
    \r\n
    \x00
[11:16:18 DEBUG papyon.msnp2p.transport.switchboard] >>> TLPv1 chunk 0x2735e7d6: blob 1233766329, ACK 0x2735e7d6 0x7f7b9073
[11:16:18 DEBUG papyon.transport] >>> MSG 4 D 130
    MIME-Version: '1.0'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    P2P-Dest: 'mail1@live.fr'\r\n
    [P2P message (48 bytes)]
[11:16:18 INFO papyon.p2p] Keeping only session 2103160107 in meta session
[11:16:18 DEBUG papyon.transport] <<< MSG mail1@live.fr Ethan 140
    P2P-Dest: 'mail2@hotmail.com'\r\n
    Content-Type: 'application/x-msnmsgrp2p'\r\n
    MIME-Version: '1.0'\r\n
    [P2P message (52 bytes)]
[11:16:18 DEBUG papyon.msnp2p.transport.switchboard] <<< TLPv1 chunk 0x672a9f7a: blob 781157882, session 2103160107, data [4 bytes]</pre>

**Comment by c10ud** [comment]
i guess i now know why this is happening.

in adium when an emoticon hasn't been downloaded yet we put a placeholder and then we (try to) update with some js hack once the emoticon has been retrieved..

in richbuffer seems like the emoticon must be present or it breaks!

**Comment by c10ud** [comment]
also, in case the code gets updated to reflect adium's, how can we update emoticon _after_ they've been put in the gtk widget?
