### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#772]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 115, in **call**
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/e3/common/notification.py", line 133, in _on_message
    self._notify(contact, msgobj.display_name, text, msgobj.account, None)
  File "/home/andre/emesene/emesene/e3/common/notification.py", line 190, in _notify
    self.notifier(title, text, uri, 'message-im', None, tooltip)
  File "/home/andre/emesene/emesene/gui/gtkui/ThemeNotification.py", line 56, in ThemeNotification
    title = Plus.msnplus_strip(title)
  File "/home/andre/emesene/emesene/gui/base/Plus.py", line 315, in msnplus_strip
    msnplus = escape_special_chars(msnplus)
  File "/home/andre/emesene/emesene/gui/base/Plus.py", line 294, in escape_special_chars
    msnplus = msnplus.replace ('\xc2\xb7&amp;','\xc2\xb7&')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by c10ud** [comment]
where? which nick?

**Comment by zipatei** [comment]
"André"? ou "Elisiário Tiago"?

**Comment by c10ud** [comment]
really weird , seems like it's given None instead of something..

**Comment by zipatei** [comment]
ah... maybe broken profile

**Comment by c10ud** [comment]
i don't think so

@sbte @pepeleproso see if you can spot something obvious

**Comment by Sbte** [comment]
Only if the display_name is none, and that would have to be set by papyon. Maybe it happened during a group chat where someone not in your contact list said something?

Only thing I can think of is doing something like

msgobj.display_name if msgobj.display_name else account

in _on_message in notification.py. But it would be better to find out why this is even possible. And how it happened.

**Comment by c10ud** [comment]
i was quite asleep yesterday and i think Sbte's solution is ok..even if idk why it's None (maybe you're right with the group chat with contact etc.etc.)

**Comment by zipatei** [comment]
I do not know if that helps. Situation where it appeared:
- Login
- Offline status
- I get two messages offline Elisiário Tiago (He's my friend. There is no group. It is also offline status)

**Comment by Sbte** [comment]
Nice. That totally worked when trying to reproduce.
