### ISSUE TITLE
Segmentation faul at login hotmail

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#775]
emesene was working fine until I updated to latest via git.
emesene starts ok, when i hit the 'connect' button it closes immediately.

here is the run log:

$ ./emesene -vvv
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
/home/user/apps/emesene/emesene/emesene/e3/jabber/Worker.py:27: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha
[14:59:27 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x1d45500 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x1f2a640)>
Segmentation fault

i'm using
emesene git version
python 2.6.7
pygtk 2.24.0
papyon 0.5.5

**Comment by c10ud** [comment]
can you bisect the commit that's causing the problem?

http://kernel.org/pub/software/scm/git/docs/git-bisect.html

**Comment by ivanalejandro0** [comment]
after using git-bisect to select 'good' and 'bad' revisions i got this:

bash $ git bisect log
git bisect start

# bad: [00e79808ab50f92e358b71e9abfed0e02a56c600] setup interfaces in Category.**init** using set_interfaces

git bisect bad 00e79808ab50f92e358b71e9abfed0e02a56c600

# good: [c9e6c7189dfa8b00ed15eb141b3fb51399ccd936] jabber: get rid of tmpfile when downloading avatars and avoid leaking file descriptors

git bisect good c9e6c7189dfa8b00ed15eb141b3fb51399ccd936

# good: [902d478456a0ae74eca84f6d1b29d7b8c96fbf66] papylib: fix corner case with current_media

git bisect good 902d478456a0ae74eca84f6d1b29d7b8c96fbf66

# bad: [2e549bf2e2a488c4b286d3a4c0696a19a7cc56c0] Plus Parser: add a new function to get a pango markup

git bisect bad 2e549bf2e2a488c4b286d3a4c0696a19a7cc56c0

# bad: [9ef2fd4059cce6de5cf6ca5a964126813549cb42] gui: Move all notifications and tray icons from gui.gtkui to gui.common. One might want to use a different gui with gtk notifications/tray icons. Some of them are even gui independent

git bisect bad 9ef2fd4059cce6de5cf6ca5a964126813549cb42

# good: [13fb27c0174734cc1f69902d2b739669e5402307] gtk: indicator - use uuid instead of session.account because it's not ready when loading emesene

git bisect good 13fb27c0174734cc1f69902d2b739669e5402307

was this what you mean?
it's useful?

Note: since this problem i did'nt pulled again in this folder.
In the latest commits (tested somewhere else) i have the same problem.

**Comment by c10ud** [comment]
thanks! my personal take on the issue is some bad lib being picked up
by the "new" loading method, or some really weird regexp bug (?)

meanwhile try pulling the last git head in another folder, there've
been some other fixes (mostly parser's) that _could_ affect this issue

@Sbte mind looking into this?

2011/8/15 ivanalejandro0
reply@reply.github.com:

**Comment by ivanalejandro0** [comment]
Already done. I have 2 folders for emesene2, the updated one and the conflictive.The last git head keeps the same.
If the problem gets solved in any update i'll let you know in here. Meanwhile (and sadly) i have to use other msn client :(

**Comment by Sbte** [comment]
@ivanalejandro0, the bisect log doesn't seem complete. You have to go on until you get:

..... is the first bad commit

**Comment by ivanalejandro0** [comment]
sorry, it's my first bisection :)
I tested again and found one step missing.

ivan@sabagentoo ~/apps-test/emesene.seg_fault/emesene $ git bisect good
9ef2fd4059cce6de5cf6ca5a964126813549cb42 is the first bad commit
commit 9ef2fd4059cce6de5cf6ca5a964126813549cb42
Author: Sven (Sbte) svenb.linux@gmail.com
Date:   Sat Jul 30 19:43:45 2011 +0200

```
gui: Move all notifications and tray icons from gui.gtkui to gui.common. One might want to use a different gui with gtk notifications/tray icons. Some of them are even gui independent
```

:040000 040000 8cd91288cf4d86f010f6b46bc0903d49e5338de2 9182c585001669571dacd7969c268cae47372f5a M      emesene

ivan@sabagentoo ~/apps-test/emesene.seg_fault/emesene $ git bisect log
git bisect start

# bad: [00e79808ab50f92e358b71e9abfed0e02a56c600] setup interfaces in Category.**init** using set_interfaces

git bisect bad 00e79808ab50f92e358b71e9abfed0e02a56c600

# good: [c9e6c7189dfa8b00ed15eb141b3fb51399ccd936] jabber: get rid of tmpfile when downloading avatars and avoid leaking file descriptors

git bisect good c9e6c7189dfa8b00ed15eb141b3fb51399ccd936

# good: [902d478456a0ae74eca84f6d1b29d7b8c96fbf66] papylib: fix corner case with current_media

git bisect good 902d478456a0ae74eca84f6d1b29d7b8c96fbf66

# bad: [2e549bf2e2a488c4b286d3a4c0696a19a7cc56c0] Plus Parser: add a new function to get a pango markup

git bisect bad 2e549bf2e2a488c4b286d3a4c0696a19a7cc56c0

# bad: [9ef2fd4059cce6de5cf6ca5a964126813549cb42] gui: Move all notifications and tray icons from gui.gtkui to gui.common. One might want to use a different gui with gtk notifications/tray icons. Some of them are even gui independent

git bisect bad 9ef2fd4059cce6de5cf6ca5a964126813549cb42

# good: [13fb27c0174734cc1f69902d2b739669e5402307] gtk: indicator - use uuid instead of session.account because it's not ready when loading emesene

git bisect good 13fb27c0174734cc1f69902d2b739669e5402307

# good: [b81fb2d465674805f57825dfe8df92058c04389a] papylib: Actually use the display_name as display_name, not as style

git bisect good b81fb2d465674805f57825dfe8df92058c04389a

Hope it helps.

**Comment by Sbte** [comment]
First thing you could do is remove all pyc files.

If that doesn't work, try to comment out lines 32-34 in gui/common/**init**.py

If that doesn't help either, maybe try to comment out some other lines and see if it works?

**Comment by ivanalejandro0** [comment]
removing all the .pyc files doesn't change anything.

in "gui/common/**init**.py" commented like this to get almost working...

#import_and_register('tray icon', 'MessagingMenu')
import_and_register('tray icon', 'Indicator')
#import_and_register('tray icon', 'TrayIcon')
import_and_register('tray icon', 'NoTrayIcon')
#import_and_register(('notificationGUI'), 'PyNotification')
#import_and_register(('notificationGUI'), 'GtkNotification')
import_and_register(('notificationGUI'), 'GrowlNotification')
import_and_register(('notificationImage'), 'ThemeNotificationImage')
import_and_register(('notificationImage'), 'DummyNotificationImage')

it solves the 'Segmentation Fault' problem but can't use gui.
here is the console output:

ivan@sabagentoo ~/apps-test/emesene/emesene/emesene $ ./emesene -v
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
/home/ivan/apps-test/emesene/emesene/emesene/e3/jabber/Worker.py:27: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha
[12:34:53 INFO papyon.msnp2p.transport] Registering transport <NotificationP2PTransport object at 0x1ff8eb0 (papyon+msnp2p+transport+base+BaseP2PTransport at 0x2169260)>
/usr/lib64/python2.6/site-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
[12:35:40 INFO papyon.service.content_roaming] Synchronizing
[12:35:41 WARNING e3.common.Config] couldn't load config: /home/ivan/.config/emesene2/messenger.hotmail.com/some.msn.account@hotmail.com.ar/config (no file)
[12:35:41 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'NoTrayIcon' object has no attribute 'handler'
Traceback (most recent call last):
  File "/home/ivan/apps-test/emesene/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/ivan/apps-test/emesene/emesene/emesene/e3/common/Signal.py", line 115, in **call**
    self.f(self.c(), _arg)
  File "/home/ivan/apps-test/emesene/emesene/emesene/emesene.py", line 607, in on_login_succeed
    self.draw_main_screen()
  File "/home/ivan/apps-test/emesene/emesene/emesene/emesene.py", line 509, in draw_main_screen
    self.tray_icon.set_main(self.session)
  File "/home/ivan/apps-test/emesene/emesene/emesene/gui/base/BaseTray.py", line 50, in set_main
    self.handler.session = session
AttributeError: 'NoTrayIcon' object has no attribute 'handler'
[12:35:41 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/home/ivan/apps-test/emesene/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, **kwargs) == False:
  File "/home/ivan/apps-test/emesene/emesene/emesene/e3/common/Signal.py", line 115, in **call**
    self.f(self.c(), *arg)
  File "/home/ivan/apps-test/emesene/emesene/emesene/emesene.py", line 699, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'
[12:35:41 INFO papyon.profile] Set contact some.msn.account@hotmail.com.ar flags to 1
[12:35:41 INFO papylib.Events] OIM service state changed: 0
[12:35:41 INFO papylib.Events] OIM service state changed: 1
[12:35:41 INFO papylib.Events] OIM service state changed: 2
[12:35:41 INFO papylib.Events] Mailbox count changed (initial? True): 140
[12:35:41 INFO papylib.Events] Contact's client capabilities changed: <papyon.Contact id='185d0c52-0000-0000-0000-000000000000' network='1' account='some_contact@hotmail.com' memberships='FORWARD | ALLOW'>
[12:35:41 INFO papyon.profile] Set contact some_contact@hotmail.com flags to 1
[12:35:42 INFO papylib.Events] Contact's client capabilities changed: <papyon.Contact id='6fd51f71-9ec7-4db7-933b-a4bea4db2839' network='1' account='messenger@paginasamarillas.com.ar' memberships='FORWARD | ALLOW'>
[12:35:42 INFO papyon.profile] Set contact messenger@paginasamarillas.com.ar flags to 1
[12:35:42 INFO papyon.profile] Set contact some.msn.account@hotmail.com.ar flags to 1
[12:35:56 INFO papyon.service.content_roaming] Retrieved store profile
[12:35:56 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable
[12:35:58 INFO papyon.profile] Set contact some.msn.account@hotmail.com.ar flags to 1

**Comment by Sbte** [comment]
that's c10ud breaking stuff. Let me fix that

**Comment by Sbte** [comment]
Try now?

And after that, try uncommenting as much as possible to see where the problem lies.

**Comment by ivanalejandro0** [comment]
This is the minimum necessary to comment to get emesene working.

#import_and_register('tray icon', 'MessagingMenu')
import_and_register('tray icon', 'Indicator')
#import_and_register('tray icon', 'TrayIcon')
import_and_register('tray icon', 'NoTrayIcon')
#import_and_register(('notificationGUI'), 'PyNotification')
#import_and_register(('notificationGUI'), 'GtkNotification')
import_and_register(('notificationGUI'), 'GrowlNotification')
import_and_register(('notificationImage'), 'ThemeNotificationImage')
import_and_register(('notificationImage'), 'DummyNotificationImage')

after that i can connect and chat.

also get this errors in console:

 -- snip --
[14:04:01 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable
[14:04:01 INFO papyon.profile] Set contact some.msn.account@hotmail.com.ar flags to 1
[14:04:14 INFO papyon.protocol.switchboard_manager] Requesting switchboard for participant(s) messenger@paginasamarillas.com.ar
[14:04:14 INFO papyon.protocol.switchboard_manager] Requesting new switchboard
[14:04:15 INFO papyon.protocol.switchboard] New switchboard session 1410569975.18216117.17621486
[14:04:15 INFO papyon.protocol.switchboard_manager] Handler <SwitchboardConversation participants="messenger@paginasamarillas.com.ar"> attached to switchboard 1410569975.18216117.17621486
[14:04:16 INFO papylib.Events] Contact's client capabilities changed: <papyon.Contact id='6fd51f71-9ec7-4db7-933b-a4bea4db2839' network='1' account='messenger@paginasamarillas.com.ar' memberships='FORWARD | ALLOW'>
[14:04:56 WARNING e3.common.Signal] Method called on dead object: _on_message._on_message
Traceback (most recent call last):
  File "/home/ivan/apps-test/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/ivan/apps-test/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/ivan/apps-test/emesene/emesene/e3/common/notification.py", line 141, in _on_message
    self._notify(contact, msgobj.display_name, text, msgobj.account, None)
  File "/home/ivan/apps-test/emesene/emesene/e3/common/notification.py", line 200, in _notify
    self.notifier(title, text, uri, 'message-im', None, tooltip)
TypeError: 'NoneType' object is not callable
[14:05:05 INFO papyon.protocol.switchboard_manager] Closing switchboard handler <SwitchboardConversation participants="messenger@paginasamarillas.com.ar">
 -- snip --

i think is because the commented notification lines.

**Comment by c10ud** [comment]
4 lines? this is bad..

**Comment by Sbte** [comment]
Well, it would be explained if he didn't have to comment out PyNotification, because the others all use gtkui

**Comment by c10ud** [comment]
@ivanalejandro0 are you sure you must comment all those lines otherwise it except? 

also, are you sure you don't have some weird packages installed?

**Comment by ivanalejandro0** [comment]
I checked again to be more sure.
I tested all the possible combinations, all failed except this.

What you mean with weird packages?
here is a list of packages installed that i think may be related:
python-2.6.7
papyon-0.5.5
pysqlite-2.6.3
sqlite-3.7.7.1
pygtk-2.24.0
gtk+-2.24.5
gtk+-3.0.11
webkit-gtk-1.4.1-r200
webkit-gtk-1.4.1-r300
pywebkitgtk-1.1.8
notify-python-0.1.1
libnotify-0.7.3
growl-for-linux-0.2

**Comment by Mystro256** [comment]
Scratch that, I thought you meant something else. I didn't read the original post properly ;)

**Comment by c10ud** [comment]
OS issue, if you have further infos so we can try to help you, just write

**Comment by ivanalejandro0** [comment]
yes, must be a problem with my os.
Is there any way i can debug that to isolate the problem?

**Comment by c10ud** [comment]
the problem lies in one of the libraries used by the extensions you
commented, you should trace it down to one

i think there are also tools for debugging this kind of stuff but i'm
not used to them so i wouldn't know

2011/9/1 ivanalejandro0
reply@reply.github.com:

**Comment by ghost** [comment]
Hi. I'm using gentoo on amd64, I have ivanalejandro0's same problem using emesene 2.11.11, I've commented the same lines and it works, I can connect, chat and exit. So I'm confirming the issue.
