### ISSUE TITLE
don't show empty groups

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#776]
if show empty groups is NOT selected i.e. when logging in a group is not showed (because all of its contacts are offline) when a contact of that group comes online the group will appear but it will not be expanded.

emesene/gui/gtkui/ContactList.py

```
def update_group(self, group):
    '''update the data of group'''

    try:
        weight = int(self.session.config.d_weights.get(group.identifier, 0))
    except ValueError:
        weight = 0

    self.session.config.d_weights[group.identifier] = weight

    for row in self._model:
        obj = row[1]
        if type(obj) == e3.Group and obj.identifier == group.identifier:
            if group.name in self.group_state:
                state = self.group_state[group.name]
                childpath = self._model.get_path(row.iter)
                path = self.model.convert_child_path_to_path(childpath)
                print group.name, state, childpath, path
                if path:
                    if state:
                        self.expand_row(path, False)
                    else:
                        self.collapse_row(path)

            group.contacts = obj.contacts
            group_data = (None, group,
                self.format_group(group, self._markup_escape_group(group)),
                False, None, weight, (group.type != e3.base.Group.STANDARD), False)

            self._model[row.iter] = group_data
```

when this happens, path = self.model.convert_child_path_to_path(childpath) is None

We must investigate this issue

**Comment by Sbte** [comment]
You broke something

```
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/emesene.py", line 699, in on_contact_list_ready
    self.window.content.contact_list.fill()
  File "/home/sven/emesene/emesene/gui/base/ContactList.py", line 483, in fill
    self.add_contact(contact)
  File "/home/sven/emesene/emesene/gui/gtkui/ContactList.py", line 515, in add_contact
    self.update_no_group()
  File "/home/sven/emesene/emesene/gui/gtkui/ContactList.py", line 703, in update_no_group
    self.update_group(self.no_group)
  File "/home/sven/emesene/emesene/gui/gtkui/ContactList.py", line 760, in update_group
    if path is None:
UnboundLocalError: local variable 'path' referenced before assignment
```

**Comment by c10ud** [comment]
f-f-f-fixed
