### ISSUE TITLE
[Qt gui] Error while opening about dialog

### ISSUE THREAD

**Issue by pablorodz** [emesene/emesene#797]
Hi,
i was trying the qt version and when i click the "about dialog" nothing happend.

Here is the console output:

Traceback (most recent call last):
  File "/usr/share/emesene/gui/qt4ui/menus/MainMenu.py", line 210, in <lambda>
    lambda *args: self.handler.on_about_selected())
  File "/usr/share/emesene/gui/base/Handler.py", line 185, in on_about_selected
    self.dialog.about_dialog('emesene', EMESENE_VERSION, EMESENE_AUTHORS,
AttributeError: type object 'Dialog' has no attribute 'about_dialog'

**Comment by c10ud** [comment]
don't use the qt4 ui unless you fix it, sorry
