### ISSUE TITLE
Nick renderer problem with Plus

### ISSUE THREAD

**Issue by ivanalejandro0** [emesene/emesene#802]
When i open a chat window with this contact this appears on console (using emesene -v)

(snip)

[16:20:36 ERROR gtkui.Renderers] this nick: '[c=37][b][i]| Eres el sueño hecho realidad y la realidad que siempre había soñado. |[/b][/i][/c=37]    [b][c=77][Juan][/b][/c=77]
[$small][C=c10ud]someweb.blogspot.com[/C][$/small]' made the parser go crazy, striping. Error: tuple index out of range
warning: line 6172: incompatible stripping characters and condition
warning: line 6184: incompatible stripping characters and condition
[16:20:37 WARNING e3.common.Signal] Signal handler (_on_contact_selected._on_contact_selected) error: tuple index out of range
Traceback (most recent call last):
  File "/home/ivan/apps-test/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/ivan/apps-test/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/MainWindow.py", line 202, in _on_contact_selected
    self.on_new_conversation(cid, [contact.account], False)
  File "/home/ivan/apps-test/emesene/emesene/emesene.py", line 713, in on_new_conversation
    conversation.update_data()
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Conversation.py", line 446, in update_data
    self._update_single_information(self.members[0])
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Conversation.py", line 498, in _update_single_information
    self.update_single_information(nick, message, account)
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/Conversation.py", line 340, in update_single_information
    self.update_tab()
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/Conversation.py", line 350, in update_tab
    self.tab_label.set_text(self.text)
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/TabWidget.py", line 103, in set_text
    self.label.set_markup(Renderers.msnplus_to_list(gobject.markup_escape_text(text)))
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/Renderers.py", line 161, in msnplus_to_list
    text = plus_text_parse(text)
  File "/home/ivan/apps-test/emesene/emesene/gui/gtkui/Renderers.py", line 154, in plus_text_parse
    item = Plus.msnplus_parse(item)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 393, in msnplus_parse
    dictlike = msnplus(text, False)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 381, in msnplus
    _hex_colors(dictlike)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 296, in _hex_colors
    _hex_colors(child)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 296, in _hex_colors
    _hex_colors(child)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 296, in _hex_colors
    _hex_colors(child)
  File "/home/ivan/apps-test/emesene/emesene/gui/base/Plus.py", line 281, in _hex_colors
    msgdict[tag] = (COLOR_MAP[int(param1)], msgdict[tag][1])
IndexError: tuple index out of range
[16:20:38 ERROR gtkui.Renderers] this nick: '[c=37][b][i]| Eres el sueño hecho realidad y la realidad que siempre había soñado. |[/b][/i][/c=37]    [b][c=77][Juan][/b][/c=77]
[$small][C=c10ud]someweb.blogspot.com[/C][$/small]' made the parser go crazy, striping. Error: tuple index out of range
[16:20:38 ERROR gtkui.Renderers] this nick: '[c=37][b][i]| Eres el sueño hecho realidad y la realidad que siempre había soñado. |[/b][/i][/c=37]    [b][c=77][Juan][/b][/c=77]
[$small][C=c10ud]someweb.blogspot.com[/C][$/small]' made the parser go crazy, striping. Error: tuple index out of range
/home/ivan/apps-test/emesene/emesene/gui/gtkui/__init__.py:88: GtkWarning: gdk_window_invalidate_rect_full: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()

(snip)

and the window are not usable (all grey).

If i disable the plus renderer extension in the 'nick renderer' category (setting the 'Cell Renderer No Plus' option) all works fine (chat window working, no errors in console)

**Comment by c10ud** [comment]
which emesene version? 

@sbte ^

**Comment by ivanalejandro0** [comment]
oh, i forget to say it's the latest git version.

**Comment by Sbte** [comment]
It's because of the [] around the name. I'll add a dummy contact with a name like that and fix the bug, hopefully tomorrow. Unless pepe is first of course ;)

**Comment by Sbte** [comment]
Ok, that's not the problem. The problem is that this person is a moron, because there are only 68 color codes. This person tries to use 77, which is something that doesn't exist. Not in real Plus, so not in emesene either.

I'll just default to black. And fix the [a] and [c] codes while at it

**Comment by Sbte** [comment]
Also, he doesn't close tags in the right order. That's broken too...

@pepeleproso, I could use some reinforcements.

**Comment by Sbte** [comment]
Oh, and it appears that if new tags are not closed, they shouldn't be parsed.

@c10ud, this was also broken in the old parser, so don't say that we shouldn't have bothered fixing this one, because the old one was better.
