### ISSUE TITLE
emesene doesn't start when an incomplete (image) theme is used

### ISSUE THREAD

**Issue by javijec** [emesene/emesene#817]
[11:44:45 WARNING papyon.msnp2p.transport] TLPv1 Parse Error: empty chunk for non-empty blob
00 00 00 00 d0 16 00 00 00 00 00 00 00 00 00 00
47 01 00 00 00 00 00 00 00 00 00 00 02 00 00 00
63 d1 59 7b c5 00 c5 49 47 01 00 00 00 00 00 00

does not start emesene, it is a blank screen.
That error occurs

[11:45:05 WARNING e3.common.Signal] Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: 'str' object has no attribute 'status_icons'

**Comment by Sbte** [comment]
There should also be a traceback. Please post that too. 

That papyon warning is harmless btw. It's about the last one.

**Comment by javijec** [comment]
[12:13:54 WARNING e3.common.Signal] Signal handler (_on_contact_attr_changed._on_contact_attr_changed) error: 'str' object has no attribute 'status_icons'
Traceback (most recent call last):
  File "/home/javijec/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/javijec/emesene/emesene/e3/common/Signal.py", line 115, in __call__
    self.f(self.c(), *arg)
  File "/home/javijec/emesene/emesene/gui/base/ContactList.py", line 170, in _on_contact_attr_changed
    self.update_contact(contact)
  File "/home/javijec/emesene/emesene/gui/gtkui/ContactList.py", line 638, in update_contact
    utils.safe_gtk_pixbuf_load(gui.theme.image_theme.status_icons[contact.status]),
AttributeError: 'str' object has no attribute 'status_icons'

**Comment by Sbte** [comment]
And what version of emesene?

**Comment by javijec** [comment]
is the newest version from git repository

**Comment by javijec** [comment]
Ubuntu 11.04

**Comment by javijec** [comment]
of papyon is also the newest version from git repository

**Comment by Sbte** [comment]
Ok, then that theme is probably not complete. For now you can fix it by copying the missing images from the default theme to that folder. I will make those load by default instead. Unless @pepeleproso fixes it faster.

**Comment by javijec** [comment]
I somehow I can temporarily fix?

**Comment by Sbte** [comment]
Yes, see above...

I also have a fix in my repo that I'll push as soon as pepeleproso looks at it.

**Comment by javijec** [comment]
the solution of your fork made ​​my work emesene

**Comment by Sbte** [comment]
Pulled, and fixed
