### ISSUE TITLE
Start session

### ISSUE THREAD

**Issue by cleve** [emesene/emesene#82]
I can´t session start with hotmail.cl domain.

(sorry for my english).

**Comment by c10ud** [comment]
are you using papyon (msn) to connect or e3.msn? can you post some debug output? start emesene like this: ./emesene -vvv

**Comment by cleve** [comment]
This error:
 [14:00:31 WARNING papyon.protocol.notification] Contact (network_id=1) user@hotmail.cl not found

**Comment by cleve** [comment]
Complete:

No handlers could be found for logger "papylib.Worker"
[14:30:08 WARNING papyon.protocol] Notification unhandled command : GCF 0 5486
    [payload]
/usr/lib64/python2.6/site-packages/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/client.py", line 395, in state_changed
    self._state = ClientState.OPEN
  File "/usr/lib/python2.6/site-packages/papyon/client.py", line 288, in fset
    self._dispatch("on_client_state_changed", state)
  File "/usr/lib/python2.6/site-packages/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/usr/lib/python2.6/site-packages/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/cleve/Descargas/emesene-emesene-4896b30/emesene/e3/papylib/PapyEvents.py", line 33, in on_client_state_changed
    self._client.set_initial_infos()
  File "/home/cleve/Descargas/emesene-emesene-4896b30/emesene/e3/papylib/Worker.py", line 125, in set_initial_infos
    self.content_roaming.connect("notify::state", \
AttributeError: 'Worker' object has no attribute 'content_roaming'
[papyon] oim state changed 0
[papyon] oim state changed 1
[papyon] oim state changed 2
[14:30:14 WARNING papyon.protocol.notification] Contact (network_id=1) user@hotmail.cl not found
[14:30:14 WARNING papyon.protocol.notification] Contact (network_id=1) user@hotmail.cl not found

**Comment by c10ud** [comment]
you must use papyon 0.5.1 sir, sure you have it?

**Comment by cleve** [comment]
Name        : papyon
Arch        : noarch
Version     : 0.5.0

:/

**Comment by c10ud** [comment]
then, use .5.1
