### ISSUE TITLE
[papyon]TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by EibrielInv** [emesene/emesene#83]
The complete error:

```
Traceback (most recent call last):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 368, in property_changed
    self._dispatch(method_name, contact)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/PapyEvents.py", line 149, in on_contact_msn_object_changed
    self._client._on_contact_msnobject_changed(contact)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/Worker.py", line 597, in _on_contact_msnobject_changed
    (download_ok, download_failed))
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/p2p.py", line 334, in request
    session.invite()
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/p2p.py", line 587, in invite
    session.invite()
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/msnobject.py", line 64, in invite
    self._invite(self._context)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 156, in _invite
    self._send_slp_message(message)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/session.py", line 261, in _send_slp_message
    self._application_id, message)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 127, in send_slp_message
    self.send_data(peer, peer_guid, application_id, 0, str(message))
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/transport_manager.py", line 132, in send_data
    transport.send(peer, peer_guid, blob)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 103, in send
    self._process_send_queue()
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 206, in _process_send_queue
    self.__send_chunk(peer, peer_guid, chunk)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/base.py", line 224, in __send_chunk
    self._send_chunk(peer, peer_guid, chunk)
  File "/home/gabriel/Documentos/SoftLibre/Emesene/emesene/emesene/e3/papylib/papyon/papyon/msnp2p/transport/switchboard.py", line 102, in _send_chunk
    peer_guid + "}"}
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Regards!!!

**Comment by c10ud** [comment]
issue in papyon

[18:38] <lfrb> but you can try to change lines 569 of papyon/msnp/notification.py
[18:38] <lfrb> put the 'end-points' before 'msn-object'

will be fixed upstream asap

**Comment by EibrielInv** [comment]
Ok!! Thanks!!

**Comment by EibrielInv** [comment]
What is the Papyon repository? to make an Issue entry.
Is http://github.com/Kjir/papyon/?

Thanks!

**Comment by c10ud** [comment]
https://bugs.freedesktop.org/buglist.cgi?product=papyon

**Comment by c10ud** [comment]
fixed upstream

**Comment by c10ud** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=30411
