### ISSUE TITLE
'NoneType' object has no attribute 'Empty'

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#840]
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/andre/emesene/emesene/e3/papylib/Worker.py", line 135, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

I don't know how to reproduce it.
Two possible things:
- View information and conversation history ...
- Clean conversation
- Refresh

or,

Error Appear When emesene quit.

**Comment by shuhaowu** [comment]
I'm pretty sure this is a synchronization issue caused when threads start terminating while quitting, which is unavoidable.

Hence: this should be a non-issue and should be closed.

**Comment by c10ud** [comment]
ultimatebuster is right
