### ISSUE TITLE
Contact status history combo plugin (stop error)

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#843]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/PluginWindow.py", line 68, in on_toggled
    self.on_stop()
  File "/home/andre/emesene/emesene/gui/gtkui/PluginWindow.py", line 94, in on_stop
    pluginmanager.plugin_stop(name)
  File "/home/andre/emesene/emesene/pluginmanager.py", line 205, in plugin_stop
    self._plugins[name].stop()
  File "/home/andre/emesene/emesene/pluginmanager.py", line 132, in stop
    self._instance.stop()
  File "/home/andre/.config/emesene2/plugins/contact_status_history_combo/plugin.py", line 20, in stop
    self.on_stop()
AttributeError: 'Plugin' object has no attribute 'on_stop'

**Comment by pepeleproso** [comment]
Fixed in plugins repo
