### ISSUE TITLE
account facebook login

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#844]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 104, in run
    self._process_action(action)
  File "/home/andre/emesene/emesene/e3/base/Worker.py", line 182, in _process_action
    self.action_handlers[action.id_](*action.args)
  File "/home/andre/emesene/emesene/e3/jabber/Worker.py", line 303, in _handle_action_login
    proxy=self.proxy_data) == "":
  File "/home/andre/emesene/emesene/e3/jabber/xmppy/xmpp/client.py", line 200, in connect
    if not CommonClient.connect(self,server,proxy,secure,use_srv) or secure<>None and not secure: return self.connected
  File "/home/andre/emesene/emesene/e3/jabber/xmppy/xmpp/client.py", line 184, in connect
    if not self.Process(1): return
  File "/home/andre/emesene/emesene/e3/jabber/xmppy/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "/home/andre/emesene/emesene/e3/jabber/xmppy/xmpp/dispatcher.py", line 215, in streamErrorHandler
    raise exc((name,text))
HostUnknown: (u'host-unknown', '')

**Comment by c10ud** [comment]
what's this supposed to mean? did you enter the right account/password?

**Comment by zipatei** [comment]
Sorry for the hassle of issues raised yesterday.

It was late and didn't even see that he was not being clear in the description.

About this Issue, I put the wrong username.
