### ISSUE TITLE
account facebook login http method

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#845]
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 452, in error
    self._transport.lose_connection()
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/transport.py", line 378, in lose_connection
    gobject.source_remove(self._polling_source_id)
AttributeError: 'HTTPPollConnection' object has no attribute '_polling_source_id'

**Comment by c10ud** [comment]
logging in facebook with papyon might not be a good idea

**Comment by zipatei** [comment]
We shouldn't work the code to avoid bad settings?

Insensitive things in server configuration for example?
