### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#847]
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 821, in run
    quit = self._process(data)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 842, in _process
    cid=cid)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 602, in add_event
    id_time = self.insert_time_now()
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 419, in insert_time_now
    seconds)
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 406, in insert_time
    (year, month, day, wday, hour, minute, seconds))
  File "/home/andre/emesene/emesene/e3/base/Logger.py", line 576, in execute
    self.cursor.execute(query, args)
OperationalError: database is locked

**Comment by shuhaowu** [comment]
Did you shutdown emesene abnormally before?

**Comment by c10ud** [comment]
@ultimatebuster answer is 100% yes

**Comment by Sbte** [comment]
That or he had another instance of emesene with the same account still open. That's more likely when this happens.
