### ISSUE TITLE
music plugin doesn't work with audacious (2.54)

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#850]
I've cloned the latest git and I tried the music plugin, it doesn't work at all (I'm in ArchLinux). The first time I was able to see the title of the song that i was listen in the main window, but anyone of my contacts can't . Now the song name doesn't show at all.

Here'e the output:

$ python2 ./emesene
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
[23:14:34 ERROR papyon.protocol.notification] Notification got error : 913 10
[23:14:43 WARNING papyon.p2p] Trying to publish an empty MSNObject
Traceback (most recent call last):
  File "/home/maloy/.config/emesene2/plugins/music/songretriever.py", line 138, in check_song
    song = self.get_current_song()
  File "/home/maloy/.config/emesene2/plugins/music/handler_audacious2.py", line 30, in get_current_song
    album = self.iface.SongTuple(song_position, "album") 
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 143, in **call**
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 630, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.GLib.ErrorError: Method invoked for SongTuple returned FALSE but did not set error
warning: line 6172: incompatible stripping characters and condition
warning: line 6184: incompatible stripping characters and condition

**Comment by c10ud** [comment]
please open the issue in emesene-plugins
