### ISSUE TITLE
Logger error

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#859]
after last git, I can't see my chat logs with the following error:
Traceback (most recent call last):
  File "/home/ammar/emesene/emesene/e3/base/Logger.py", line 888, in check
    callback(result)
  File "/home/ammar/emesene/emesene/gui/gtkui/ContactInformation.py", line 419, in _on_chats_ready
    None, None, self.first)
TypeError: receive_message() takes exactly 3 arguments (7 given)

**Comment by pepeleproso** [comment]
I'm working on this
