### ISSUE TITLE
Can't login in one account with the new emesene-papyon

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#864]
this is the traceback

```
Traceback (most recent call last):
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/SOAPService.py", line 230, in _response_handler
    handler(callback, errback, response, user_data)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/ab.py", line 231, in _HandleABFindAllResponse
    run(callback, address_book)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/scenario/sync/sync.py", line 55, in __ab_findall_callback
    self.__sync_callback()
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/scenario/sync/sync.py", line 60, in __sync_callback
    self.callback(self.__ab_response, self.__membership_response)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/scenario/base.py", line 37, in callback
    run(self._callback, *args)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/address_book.py", line 254, in callback
    self.__log_sync_request(ab_storage, memberships)
  File "/home/arielau/emesene2/emesene/emesene/e3/papylib/papyon/papyon/service/AddressBook/address_book.py", line 691, in __log_sync_request
    member_repr = member.PassportName if not isinstance(member, sharing.EmailMember) else member.Email
AttributeError: 'CircleMember' object has no attribute 'PassportName'
```

Do you need any extra info?

The account is a normal hotmail.com account, the profile is NOT broken (but it doesn't matter anyway I can log in with two other normal hotmail accounts with nd without the profile broken). I don't know what else could be related.

**Comment by c10ud** [comment]
ah, CircleMember needs to be added to the "exceptions"..

**Comment by c10ud** [comment]
@arielj, try:

member_repr = member.PassportName if isinstance(member, sharing.PassportMember) else member.Email

**Comment by c10ud** [comment]
or maybe:

member_repr = member.PassportName if isinstance(member, sharing.PassportMember) else member.Account

is better (?)

**Comment by c10ud** [comment]
or maybe just
member_repr = member.Account

**Comment by c10ud** [comment]
or just pull now :D

**Comment by arielj** [comment]
works!
