### ISSUE TITLE
emesene2 loggin failed

### ISSUE THREAD

**Issue by chy168** [emesene/emesene#87]
I use git version emesene2.
Python version: 2.6.5
When I logged in my account, there are some error shown.
How can I fix it ?
# 

No handlers could be found for logger "papylib.Worker"
[04:15:17 WARNING papyon.protocol] Notification unhandled command : GCF 0 5486
    [payload]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/client.py", line 385, in state_changed
    self._state = ClientState.OPEN
  File "/usr/lib/python2.6/site-packages/papyon/client.py", line 278, in fset
    self._dispatch("on_client_state_changed", state)
  File "/usr/lib/python2.6/site-packages/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/usr/lib/python2.6/site-packages/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/chy168/emesene-svn/develope/emesene2/emesene/emesene/e3/papylib/PapyEvents.py", line 33, in on_client_state_changed
    self._client.set_initial_infos()
  File "/home/chy168/emesene-svn/develope/emesene2/emesene/emesene/e3/papylib/Worker.py", line 125, in set_initial_infos
    self.content_roaming.connect("notify::state", \
AttributeError: 'Worker' object has no attribute 'content_roaming'
[papyon] oim state changed 0
[papyon] oim state changed 1
[04:15:26 WARNING papyon.protocol.notification] Contact (network_id=1) MYMSN@hotmail.com not found
[04:15:26 WARNING papyon.protocol.notification] Contact (network_id=1) MYMSN@hotmail.com not found
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/python2.6/site-packages/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/python2.6/site-packages/papyon/p2p.py", line 155, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/python2.6/site-packages/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/python2.6/site-packages/papyon/p2p.py", line 155, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/python2.6/site-packages/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/python2.6/site-packages/papyon/p2p.py", line 155, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/msnp/base.py", line 107, in _dispatch_command
    handler(command)
  File "/usr/lib/python2.6/site-packages/papyon/msnp/notification.py", line 453, in _handle_NLN
    urllib.unquote(command.arguments[idx]))
  File "/usr/lib/python2.6/site-packages/papyon/p2p.py", line 155, in parse
    location = xml.unescape(element["Location"])
KeyError: 'Location'
[04:15:28 WARNING papyon.service] Metadata: Invalid metadata
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/papyon/service/SOAPService.py", line 215, in _response_handler
    handler(callback, errback, response, user_data)
  File "/usr/lib/python2.6/site-packages/papyon/service/OfflineIM/rsi.py", line 45, in _HandleGetMetadataResponse
    callback[0](response.text, *callback[1:])
  File "/usr/lib/python2.6/site-packages/papyon/service/OfflineIM/scenario/sync_headers.py", line 41, in __get_metadata_callback
    callback[0](metadata, *callback[1:])
  File "/usr/lib/python2.6/site-packages/papyon/service/OfflineIM/offline_messages_box.py", line 251, in __parse_metadata
    for m in metadata.findall('./M'):
  File "/usr/lib/python2.6/site-packages/papyon/util/element_tree.py", line 143, in findall
    return self.tree.findall(path)
AttributeError: 'NoneType' object has no attribute 'findall'

**Comment by c10ud** [comment]
use papyon 0.5.1 and it will work
