### ISSUE TITLE
Emesene cannot start : Syntaxt error

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#874]
There isn't much I can say about that, except that when I updated my revision 2 days ago after weeks of using an older build, it stopped working. I just re-updated it and it didn't fix it.

```
Traceback (most recent call last):
  File "./emesene", line 30, in <module>
    from emesene import emesene
  File "/home/user/emesene/emesene/emesene.py", line 73, in <module>
    import e3
  File "/home/user/emesene/emesene/e3/__init__.py", line 3, in <module>
    import common
  File "/home/user/emesene/emesene/e3/common/__init__.py", line 22, in <module>
    import notification
  File "/home/user/emesene/emesene/e3/common/notification.py", line 21, in <module>
    import gui
  File "/home/user/emesene/emesene/gui/__init__.py", line 20, in <module>
    from base import *
  File "/home/user/emesene/emesene/gui/base/__init__.py", line 25, in <module>
    from Conversation import Conversation
  File "/home/user/emesene/emesene/gui/base/Conversation.py", line 358
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```

**Comment by c10ud** [comment]
your merge went bad, git reset --hard upstream/master or just delete
the dir and clone again

please keep the bugtracker for code issues only, not git-related mess

2011/9/18 Riboshom
reply@reply.github.com:

**Comment by Sbte** [comment]
`git reset --hard origin` could be enough even.

Anyway, this is @marianoguerra's fault. He force pushed.
