### ISSUE TITLE
Emesene 2.11.9 not starting (Lubuntu 11.04)

### ISSUE THREAD

**Issue by Smile4ever** [emesene/emesene#883]
Emesene 2.11.9 is not starting. It just does nothing. When I open my terminal and I type emesene or sudo emesene I get this:

king@lubuntu:~$ emesene
No module named OpenSSL.SSL
Traceback (most recent call last):
  File "/usr/bin/emesene", line 30, in <module>
    from emesene import emesene
  File "/usr/share/emesene/emesene/emesene.py", line 109, in <module>
    from e3 import papylib
  File "/usr/share/emesene/emesene/e3/papylib/**init**.py", line 21, in <module>
    from Session import Session
  File "/usr/share/emesene/emesene/e3/papylib/Session.py", line 22, in <module>
    from Worker import Worker
  File "/usr/share/emesene/emesene/e3/papylib/Worker.py", line 65, in <module>
    from PapyEvents import *
  File "/usr/share/emesene/emesene/e3/papylib/PapyEvents.py", line 23, in <module>
    import papyon.event
  File "/usr/share/emesene/emesene/e3/papylib/papyon/papyon/**init**.py", line 36, in <module>
    from client import *
  File "/usr/share/emesene/emesene/e3/papylib/papyon/papyon/client.py", line 83, in <module>
    import papyon.profile as profile
AttributeError: 'module' object has no attribute 'profile'

Regards,
Smile4ever

**Comment by c10ud** [comment]
No module named OpenSSL.SSL

you need python-openssl how did you install emesene system-wide without having its deps?

**Comment by Smile4ever** [comment]
I just used the WebUpd8 unstable ppa. With python-openssl installed I get the same errors.

**Comment by c10ud** [comment]
please paste the new error, and don't use packages made by unknown sources

**Comment by madjr** [comment]
i also use the WebUpd8 ppas by Alin Andrei.

i wouldn't consider him unknown:
http://www.google.com/search?client=ubuntu&channel=fs&q=webupd8&ie=utf-8&oe=utf-8

He usually is a good packager and probably this package was poorly tested and is why is still in his unstable ppa.

it seems no one else has made a package for ubuntu, so not much choice either..

**Comment by c10ud** [comment]
sir, you're just missing one of the deps. Unknown or not the package is not OK since it didn't pull in the requested deps.

you may want to use this ppa instead:
https://launchpad.net/~emesene-team/+archive/emesene-stable
