### ISSUE TITLE
Json exception

### ISSUE THREAD

**Issue by cando** [emesene/emesene#9]
Traceback (most recent call last):
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/gtkui/TrayIcon.py", line 116, in <lambda>
    lambda *args: self.handler.on_disconnect_selected())
  File "/home/cando/Documenti/devs/emesene/mesinyer/gui/base/Handler.py", line 42, in on_disconnect_selected
    self.on_disconnect()
  File "/home/cando/Documenti/devs/emesene/mesinyer/emesene.py", line 487, in on_user_disconnect
    self.close_session(False)
  File "/home/cando/Documenti/devs/emesene/mesinyer/emesene.py", line 210, in close_session
    self.session.save_config()
  File "/home/cando/Documenti/devs/emesene/mesinyer/e3/base/Session.py", line 90, in save_config
    self.config.save(self.config_dir.join('config'))
  File "/home/cando/Documenti/devs/emesene/mesinyer/e3/common/Config.py", line 75, in save
    json.dump(values, file(path, "w"), indent=1)
  File "/usr/lib/python2.6/json/**init**.py", line 180, in dump
    for chunk in iterable:
  File "/usr/lib/python2.6/json/encoder.py", line 306, in _iterencode
    for chunk in self._iterencode_list(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 204, in _iterencode_list
    for chunk in self._iterencode(value, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 306, in _iterencode
    for chunk in self._iterencode_list(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 204, in _iterencode_list
    for chunk in self._iterencode(value, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 268, in _iterencode_dict
    raise TypeError("key {0!r} is not a string".format(key))
TypeError: key <class interfaces.bar.IBar at 0xaeb4cec> is not a string

everytime i try to disconnect or close emesene...

**Comment by cando** [comment]
fixed
