### ISSUE TITLE
The music plugin fails when the 'Album' field in the id3tag is empty (Audacious)

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#912]
This happens when the "Album" field in the id3tag of the song is empty, the song doesn't change and the plugin doesn't work anymore until emesene is restarted. Can you make the music plugin skips the 'Album' field if the cover album as an avatar option is not set?

I'm on emesene git version in Ubuntu Lucid, here's the output:

$ /home/maloy/emesene/emesene/emesene
[21:36:10 ERROR papyon.protocol.notification] Notification got error : 913 14
Traceback (most recent call last):
File "/home/maloy/.config/emesene2/plugins/music/songretriever.py", line 138, in check_song
song = self.get_current_song()
File "/home/maloy/.config/emesene2/plugins/music/handler_audacious2.py", line 30, in get_current_song
album = self.iface.SongTuple(song_position, "album")
File "/usr/lib/pymodules/python2.6/dbus/proxies.py", line 140, in call
**keywords)
File "/usr/lib/pymodules/python2.6/dbus/connection.py", line 620, in call_blocking
message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.GLib.ErrorError: Method invoked for SongTuple returned FALSE but did not set error
[21:36:26 WARNING papyon.p2p] Trying to publish an empty MSNObject

**Comment by Sbte** [comment]
Don't report duplicates please:

https://github.com/emesene/emesene-supported-plugins/issues/40
