### ISSUE TITLE
Downloading many files from github is forbidden?

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#922]
When I try to download two image themes in a row, I get this:

```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/e3/common/Collections.py", line 79, in save_files
    rq = self.github.get_raw(self.theme, element[label].files[path])
  File "/home/sven/emesene-dev/emesene/e3/common/Github.py", line 38, in get_raw
    response = urlopen(API_GITHUB_GETRAW % (self._org, repo, sha))
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

I wonder why that happens...

**Comment by Sbte** [comment]
Seems to be fixed by 00cd2ccd30dfb0c6484ca7ed4a77bb9bc6e88789

:S

**Comment by arielj** [comment]
I get this errror when downloading the music plugin, plugin.py's content is:

{"error":["API Rate Limit Exceeded for xxx.xxx.xx.xxx"]}

(xxx.xxx.xx.xxx is my ip)

it might be related, I'm not sure

**Comment by arielj** [comment]
It happens if I download something big like an image theme before the music plugin, I guess we can't download too much data too quick, should we have some kind of warning?

**Comment by Sbte** [comment]
I downloaded 5 image themes and this didn't happen...

**Comment by c10ud** [comment]
maybe it depends on load, etc.

i think it could be just enough to tell the user: "servers are overloaded try again later"

**Comment by Sbte** [comment]
Not sure, I can't reproduce it anymore. If someone else can, then we'll see.
