### ISSUE TITLE
Can't save emoticons

### ISSUE THREAD

**Issue by Mercilessgr1** [emesene/emesene#933]
I have downloaded and installed the latest emesene version 2.11.11 and have corrected the code accordint to https://github.com/emesene/emesene/commit/70c2cbab1f506f37cbf7c9c9b8b67001ba7281f7 correction by pepeleproso answered on bug No #914 but I can't steal or add any custom emoticons.

Some help would be appreciated.

Thanks

**Comment by pepeleproso** [comment]
any console output?

**Comment by Mercilessgr1** [comment]
I just tested the application using the commandline and here is the output starting at the point I received a custom emoticon from a friend:

Traceback (most recent call last):
  File "/usr/share/emesene/emesene/e3/papylib/papyon/papyon/p2p.py", line 325, in _on_session_completed
    run(callback, msn_object)
  File "/usr/share/emesene/emesene/e3/papylib/papyon/papyon/util/async.py", line 40, in run
    callback[0](*args)
  File "/usr/share/emesene/emesene/e3/papylib/Worker.py", line 546, in download_ok
    filename)
  File "/usr/share/emesene/emesene/e3/cache/EmoticonCache.py", line 91, in insert_resized
    self.resize_with_imagemagick(path, path, height, width)
  File "/usr/share/emesene/emesene/e3/cache/Cache.py", line 130, in resize_with_imagemagick
    return false
NameError: global name 'false' is not defined
[20:09:32 WARNING papyon.msnp2p.session_manager] Received initial blob with SessionID=0 and non INVITE SLP data
[20:10:10 WARNING e3.cache.Cache.py] Can't read file to hash
