### ISSUE TITLE
ERROR gtkui.Renderers 

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#937]
apple always returns this error:

[21:04:06 ERROR gtkui.Renderers] this nick: '[b][c=27][a=0]Â°â¢.â¢Â°o.O [/c=46][c=46]ÑÎ±zÎ¹Ñâ[/c=12][c=12] O.oÂ°â¢.â¢Â°[/a=0][/c=9][/b]
[$small][C=c10ud][/C][$/small]' made the parser go crazy, striping. Error: list index out of range

**Comment by Sbte** [comment]
From #944:

[17:54:48 ERROR gtkui.Renderers] this nick: ''
[$small][C=c10ud][a=1][c=0]- uɐɐɐɹɟfraan臖 *͍͎͋͌⃡(F) [/c][c=8] [/c=11][c=11][/c=13][c=13][/c=8][/a][/C][$/small]' made the parser go crazy, striping. Error: list index out of range

Full traceback is

```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/gui/gtkui/TextField.py", line 86, in on_entry_activate
    self.text = self.entry.get_text()
  File "/home/sven/emesene-dev/emesene/gui/gtkui/TextField.py", line 123, in _set_text
    gobject.markup_escape_text(self._text or self.empty_text)))
  File "/home/sven/emesene-dev/emesene/gui/gtkui/Renderers.py", line 165, in msnplus_to_list
    text = plus_text_parse(text, plus)
  File "/home/sven/emesene-dev/emesene/gui/gtkui/Renderers.py", line 158, in plus_text_parse
    item = Plus.msnplus_parse(item)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 401, in msnplus_parse
    dictlike = msnplus(text, False)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 390, in msnplus
    _dict_gradients(dictlike)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 359, in _dict_gradients
    _dict_gradients(subdict)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 359, in _dict_gradients
    _dict_gradients(subdict)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 358, in _dict_gradients
    _gradientify(subdict)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 336, in _gradientify
    colors = _color_gradient(param_from, param_to, length)
  File "/home/sven/emesene-dev/emesene/gui/base/Plus.py", line 269, in _color_gradient
    colors[length - 1] += dec2hex(color_part[1])
IndexError: list index out of range
```

**Comment by KinG-InFeT** [comment]
fixed? well ^_^
