### ISSUE TITLE
emesene and close out an error

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#940]
emesene when I close out the following error:

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 136, in run

**Comment by KinG-InFeT** [comment]
added 

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

version 2.11.12-devel

**Comment by KinG-InFeT** [comment]
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/site-packages/emesene/e3/papylib/Worker.py", line 136, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

last commit git version 2.11.12-devel

**Comment by c10ud** [comment]
we can't prevent interpreter-shutdown exception, i won't post the source because i'll have to search for it and i'm lazy, but trust me on this one
