### ISSUE TITLE
cids can break

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#951]
[11:46:36 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'icid'
Traceback (most recent call last):
  File "/home//msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, *_kwargs) == False:
  File "/home//msn/emesene/emesene/e3/common/Signal.py", line 112, in __call__
    self.f(self.c(), _arg)
  File "/home//msn/emesene/emesene/gui/common/MessagingMenu.py", line 85, in _on_conv_message
    icid = conv.icid
AttributeError: 'NoneType' object has no attribute 'icid'
[11:46:40 ERROR e3.common.Signal] Signal handler (_on_conv_message._on_conv_message) error: 'NoneType' object has no attribute 'icid'
Traceback (most recent call last):
  File "/home//msn/emesene/emesene/e3/common/Signal.py", line 65, in emit
    if callback(_args, **kwargs) == False:
  File "/home//msn/emesene/emesene/e3/common/Signal.py", line 112, in **call**
    self.f(self.c(), *arg)
  File "/home//msn/emesene/emesene/gui/common/MessagingMenu.py", line 85, in _on_conv_message
    icid = conv.icid
AttributeError: 'NoneType' object has no attribute 'icid'

@sbte

**Comment by c10ud** [comment]
two instances send send send close conv send again (?)

**Comment by Sbte** [comment]
You sent and closed so fast that emesene.py didn't have time to process the previous message in on_new_conversation? I wouldn't know how this could happen otherwise. Anyhow, you could just check for conv...
