### ISSUE TITLE
[papylib] send custom emoticons with text messages

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#96]
kthxbi

**Comment by c10ud** [comment]
disclaimer: i currently have no clue on how to do this :)

**Comment by c10ud** [comment]
Implemented custom emoticons sending. Tested with amsn, makes emesene1 crash (some weirdness happens). Closed by 5025a6023cedfeb4d6d3029ff8c17f8316dc28ad

Fixed style in incoming messages in AdiumTextBox.
Possibly broken some output backend with the add of some dict/list here and there.

**Comment by chy168** [comment]
I try the newest version, but get error when send message:

```
Traceback (most recent call last):
  File "/home/chy168/emesene-       svn/develope/emesene2/emesene/emesene/gui/gtkui/TextBox.py", line 173, in     _on_key_press_event
    self.on_send_message(self.text)
  File "/home/chy168/emesene-    svn/develope/emesene2/emesene/emesene/gui/base/Conversation.py", line 206, in   _on_send_message
    self.session.send_message(self.cid, text, self.cstyle, self.emcache.parse(), custom_emoticons)
TypeError: send_message() takes at most 4 arguments (6 given)
```

**Comment by c10ud** [comment]
are you using e3.msn?

**Comment by c10ud** [comment]
btw try pulling again

**Comment by chy168** [comment]
Yes, I use e3.msn session.
I've try pulling new one, but get another error:

```
TypeError: send_message() takes exactly 7 arguments (8 given)
Traceback (most recent call last):
  File "/home/chy168/emesene-    svn/develope/emesene2/emesene/emesene/gui/gtkui/TextBox.py", line 173, in    _on_key_press_event
    self.on_send_message(self.text)
  File "/home/chy168/emesene-    svn/develope/emesene2/emesene/emesene/gui/base/Conversation.py", line 208, in     _on_send_message
    text, self.emcache.parse(), self.emcache.path, self.cstyle, self.first)
TypeError: send_message() takes exactly 7 arguments (8 given)
```

PS. The message will be sent to friend, but no message appended on my conversation window.

**Comment by c10ud** [comment]
i just tried with e3.msn both sending and receiving and it worked :S uhm...

**Comment by chy168** [comment]
When I click a user at contact list, it shown:
    [14:29:48 WARNING msn.Conversation] unknown command: 217 2

I type some message and "enter", I got:
    Traceback (most recent call last):
      File "/tmp/emesene-emesene-19a44ba/emesene/gui/gtkui/TextBox.py", line  173, in _on_key_press_event
        self.on_send_message(self.text)
      File "/tmp/emesene-emesene-19a44ba/emesene/gui/base  /Conversation.py", line 208, in _on_send_message
        text, self.emcache.parse(), self.emcache.path, self.cstyle, self.first)
    TypeError: send_message() takes exactly 7 arguments (8 given)

**Comment by chy168** [comment]
I try to figure out the problem ...

In Conversation gui/base/Conversation.py, line 207
How can I know when the "self.output" object is constructed ?
(How can I find the correct send_message() instant ?)

thank you very much ....

**Comment by c10ud** [comment]
please open a new bug so we can track this problem better, also specify you're using e3.msn instead of "simple" msn (papyon)
