### ISSUE TITLE
Error when logging in with the music plugin enabled

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#974]
```
[20:38:49 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from storage.msn.com:443
[20:38:49 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[20:38:49 ERROR papyon.service.content_roaming] Content Roaming service got error: Content Roaming Error (InvalidObjectHandle): ObjectHandle is Invalid
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/client.py", line 552, in error
    self._dispatch("on_client_error", ClientErrorType.CONTENT_ROAMING, error_code)
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 44, in _dispatch
    if event_handler._dispatch_event(name, *args):
  File "/home/sven/emesene-dev/emesene/e3/papylib/papyon/papyon/event/__init__.py", line 65, in _dispatch_event
    handler(*params)
  File "/home/sven/emesene-dev/emesene/e3/papylib/PapyEvents.py", line 77, in on_client_error
    if error.response and error.response.status and error.response.status == 404:
AttributeError: 'ContentRoamingError' object has no attribute 'response'
```

I can fix the AttributeError, but does anyone know if we can ignore the content roaming error?

**Comment by Sbte** [comment]
Or this one:

```
[20:49:26 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from storage.msn.com:443
[20:49:26 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[20:49:26 ERROR papyon.service.content_roaming] Content Roaming service got error: Content Roaming Error (ItemDoesNotExist): Item Does Not Exist
```

**Comment by c10ud** [comment]
most likely the plugin is trying to set the music message too early?

**Comment by Sbte** [comment]
No it works correctly and it also happens when the song is changed. That's the second error.

The non-papyon error is already fixed btw: cc7c6210bbf49c6ebcb0ca8a8de7331f7f7e2b45

**Comment by c10ud** [comment]
@Sbte how about this bug?

**Comment by Sbte** [comment]
Looks like one of the broken profile bugs. Probably that.
